version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-service
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - OLLAMA_HOST=http://llm:11434
    ports:
      - "8080:8080"
    depends_on:
      - database
      - llm

  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "3000:80"
    depends_on:
      - backend

  llm:
    build: ./llm
    container_name: ollama-service
    ports:
      - "11434:11434"

  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unhinged_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
