#!/bin/bash
# Auto-generated multi-file port conflict resolution script
# Generated by Unhinged build-time port validator
# Run this script to automatically resolve detected port conflicts

set -e

echo '🔧 Unhinged Multi-File Port Conflict Auto-Fix Script'
echo '===================================================='
echo ''

echo '🔍 Fixing port 8082 conflict...'
echo 'Conflicting services: backend, database, backend'

echo '🔍 Fixing port 8083 conflict...'
echo 'Conflicting services: cdc-service, weaviate, flink-jobmanager'

echo '🔍 Fixing port 8100 conflict...'
echo 'Conflicting services: speech-to-text, whisper-tts, whisper-tts'

echo '🔍 Fixing port 26357 conflict...'
echo 'Conflicting services: database, cockroachdb, cockroachdb'

echo '🔍 Fixing port 6479 conflict...'
echo 'Conflicting services: redis, redis, redis'

echo '🔍 Fixing port 9300 conflict...'
echo 'Conflicting services: elasticsearch, elasticsearch, elasticsearch'

echo '🔍 Fixing port 9400 conflict...'
echo 'Conflicting services: elasticsearch, elasticsearch, elasticsearch'

echo '🔍 Fixing port 9142 conflict...'
echo 'Conflicting services: cassandra, cassandra, cassandra'

echo '🔍 Fixing port 8084 conflict...'
echo 'Conflicting services: chroma, cockroachdb, cockroachdb'

echo '🔍 Fixing port 9192 conflict...'
echo 'Conflicting services: kafka, vision-ai, kafka'

echo '🔍 Fixing port 3001 conflict...'
echo 'Conflicting services: grafana, grafana, grafana'

echo '🔍 Fixing port 9190 conflict...'
echo 'Conflicting services: prometheus, persistence-platform, prometheus, persistence-platform, prometheus'

echo '🔍 Fixing port 8190 conflict...'
echo 'Conflicting services: persistence-platform, persistence-platform'

echo '🔍 Fixing port 27117 conflict...'
echo 'Conflicting services: mongodb, mongodb'

echo '🔍 Fixing port 8081 conflict...'
echo 'Conflicting services: weaviate, weaviate'

echo '🔍 Fixing port 7574 conflict...'
echo 'Conflicting services: neo4j, neo4j'

echo '🔍 Fixing port 7787 conflict...'
echo 'Conflicting services: neo4j, neo4j'

echo '🔍 Fixing port 9002 conflict...'
echo 'Conflicting services: minio, minio'

echo '🔍 Fixing port 9101 conflict...'
echo 'Conflicting services: minio, minio'

echo '🔍 Fixing port 16786 conflict...'
echo 'Conflicting services: jaeger, jaeger'

echo '🔍 Fixing port 14368 conflict...'
echo 'Conflicting services: jaeger, jaeger'

# Backup all affected docker-compose files
BACKUP_TIMESTAMP=$(date +%Y%m%d_%H%M%S)

cp /home/e-bliss-station-1/Projects/Unhinged/build-config.yml /home/e-bliss-station-1/Projects/Unhinged/build-config.yml.backup.$BACKUP_TIMESTAMP
cp /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml.backup.$BACKUP_TIMESTAMP
cp /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml.backup.$BACKUP_TIMESTAMP
cp /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml.backup.$BACKUP_TIMESTAMP
cp /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml.backup.$BACKUP_TIMESTAMP
cp /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml.backup.$BACKUP_TIMESTAMP

# Generic fix for port 8082 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move backend to 8182
sed -i 's/8082:8082/8182:8082/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'backend moved from port 8082 to 8182 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 8082 in /home/e-bliss-station-1/Projects/Unhinged/build-config.yml: Move backend to 8182
sed -i 's/8082:8082/8182:8082/g' /home/e-bliss-station-1/Projects/Unhinged/build-config.yml
echo 'backend moved from port 8082 to 8182 in /home/e-bliss-station-1/Projects/Unhinged/build-config.yml'

# Generic fix for port 8082 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move database to 8182
sed -i 's/8082:8082/8182:8082/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'database moved from port 8082 to 8182 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 8083 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move cdc-service to 8183
sed -i 's/8083:8083/8183:8083/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'cdc-service moved from port 8083 to 8183 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 8083 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move weaviate to 8183
sed -i 's/8083:8083/8183:8083/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'weaviate moved from port 8083 to 8183 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 8083 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move flink-jobmanager to 8183
sed -i 's/8083:8083/8183:8083/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'flink-jobmanager moved from port 8083 to 8183 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 8100 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move speech-to-text to 8200
sed -i 's/8100:8100/8200:8100/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'speech-to-text moved from port 8100 to 8200 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 8100 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml: Move whisper-tts to 8200
sed -i 's/8100:8100/8200:8100/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml
echo 'whisper-tts moved from port 8100 to 8200 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml'

# Generic fix for port 8100 in /home/e-bliss-station-1/Projects/Unhinged/build-config.yml: Move whisper-tts to 8200
sed -i 's/8100:8100/8200:8100/g' /home/e-bliss-station-1/Projects/Unhinged/build-config.yml
echo 'whisper-tts moved from port 8100 to 8200 in /home/e-bliss-station-1/Projects/Unhinged/build-config.yml'

# Generic fix for port 26357 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move database to 26457
sed -i 's/26357:26357/26457:26357/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'database moved from port 26357 to 26457 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 26357 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move cockroachdb to 26457
sed -i 's/26357:26357/26457:26357/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'cockroachdb moved from port 26357 to 26457 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 26357 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move cockroachdb to 26457
sed -i 's/26357:26357/26457:26357/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'cockroachdb moved from port 26357 to 26457 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 6479 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move redis to 6579
sed -i 's/6479:6479/6579:6479/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'redis moved from port 6479 to 6579 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 6479 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move redis to 6579
sed -i 's/6479:6479/6579:6479/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'redis moved from port 6479 to 6579 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 6479 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move redis to 6579
sed -i 's/6479:6479/6579:6479/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'redis moved from port 6479 to 6579 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 9300 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move elasticsearch to 9400
sed -i 's/9300:9300/9400:9300/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'elasticsearch moved from port 9300 to 9400 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 9300 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move elasticsearch to 9400
sed -i 's/9300:9300/9400:9300/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'elasticsearch moved from port 9300 to 9400 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9300 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move elasticsearch to 9400
sed -i 's/9300:9300/9400:9300/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'elasticsearch moved from port 9300 to 9400 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 9400 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move elasticsearch to 9500
sed -i 's/9400:9400/9500:9400/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'elasticsearch moved from port 9400 to 9500 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 9400 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move elasticsearch to 9500
sed -i 's/9400:9400/9500:9400/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'elasticsearch moved from port 9400 to 9500 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9400 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move elasticsearch to 9500
sed -i 's/9400:9400/9500:9400/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'elasticsearch moved from port 9400 to 9500 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 9142 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move cassandra to 9242
sed -i 's/9142:9142/9242:9142/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'cassandra moved from port 9142 to 9242 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 9142 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move cassandra to 9242
sed -i 's/9142:9142/9242:9142/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'cassandra moved from port 9142 to 9242 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9142 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move cassandra to 9242
sed -i 's/9142:9142/9242:9142/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'cassandra moved from port 9142 to 9242 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 8084 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move chroma to 8184
sed -i 's/8084:8084/8184:8084/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'chroma moved from port 8084 to 8184 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 8084 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move cockroachdb to 8184
sed -i 's/8084:8084/8184:8084/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'cockroachdb moved from port 8084 to 8184 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 8084 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move cockroachdb to 8184
sed -i 's/8084:8084/8184:8084/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'cockroachdb moved from port 8084 to 8184 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 9192 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move kafka to 9292
sed -i 's/9192:9192/9292:9192/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'kafka moved from port 9192 to 9292 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 9192 in /home/e-bliss-station-1/Projects/Unhinged/build-config.yml: Move kafka to 9292
sed -i 's/9192:9192/9292:9192/g' /home/e-bliss-station-1/Projects/Unhinged/build-config.yml
echo 'kafka moved from port 9192 to 9292 in /home/e-bliss-station-1/Projects/Unhinged/build-config.yml'

# Generic fix for port 9192 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml: Move vision-ai to 9292
sed -i 's/9192:9192/9292:9192/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml
echo 'vision-ai moved from port 9192 to 9292 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml'

# Generic fix for port 3001 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml: Move grafana to 3101
sed -i 's/3001:3001/3101:3001/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml
echo 'grafana moved from port 3001 to 3101 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml'

# Generic fix for port 3001 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move grafana to 3101
sed -i 's/3001:3001/3101:3001/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'grafana moved from port 3001 to 3101 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 3001 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move grafana to 3101
sed -i 's/3001:3001/3101:3001/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'grafana moved from port 3001 to 3101 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 9190 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml: Move prometheus to 9290
sed -i 's/9190:9190/9290:9190/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml
echo 'prometheus moved from port 9190 to 9290 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml'

# Generic fix for port 9190 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move prometheus to 9290
sed -i 's/9190:9190/9290:9190/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'prometheus moved from port 9190 to 9290 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9190 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move prometheus to 9290
sed -i 's/9190:9190/9290:9190/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'prometheus moved from port 9190 to 9290 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 9190 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move persistence-platform to 9290
sed -i 's/9190:9190/9290:9190/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'persistence-platform moved from port 9190 to 9290 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9190 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move persistence-platform to 9290
sed -i 's/9190:9190/9290:9190/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'persistence-platform moved from port 9190 to 9290 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 8190 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move persistence-platform to 8290
sed -i 's/8190:8190/8290:8190/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'persistence-platform moved from port 8190 to 8290 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 8190 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move persistence-platform to 8290
sed -i 's/8190:8190/8290:8190/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'persistence-platform moved from port 8190 to 8290 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 27117 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move mongodb to 27217
sed -i 's/27117:27117/27217:27117/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'mongodb moved from port 27117 to 27217 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 27117 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move mongodb to 27217
sed -i 's/27117:27117/27217:27117/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'mongodb moved from port 27117 to 27217 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 7574 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move neo4j to 7674
sed -i 's/7574:7574/7674:7574/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'neo4j moved from port 7574 to 7674 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 7574 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move neo4j to 7674
sed -i 's/7574:7574/7674:7574/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'neo4j moved from port 7574 to 7674 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 7787 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move neo4j to 7887
sed -i 's/7787:7787/7887:7787/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'neo4j moved from port 7787 to 7887 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 7787 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move neo4j to 7887
sed -i 's/7787:7787/7887:7787/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'neo4j moved from port 7787 to 7887 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 9002 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move minio to 9102
sed -i 's/9002:9002/9102:9002/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'minio moved from port 9002 to 9102 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9002 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move minio to 9102
sed -i 's/9002:9002/9102:9002/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'minio moved from port 9002 to 9102 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 9101 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move minio to 9201
sed -i 's/9101:9101/9201:9101/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'minio moved from port 9101 to 9201 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9101 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move minio to 9201
sed -i 's/9101:9101/9201:9101/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'minio moved from port 9101 to 9201 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 16786 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move jaeger to 16886
sed -i 's/16786:16786/16886:16786/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'jaeger moved from port 16786 to 16886 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 16786 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move jaeger to 16886
sed -i 's/16786:16786/16886:16786/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'jaeger moved from port 16786 to 16886 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 14368 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move jaeger to 14468
sed -i 's/14368:14368/14468:14368/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'jaeger moved from port 14368 to 14468 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 14368 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move jaeger to 14468
sed -i 's/14368:14368/14468:14368/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'jaeger moved from port 14368 to 14468 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

echo '✅ Port conflict fixes applied!'
echo ''
echo '🔍 Re-running validation to verify fixes...'
cd build && python build.py validate-ports

echo '🎉 Port conflict resolution complete!'
echo 'You can now run: make start'
