#!/bin/bash
# Auto-generated port conflict resolution script
# Generated by Unhinged build-time port validator
# Run this script to automatically resolve detected port conflicts

set -e

echo '🔧 Unhinged Port Conflict Auto-Fix Script'
echo '========================================='
echo ''

echo '🔍 Fixing port 8080 conflict...'
echo 'Conflicting services: backend, database, cockroachdb, cockroachdb, backend'

echo '🔍 Fixing port 8081 conflict...'
echo 'Conflicting services: cdc-service, flink-jobmanager, weaviate, weaviate'

echo '🔍 Fixing port 3000 conflict...'
echo 'Conflicting services: frontend, grafana, grafana'

echo '🔍 Fixing port 11434 conflict...'
echo 'Conflicting services: llm, llm'

echo '🔍 Fixing port 8001 conflict...'
echo 'Conflicting services: vision-ai, vision-ai'

echo '🔍 Fixing port 8000 conflict...'
echo 'Conflicting services: speech-to-text, whisper-tts, whisper-tts'

echo '🔍 Fixing port 26257 conflict...'
echo 'Conflicting services: database, cockroachdb, cockroachdb'

echo '🔍 Fixing port 6379 conflict...'
echo 'Conflicting services: redis, redis, redis'

echo '🔍 Fixing port 9200 conflict...'
echo 'Conflicting services: elasticsearch, elasticsearch, elasticsearch'

echo '🔍 Fixing port 9300 conflict...'
echo 'Conflicting services: elasticsearch, elasticsearch, elasticsearch'

echo '🔍 Fixing port 9042 conflict...'
echo 'Conflicting services: cassandra, cassandra, cassandra'

echo '🔍 Fixing port 2181 conflict...'
echo 'Conflicting services: zookeeper, zookeeper'

echo '🔍 Fixing port 9092 conflict...'
echo 'Conflicting services: kafka, vision-ai, kafka'

echo '🔍 Fixing port 9090 conflict...'
echo 'Conflicting services: prometheus, persistence-platform, prometheus, persistence-platform, prometheus'

echo '🔍 Fixing port 8090 conflict...'
echo 'Conflicting services: persistence-platform, persistence-platform'

echo '🔍 Fixing port 27017 conflict...'
echo 'Conflicting services: mongodb, mongodb'

echo '🔍 Fixing port 7474 conflict...'
echo 'Conflicting services: neo4j, neo4j'

echo '🔍 Fixing port 7687 conflict...'
echo 'Conflicting services: neo4j, neo4j'

echo '🔍 Fixing port 9000 conflict...'
echo 'Conflicting services: minio, minio'

echo '🔍 Fixing port 9001 conflict...'
echo 'Conflicting services: minio, minio'

echo '🔍 Fixing port 16686 conflict...'
echo 'Conflicting services: jaeger, jaeger'

echo '🔍 Fixing port 14268 conflict...'
echo 'Conflicting services: jaeger, jaeger'

# Backup original docker-compose files
cp docker-compose.yml docker-compose.yml.backup.$(date +%Y%m%d_%H%M%S)

# Fix port 8080 conflict: Move CockroachDB admin UI to 8082
sed -i 's/8080:8080/8082:8080/g' docker-compose.yml
echo 'CockroachDB admin UI moved to port 8082'

# Fix port 8081 conflict: Move cdc-service to 8083
sed -i 's/8081:8081/8083:8081/g' docker-compose.yml
echo 'CDC service moved to port 8083'

# Fix port 3000 conflict: Move Grafana to 3001
sed -i 's/3000:3000/3001:3000/g' docker-compose.yml
echo 'Grafana moved to port 3001'

# Generic fix for port 11434: Move to 11534
sed -i 's/11434:11434/11534:11434/g' docker-compose.yml
echo 'Services moved from port 11434 to 11534'

# Generic fix for port 8001: Move to 8101
sed -i 's/8001:8001/8101:8001/g' docker-compose.yml
echo 'Services moved from port 8001 to 8101'

# Generic fix for port 8000: Move to 8100
sed -i 's/8000:8000/8100:8000/g' docker-compose.yml
echo 'Services moved from port 8000 to 8100'

# Generic fix for port 26257: Move to 26357
sed -i 's/26257:26257/26357:26257/g' docker-compose.yml
echo 'Services moved from port 26257 to 26357'

# Generic fix for port 6379: Move to 6479
sed -i 's/6379:6379/6479:6379/g' docker-compose.yml
echo 'Services moved from port 6379 to 6479'

# Generic fix for port 9200: Move to 9300
sed -i 's/9200:9200/9300:9200/g' docker-compose.yml
echo 'Services moved from port 9200 to 9300'

# Generic fix for port 9300: Move to 9400
sed -i 's/9300:9300/9400:9300/g' docker-compose.yml
echo 'Services moved from port 9300 to 9400'

# Generic fix for port 9042: Move to 9142
sed -i 's/9042:9042/9142:9042/g' docker-compose.yml
echo 'Services moved from port 9042 to 9142'

# Generic fix for port 2181: Move to 2281
sed -i 's/2181:2181/2281:2181/g' docker-compose.yml
echo 'Services moved from port 2181 to 2281'

# Generic fix for port 9092: Move to 9192
sed -i 's/9092:9092/9192:9092/g' docker-compose.yml
echo 'Services moved from port 9092 to 9192'

# Generic fix for port 9090: Move to 9190
sed -i 's/9090:9090/9190:9090/g' docker-compose.yml
echo 'Services moved from port 9090 to 9190'

# Generic fix for port 8090: Move to 8190
sed -i 's/8090:8090/8190:8090/g' docker-compose.yml
echo 'Services moved from port 8090 to 8190'

# Generic fix for port 27017: Move to 27117
sed -i 's/27017:27017/27117:27017/g' docker-compose.yml
echo 'Services moved from port 27017 to 27117'

# Generic fix for port 7474: Move to 7574
sed -i 's/7474:7474/7574:7474/g' docker-compose.yml
echo 'Services moved from port 7474 to 7574'

# Generic fix for port 7687: Move to 7787
sed -i 's/7687:7687/7787:7687/g' docker-compose.yml
echo 'Services moved from port 7687 to 7787'

# Fix port 9000 conflict: Move MinIO to 9002
sed -i 's/9000:9000/9002:9000/g' docker-compose.yml
echo 'MinIO moved to port 9002 (our control proxy needs 9000)'

# Generic fix for port 9001: Move to 9101
sed -i 's/9001:9001/9101:9001/g' docker-compose.yml
echo 'Services moved from port 9001 to 9101'

# Generic fix for port 16686: Move to 16786
sed -i 's/16686:16686/16786:16686/g' docker-compose.yml
echo 'Services moved from port 16686 to 16786'

# Generic fix for port 14268: Move to 14368
sed -i 's/14268:14268/14368:14268/g' docker-compose.yml
echo 'Services moved from port 14268 to 14368'

echo '✅ Port conflict fixes applied!'
echo ''
echo '🔍 Re-running validation to verify fixes...'
cd build && python build.py validate-ports

echo '🎉 Port conflict resolution complete!'
echo 'You can now run: make start'
