#!/bin/bash
# Auto-generated multi-file port conflict resolution script
# Generated by Unhinged build-time port validator
# Run this script to automatically resolve detected port conflicts

set -e

echo '🔧 Unhinged Multi-File Port Conflict Auto-Fix Script'
echo '===================================================='
echo ''

echo '🔍 Fixing port 8082 conflict...'
echo 'Conflicting services: backend, database, spark-master'

echo '🔍 Fixing port 8083 conflict...'
echo 'Conflicting services: cdc-service, weaviate, flink-jobmanager'

echo '🔍 Fixing port 3000 conflict...'
echo 'Conflicting services: frontend, grafana, grafana'

echo '🔍 Fixing port 9300 conflict...'
echo 'Conflicting services: elasticsearch, elasticsearch, elasticsearch'

echo '🔍 Fixing port 8000 conflict...'
echo 'Conflicting services: whisper-tts, whisper-tts'

echo '🔍 Fixing port 9092 conflict...'
echo 'Conflicting services: vision-ai, kafka'

echo '🔍 Fixing port 9090 conflict...'
echo 'Conflicting services: prometheus, persistence-platform, prometheus, persistence-platform, prometheus'

echo '🔍 Fixing port 8090 conflict...'
echo 'Conflicting services: persistence-platform, persistence-platform'

echo '🔍 Fixing port 6379 conflict...'
echo 'Conflicting services: redis, redis'

echo '🔍 Fixing port 26257 conflict...'
echo 'Conflicting services: cockroachdb, cockroachdb'

echo '🔍 Fixing port 8080 conflict...'
echo 'Conflicting services: cockroachdb, cockroachdb, backend'

echo '🔍 Fixing port 27017 conflict...'
echo 'Conflicting services: mongodb, mongodb'

echo '🔍 Fixing port 8081 conflict...'
echo 'Conflicting services: weaviate, weaviate'

echo '🔍 Fixing port 9200 conflict...'
echo 'Conflicting services: elasticsearch, elasticsearch'

echo '🔍 Fixing port 9042 conflict...'
echo 'Conflicting services: cassandra, cassandra'

echo '🔍 Fixing port 7474 conflict...'
echo 'Conflicting services: neo4j, neo4j'

echo '🔍 Fixing port 7687 conflict...'
echo 'Conflicting services: neo4j, neo4j'

echo '🔍 Fixing port 9000 conflict...'
echo 'Conflicting services: minio, minio'

echo '🔍 Fixing port 9001 conflict...'
echo 'Conflicting services: minio, minio'

echo '🔍 Fixing port 16686 conflict...'
echo 'Conflicting services: jaeger, jaeger'

echo '🔍 Fixing port 14268 conflict...'
echo 'Conflicting services: jaeger, jaeger'

# Backup all affected docker-compose files
BACKUP_TIMESTAMP=$(date +%Y%m%d_%H%M%S)

cp /home/e-bliss-station-1/Projects/Unhinged/build-config.yml /home/e-bliss-station-1/Projects/Unhinged/build-config.yml.backup.$BACKUP_TIMESTAMP
cp /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml.backup.$BACKUP_TIMESTAMP
cp /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml.backup.$BACKUP_TIMESTAMP
cp /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml.backup.$BACKUP_TIMESTAMP
cp /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml.backup.$BACKUP_TIMESTAMP
cp /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml.backup.$BACKUP_TIMESTAMP

# Generic fix for port 8082 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move backend to 8182
sed -i 's/8082:8082/8182:8082/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'backend moved from port 8082 to 8182 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 8082 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move database to 8182
sed -i 's/8082:8082/8182:8082/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'database moved from port 8082 to 8182 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 8082 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move spark-master to 8182
sed -i 's/8082:8082/8182:8082/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'spark-master moved from port 8082 to 8182 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 8083 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move cdc-service to 8183
sed -i 's/8083:8083/8183:8083/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'cdc-service moved from port 8083 to 8183 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 8083 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move weaviate to 8183
sed -i 's/8083:8083/8183:8083/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'weaviate moved from port 8083 to 8183 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 8083 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move flink-jobmanager to 8183
sed -i 's/8083:8083/8183:8083/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'flink-jobmanager moved from port 8083 to 8183 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Fix port 3000 conflict in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move Grafana to 3001
sed -i 's/3000:3000/3001:3000/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'Grafana moved to port 3001 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Fix port 3000 conflict in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move Grafana to 3001
sed -i 's/3000:3000/3001:3000/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'Grafana moved to port 3001 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 9300 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml: Move elasticsearch to 9400
sed -i 's/9300:9300/9400:9300/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml
echo 'elasticsearch moved from port 9300 to 9400 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.yml'

# Generic fix for port 9300 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move elasticsearch to 9400
sed -i 's/9300:9300/9400:9300/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'elasticsearch moved from port 9300 to 9400 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9300 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move elasticsearch to 9400
sed -i 's/9300:9300/9400:9300/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'elasticsearch moved from port 9300 to 9400 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 8000 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml: Move whisper-tts to 8100
sed -i 's/8000:8000/8100:8000/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml
echo 'whisper-tts moved from port 8000 to 8100 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml'

# Generic fix for port 8000 in /home/e-bliss-station-1/Projects/Unhinged/build-config.yml: Move whisper-tts to 8100
sed -i 's/8000:8000/8100:8000/g' /home/e-bliss-station-1/Projects/Unhinged/build-config.yml
echo 'whisper-tts moved from port 8000 to 8100 in /home/e-bliss-station-1/Projects/Unhinged/build-config.yml'

# Generic fix for port 9092 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml: Move vision-ai to 9192
sed -i 's/9092:9092/9192:9092/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml
echo 'vision-ai moved from port 9092 to 9192 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.simple.yml'

# Generic fix for port 9092 in /home/e-bliss-station-1/Projects/Unhinged/build-config.yml: Move kafka to 9192
sed -i 's/9092:9092/9192:9092/g' /home/e-bliss-station-1/Projects/Unhinged/build-config.yml
echo 'kafka moved from port 9092 to 9192 in /home/e-bliss-station-1/Projects/Unhinged/build-config.yml'

# Generic fix for port 9090 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml: Move prometheus to 9190
sed -i 's/9090:9090/9190:9090/g' /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml
echo 'prometheus moved from port 9090 to 9190 in /home/e-bliss-station-1/Projects/Unhinged/docker-compose.observability.yml'

# Generic fix for port 9090 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move prometheus to 9190
sed -i 's/9090:9090/9190:9090/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'prometheus moved from port 9090 to 9190 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9090 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move prometheus to 9190
sed -i 's/9090:9090/9190:9090/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'prometheus moved from port 9090 to 9190 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 9090 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move persistence-platform to 9190
sed -i 's/9090:9090/9190:9090/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'persistence-platform moved from port 9090 to 9190 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9090 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move persistence-platform to 9190
sed -i 's/9090:9090/9190:9090/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'persistence-platform moved from port 9090 to 9190 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 8090 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move persistence-platform to 8190
sed -i 's/8090:8090/8190:8090/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'persistence-platform moved from port 8090 to 8190 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 8090 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move persistence-platform to 8190
sed -i 's/8090:8090/8190:8090/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'persistence-platform moved from port 8090 to 8190 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 6379 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move redis to 6479
sed -i 's/6379:6379/6479:6379/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'redis moved from port 6379 to 6479 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 6379 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move redis to 6479
sed -i 's/6379:6379/6479:6379/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'redis moved from port 6379 to 6479 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 26257 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move cockroachdb to 26357
sed -i 's/26257:26257/26357:26257/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'cockroachdb moved from port 26257 to 26357 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 26257 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move cockroachdb to 26357
sed -i 's/26257:26257/26357:26257/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'cockroachdb moved from port 26257 to 26357 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Fix port 8080 conflict in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move CockroachDB admin UI to 8084
sed -i 's/8080:8080/8084:8080/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'CockroachDB admin UI moved to port 8084 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Fix port 8080 conflict in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move CockroachDB admin UI to 8084
sed -i 's/8080:8080/8084:8080/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'CockroachDB admin UI moved to port 8084 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Fix port 8080 conflict in /home/e-bliss-station-1/Projects/Unhinged/build-config.yml: Move backend to 8082
sed -i 's/8080:8080/8082:8080/g' /home/e-bliss-station-1/Projects/Unhinged/build-config.yml
echo 'Backend service moved to port 8082 in /home/e-bliss-station-1/Projects/Unhinged/build-config.yml'

# Generic fix for port 27017 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move mongodb to 27117
sed -i 's/27017:27017/27117:27017/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'mongodb moved from port 27017 to 27117 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 27017 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move mongodb to 27117
sed -i 's/27017:27017/27117:27017/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'mongodb moved from port 27017 to 27117 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 9200 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move elasticsearch to 9300
sed -i 's/9200:9200/9300:9200/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'elasticsearch moved from port 9200 to 9300 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9200 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move elasticsearch to 9300
sed -i 's/9200:9200/9300:9200/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'elasticsearch moved from port 9200 to 9300 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 9042 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move cassandra to 9142
sed -i 's/9042:9042/9142:9042/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'cassandra moved from port 9042 to 9142 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9042 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move cassandra to 9142
sed -i 's/9042:9042/9142:9042/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'cassandra moved from port 9042 to 9142 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 7474 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move neo4j to 7574
sed -i 's/7474:7474/7574:7474/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'neo4j moved from port 7474 to 7574 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 7474 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move neo4j to 7574
sed -i 's/7474:7474/7574:7474/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'neo4j moved from port 7474 to 7574 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 7687 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move neo4j to 7787
sed -i 's/7687:7687/7787:7687/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'neo4j moved from port 7687 to 7787 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 7687 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move neo4j to 7787
sed -i 's/7687:7687/7787:7687/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'neo4j moved from port 7687 to 7787 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Fix port 9000 conflict in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move minio to 9002
sed -i 's/9000:9000/9002:9000/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'minio moved to port 9002 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml (control proxy needs 9000)'

# Fix port 9000 conflict in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move minio to 9002
sed -i 's/9000:9000/9002:9000/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'minio moved to port 9002 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml (control proxy needs 9000)'

# Generic fix for port 9001 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move minio to 9101
sed -i 's/9001:9001/9101:9001/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'minio moved from port 9001 to 9101 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 9001 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move minio to 9101
sed -i 's/9001:9001/9101:9001/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'minio moved from port 9001 to 9101 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 16686 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move jaeger to 16786
sed -i 's/16686:16686/16786:16686/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'jaeger moved from port 16686 to 16786 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 16686 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move jaeger to 16786
sed -i 's/16686:16686/16786:16686/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'jaeger moved from port 16686 to 16786 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

# Generic fix for port 14268 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml: Move jaeger to 14368
sed -i 's/14268:14268/14368:14268/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml
echo 'jaeger moved from port 14268 to 14368 in /home/e-bliss-station-1/Projects/Unhinged/platforms/docker-compose.all.yml'

# Generic fix for port 14268 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml: Move jaeger to 14368
sed -i 's/14268:14268/14368:14268/g' /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml
echo 'jaeger moved from port 14268 to 14368 in /home/e-bliss-station-1/Projects/Unhinged/platforms/persistence/docker-compose.yml'

echo '✅ Port conflict fixes applied!'
echo ''
echo '🔍 Re-running validation to verify fixes...'
cd build && python build.py validate-ports

echo '🎉 Port conflict resolution complete!'
echo 'You can now run: make start'
