#!/usr/bin/env python3
"""
@llm-type driver.git
@llm-does Git hook management for quality gate enforcement

Manages Git hooks installation, configuration, and enforcement.
Provides programmatic interface for hook management.
"""

import os
import stat
from pathlib import Path


class GitHookManager:
    """Manages Git hooks for quality gate enforcement."""

    def __init__(self, repo_root: Path):
        """Initialize Git hook manager.

        Args:
            repo_root: Path to repository root
        """
        self.repo_root = repo_root
        self.hooks_dir = repo_root / ".git" / "hooks"
        self.pre_commit_hook = self.hooks_dir / "pre-commit"

    def install_quality_gate_hook(self) -> bool:
        """Install pre-commit hook for quality gate enforcement.

        Returns:
            True if installation successful, False otherwise
        """
        if not self.hooks_dir.exists():
            self.hooks_dir.mkdir(parents=True, exist_ok=True)

        hook_content = self._generate_pre_commit_hook()

        try:
            self.pre_commit_hook.write_text(hook_content)
            self.pre_commit_hook.chmod(self.pre_commit_hook.stat().st_mode | stat.S_IEXEC)
            return True
        except Exception as e:
            print(f"Failed to install pre-commit hook: {e}")
            return False

    def _generate_pre_commit_hook(self) -> str:
        """Generate pre-commit hook script content.

        Returns:
            Hook script content as string
        """
        return """#!/bin/bash
#
# Unhinged Quality Gate Enforcement
# Generated by: libs/python/drivers/git/hooks.py

set -e

REPO_ROOT="$(git rev-parse --show-toplevel)"

if [[ "$*" == *"--no-verify"* ]]; then
    echo ""
    echo "🚫 --no-verify DETECTED - Quality gates cannot be bypassed"
    exit 1
fi

if [[ -n "$SKIP" ]]; then
    echo ""
    echo "🚫 SKIP DETECTED: $SKIP - Quality gates cannot be bypassed"
    exit 1
fi

python3 "$REPO_ROOT/libs/python/drivers/git/quality_gates.py"
exit $?
"""

    def is_installed(self) -> bool:
        """Check if quality gate hook is installed.

        Returns:
            True if hook exists and is executable
        """
        return self.pre_commit_hook.exists() and os.access(self.pre_commit_hook, os.X_OK)

    def uninstall(self) -> bool:
        """Uninstall pre-commit hook.

        Returns:
            True if uninstallation successful
        """
        try:
            if self.pre_commit_hook.exists():
                self.pre_commit_hook.unlink()
            return True
        except Exception as e:
            print(f"Failed to uninstall pre-commit hook: {e}")
            return False
