// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializeagentFailed")
public inline fun agentFailed(block: unhinged.cdc.AgentFailedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.AgentFailed =
  unhinged.cdc.AgentFailedKt.Dsl._create(unhinged.cdc.CdcEvents.AgentFailed.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.AgentFailed`
 */
public object AgentFailedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.AgentFailed.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.AgentFailed.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.AgentFailed = _builder.build()

    /**
     * `string failure_reason = 1;`
     */
    public var failureReason: kotlin.String
      @JvmName("getFailureReason")
      get() = _builder.getFailureReason()
      @JvmName("setFailureReason")
      set(value) {
        _builder.setFailureReason(value)
      }
    /**
     * `string failure_reason = 1;`
     */
    public fun clearFailureReason() {
      _builder.clearFailureReason()
    }

    /**
     * `string error_message = 2;`
     */
    public var errorMessage: kotlin.String
      @JvmName("getErrorMessage")
      get() = _builder.getErrorMessage()
      @JvmName("setErrorMessage")
      set(value) {
        _builder.setErrorMessage(value)
      }
    /**
     * `string error_message = 2;`
     */
    public fun clearErrorMessage() {
      _builder.clearErrorMessage()
    }

    /**
     * `int32 failed_at_step = 3;`
     */
    public var failedAtStep: kotlin.Int
      @JvmName("getFailedAtStep")
      get() = _builder.getFailedAtStep()
      @JvmName("setFailedAtStep")
      set(value) {
        _builder.setFailedAtStep(value)
      }
    /**
     * `int32 failed_at_step = 3;`
     */
    public fun clearFailedAtStep() {
      _builder.clearFailedAtStep()
    }

    /**
     * `bool is_recoverable = 4;`
     */
    public var isRecoverable: kotlin.Boolean
      @JvmName("getIsRecoverable")
      get() = _builder.getIsRecoverable()
      @JvmName("setIsRecoverable")
      set(value) {
        _builder.setIsRecoverable(value)
      }
    /**
     * `bool is_recoverable = 4;`
     */
    public fun clearIsRecoverable() {
      _builder.clearIsRecoverable()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.AgentFailed.copy(block: `unhinged.cdc`.AgentFailedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.AgentFailed =
  `unhinged.cdc`.AgentFailedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

