// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializeaudioEvent")
public inline fun audioEvent(block: unhinged.cdc.AudioEventKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.AudioEvent =
  unhinged.cdc.AudioEventKt.Dsl._create(unhinged.cdc.CdcEvents.AudioEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.AudioEvent`
 */
public object AudioEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.AudioEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.AudioEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.AudioEvent = _builder.build()

    /**
     * `string audio_id = 1;`
     */
    public var audioId: kotlin.String
      @JvmName("getAudioId")
      get() = _builder.getAudioId()
      @JvmName("setAudioId")
      set(value) {
        _builder.setAudioId(value)
      }
    /**
     * `string audio_id = 1;`
     */
    public fun clearAudioId() {
      _builder.clearAudioId()
    }

    /**
     * `.unhinged.cdc.AudioEventType event_type = 2;`
     */
    public var eventType: unhinged.cdc.CdcEvents.AudioEventType
      @JvmName("getEventType")
      get() = _builder.getEventType()
      @JvmName("setEventType")
      set(value) {
        _builder.setEventType(value)
      }
    public var eventTypeValue: kotlin.Int
      @JvmName("getEventTypeValue")
      get() = _builder.getEventTypeValue()
      @JvmName("setEventTypeValue")
      set(value) {
        _builder.setEventTypeValue(value)
      }
    /**
     * `.unhinged.cdc.AudioEventType event_type = 2;`
     */
    public fun clearEventType() {
      _builder.clearEventType()
    }

    /**
     * `.unhinged.cdc.TTSStarted tts_started = 10;`
     */
    public var ttsStarted: unhinged.cdc.CdcEvents.TTSStarted
      @JvmName("getTtsStarted")
      get() = _builder.getTtsStarted()
      @JvmName("setTtsStarted")
      set(value) {
        _builder.setTtsStarted(value)
      }
    /**
     * `.unhinged.cdc.TTSStarted tts_started = 10;`
     */
    public fun clearTtsStarted() {
      _builder.clearTtsStarted()
    }
    /**
     * `.unhinged.cdc.TTSStarted tts_started = 10;`
     * @return Whether the ttsStarted field is set.
     */
    public fun hasTtsStarted(): kotlin.Boolean {
      return _builder.hasTtsStarted()
    }

    /**
     * `.unhinged.cdc.TTSCompleted tts_completed = 11;`
     */
    public var ttsCompleted: unhinged.cdc.CdcEvents.TTSCompleted
      @JvmName("getTtsCompleted")
      get() = _builder.getTtsCompleted()
      @JvmName("setTtsCompleted")
      set(value) {
        _builder.setTtsCompleted(value)
      }
    /**
     * `.unhinged.cdc.TTSCompleted tts_completed = 11;`
     */
    public fun clearTtsCompleted() {
      _builder.clearTtsCompleted()
    }
    /**
     * `.unhinged.cdc.TTSCompleted tts_completed = 11;`
     * @return Whether the ttsCompleted field is set.
     */
    public fun hasTtsCompleted(): kotlin.Boolean {
      return _builder.hasTtsCompleted()
    }

    /**
     * `.unhinged.cdc.STTCompleted stt_completed = 12;`
     */
    public var sttCompleted: unhinged.cdc.CdcEvents.STTCompleted
      @JvmName("getSttCompleted")
      get() = _builder.getSttCompleted()
      @JvmName("setSttCompleted")
      set(value) {
        _builder.setSttCompleted(value)
      }
    /**
     * `.unhinged.cdc.STTCompleted stt_completed = 12;`
     */
    public fun clearSttCompleted() {
      _builder.clearSttCompleted()
    }
    /**
     * `.unhinged.cdc.STTCompleted stt_completed = 12;`
     * @return Whether the sttCompleted field is set.
     */
    public fun hasSttCompleted(): kotlin.Boolean {
      return _builder.hasSttCompleted()
    }
    public val eventDataCase: unhinged.cdc.CdcEvents.AudioEvent.EventDataCase
      @JvmName("getEventDataCase")
      get() = _builder.getEventDataCase()

    public fun clearEventData() {
      _builder.clearEventData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.AudioEvent.copy(block: `unhinged.cdc`.AudioEventKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.AudioEvent =
  `unhinged.cdc`.AudioEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.cdc.CdcEvents.AudioEventOrBuilder.ttsStartedOrNull: unhinged.cdc.CdcEvents.TTSStarted?
  get() = if (hasTtsStarted()) getTtsStarted() else null

public val unhinged.cdc.CdcEvents.AudioEventOrBuilder.ttsCompletedOrNull: unhinged.cdc.CdcEvents.TTSCompleted?
  get() = if (hasTtsCompleted()) getTtsCompleted() else null

public val unhinged.cdc.CdcEvents.AudioEventOrBuilder.sttCompletedOrNull: unhinged.cdc.CdcEvents.STTCompleted?
  get() = if (hasSttCompleted()) getSttCompleted() else null

