// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializechatEvent")
public inline fun chatEvent(block: unhinged.cdc.ChatEventKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.ChatEvent =
  unhinged.cdc.ChatEventKt.Dsl._create(unhinged.cdc.CdcEvents.ChatEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.ChatEvent`
 */
public object ChatEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.ChatEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.ChatEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.ChatEvent = _builder.build()

    /**
     * `string conversation_id = 1;`
     */
    public var conversationId: kotlin.String
      @JvmName("getConversationId")
      get() = _builder.getConversationId()
      @JvmName("setConversationId")
      set(value) {
        _builder.setConversationId(value)
      }
    /**
     * `string conversation_id = 1;`
     */
    public fun clearConversationId() {
      _builder.clearConversationId()
    }

    /**
     * `string message_id = 2;`
     */
    public var messageId: kotlin.String
      @JvmName("getMessageId")
      get() = _builder.getMessageId()
      @JvmName("setMessageId")
      set(value) {
        _builder.setMessageId(value)
      }
    /**
     * `string message_id = 2;`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }

    /**
     * `.unhinged.cdc.ChatEventType event_type = 3;`
     */
    public var eventType: unhinged.cdc.CdcEvents.ChatEventType
      @JvmName("getEventType")
      get() = _builder.getEventType()
      @JvmName("setEventType")
      set(value) {
        _builder.setEventType(value)
      }
    public var eventTypeValue: kotlin.Int
      @JvmName("getEventTypeValue")
      get() = _builder.getEventTypeValue()
      @JvmName("setEventTypeValue")
      set(value) {
        _builder.setEventTypeValue(value)
      }
    /**
     * `.unhinged.cdc.ChatEventType event_type = 3;`
     */
    public fun clearEventType() {
      _builder.clearEventType()
    }

    /**
     * `.unhinged.cdc.ConversationCreated conversation_created = 10;`
     */
    public var conversationCreated: unhinged.cdc.CdcEvents.ConversationCreated
      @JvmName("getConversationCreated")
      get() = _builder.getConversationCreated()
      @JvmName("setConversationCreated")
      set(value) {
        _builder.setConversationCreated(value)
      }
    /**
     * `.unhinged.cdc.ConversationCreated conversation_created = 10;`
     */
    public fun clearConversationCreated() {
      _builder.clearConversationCreated()
    }
    /**
     * `.unhinged.cdc.ConversationCreated conversation_created = 10;`
     * @return Whether the conversationCreated field is set.
     */
    public fun hasConversationCreated(): kotlin.Boolean {
      return _builder.hasConversationCreated()
    }

    /**
     * `.unhinged.cdc.MessageSent message_sent = 11;`
     */
    public var messageSent: unhinged.cdc.CdcEvents.MessageSent
      @JvmName("getMessageSent")
      get() = _builder.getMessageSent()
      @JvmName("setMessageSent")
      set(value) {
        _builder.setMessageSent(value)
      }
    /**
     * `.unhinged.cdc.MessageSent message_sent = 11;`
     */
    public fun clearMessageSent() {
      _builder.clearMessageSent()
    }
    /**
     * `.unhinged.cdc.MessageSent message_sent = 11;`
     * @return Whether the messageSent field is set.
     */
    public fun hasMessageSent(): kotlin.Boolean {
      return _builder.hasMessageSent()
    }

    /**
     * `.unhinged.cdc.MessageUpdated message_updated = 12;`
     */
    public var messageUpdated: unhinged.cdc.CdcEvents.MessageUpdated
      @JvmName("getMessageUpdated")
      get() = _builder.getMessageUpdated()
      @JvmName("setMessageUpdated")
      set(value) {
        _builder.setMessageUpdated(value)
      }
    /**
     * `.unhinged.cdc.MessageUpdated message_updated = 12;`
     */
    public fun clearMessageUpdated() {
      _builder.clearMessageUpdated()
    }
    /**
     * `.unhinged.cdc.MessageUpdated message_updated = 12;`
     * @return Whether the messageUpdated field is set.
     */
    public fun hasMessageUpdated(): kotlin.Boolean {
      return _builder.hasMessageUpdated()
    }

    /**
     * `.unhinged.cdc.TypingStarted typing_started = 13;`
     */
    public var typingStarted: unhinged.cdc.CdcEvents.TypingStarted
      @JvmName("getTypingStarted")
      get() = _builder.getTypingStarted()
      @JvmName("setTypingStarted")
      set(value) {
        _builder.setTypingStarted(value)
      }
    /**
     * `.unhinged.cdc.TypingStarted typing_started = 13;`
     */
    public fun clearTypingStarted() {
      _builder.clearTypingStarted()
    }
    /**
     * `.unhinged.cdc.TypingStarted typing_started = 13;`
     * @return Whether the typingStarted field is set.
     */
    public fun hasTypingStarted(): kotlin.Boolean {
      return _builder.hasTypingStarted()
    }

    /**
     * `.unhinged.cdc.ParticipantJoined participant_joined = 14;`
     */
    public var participantJoined: unhinged.cdc.CdcEvents.ParticipantJoined
      @JvmName("getParticipantJoined")
      get() = _builder.getParticipantJoined()
      @JvmName("setParticipantJoined")
      set(value) {
        _builder.setParticipantJoined(value)
      }
    /**
     * `.unhinged.cdc.ParticipantJoined participant_joined = 14;`
     */
    public fun clearParticipantJoined() {
      _builder.clearParticipantJoined()
    }
    /**
     * `.unhinged.cdc.ParticipantJoined participant_joined = 14;`
     * @return Whether the participantJoined field is set.
     */
    public fun hasParticipantJoined(): kotlin.Boolean {
      return _builder.hasParticipantJoined()
    }
    public val eventDataCase: unhinged.cdc.CdcEvents.ChatEvent.EventDataCase
      @JvmName("getEventDataCase")
      get() = _builder.getEventDataCase()

    public fun clearEventData() {
      _builder.clearEventData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.ChatEvent.copy(block: `unhinged.cdc`.ChatEventKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.ChatEvent =
  `unhinged.cdc`.ChatEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.cdc.CdcEvents.ChatEventOrBuilder.conversationCreatedOrNull: unhinged.cdc.CdcEvents.ConversationCreated?
  get() = if (hasConversationCreated()) getConversationCreated() else null

public val unhinged.cdc.CdcEvents.ChatEventOrBuilder.messageSentOrNull: unhinged.cdc.CdcEvents.MessageSent?
  get() = if (hasMessageSent()) getMessageSent() else null

public val unhinged.cdc.CdcEvents.ChatEventOrBuilder.messageUpdatedOrNull: unhinged.cdc.CdcEvents.MessageUpdated?
  get() = if (hasMessageUpdated()) getMessageUpdated() else null

public val unhinged.cdc.CdcEvents.ChatEventOrBuilder.typingStartedOrNull: unhinged.cdc.CdcEvents.TypingStarted?
  get() = if (hasTypingStarted()) getTypingStarted() else null

public val unhinged.cdc.CdcEvents.ChatEventOrBuilder.participantJoinedOrNull: unhinged.cdc.CdcEvents.ParticipantJoined?
  get() = if (hasParticipantJoined()) getParticipantJoined() else null

