// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializeconversationCreated")
public inline fun conversationCreated(block: unhinged.cdc.ConversationCreatedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.ConversationCreated =
  unhinged.cdc.ConversationCreatedKt.Dsl._create(unhinged.cdc.CdcEvents.ConversationCreated.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.ConversationCreated`
 */
public object ConversationCreatedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.ConversationCreated.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.ConversationCreated.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.ConversationCreated = _builder.build()

    /**
     * `string title = 1;`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }
    /**
     * `string title = 1;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * `string created_by = 2;`
     */
    public var createdBy: kotlin.String
      @JvmName("getCreatedBy")
      get() = _builder.getCreatedBy()
      @JvmName("setCreatedBy")
      set(value) {
        _builder.setCreatedBy(value)
      }
    /**
     * `string created_by = 2;`
     */
    public fun clearCreatedBy() {
      _builder.clearCreatedBy()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ParticipantIdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string participant_ids = 3;`
     * @return A list containing the participantIds.
     */
    public val participantIds: com.google.protobuf.kotlin.DslList<kotlin.String, ParticipantIdsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getParticipantIdsList()
      )
    /**
     * `repeated string participant_ids = 3;`
     * @param value The participantIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addParticipantIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ParticipantIdsProxy>.add(value: kotlin.String) {
      _builder.addParticipantIds(value)
    }
    /**
     * `repeated string participant_ids = 3;`
     * @param value The participantIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignParticipantIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ParticipantIdsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string participant_ids = 3;`
     * @param values The participantIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllParticipantIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ParticipantIdsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllParticipantIds(values)
    }
    /**
     * `repeated string participant_ids = 3;`
     * @param values The participantIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllParticipantIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ParticipantIdsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string participant_ids = 3;`
     * @param index The index to set the value at.
     * @param value The participantIds to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setParticipantIds")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ParticipantIdsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setParticipantIds(index, value)
    }/**
     * `repeated string participant_ids = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearParticipantIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ParticipantIdsProxy>.clear() {
      _builder.clearParticipantIds()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.ConversationCreated.copy(block: `unhinged.cdc`.ConversationCreatedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.ConversationCreated =
  `unhinged.cdc`.ConversationCreatedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

