// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializedeadLetterEvent")
public inline fun deadLetterEvent(block: unhinged.cdc.DeadLetterEventKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.DeadLetterEvent =
  unhinged.cdc.DeadLetterEventKt.Dsl._create(unhinged.cdc.CdcService.DeadLetterEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.DeadLetterEvent`
 */
public object DeadLetterEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcService.DeadLetterEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcService.DeadLetterEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcService.DeadLetterEvent = _builder.build()

    /**
     * `.unhinged.cdc.UniversalEvent original_event = 1;`
     */
    public var originalEvent: unhinged.cdc.CdcEvents.UniversalEvent
      @JvmName("getOriginalEvent")
      get() = _builder.getOriginalEvent()
      @JvmName("setOriginalEvent")
      set(value) {
        _builder.setOriginalEvent(value)
      }
    /**
     * `.unhinged.cdc.UniversalEvent original_event = 1;`
     */
    public fun clearOriginalEvent() {
      _builder.clearOriginalEvent()
    }
    /**
     * `.unhinged.cdc.UniversalEvent original_event = 1;`
     * @return Whether the originalEvent field is set.
     */
    public fun hasOriginalEvent(): kotlin.Boolean {
      return _builder.hasOriginalEvent()
    }

    /**
     * `string failure_reason = 2;`
     */
    public var failureReason: kotlin.String
      @JvmName("getFailureReason")
      get() = _builder.getFailureReason()
      @JvmName("setFailureReason")
      set(value) {
        _builder.setFailureReason(value)
      }
    /**
     * `string failure_reason = 2;`
     */
    public fun clearFailureReason() {
      _builder.clearFailureReason()
    }

    /**
     * `int32 retry_count = 3;`
     */
    public var retryCount: kotlin.Int
      @JvmName("getRetryCount")
      get() = _builder.getRetryCount()
      @JvmName("setRetryCount")
      set(value) {
        _builder.setRetryCount(value)
      }
    /**
     * `int32 retry_count = 3;`
     */
    public fun clearRetryCount() {
      _builder.clearRetryCount()
    }

    /**
     * `.google.protobuf.Timestamp failed_at = 4;`
     */
    public var failedAt: com.google.protobuf.Timestamp
      @JvmName("getFailedAt")
      get() = _builder.getFailedAt()
      @JvmName("setFailedAt")
      set(value) {
        _builder.setFailedAt(value)
      }
    /**
     * `.google.protobuf.Timestamp failed_at = 4;`
     */
    public fun clearFailedAt() {
      _builder.clearFailedAt()
    }
    /**
     * `.google.protobuf.Timestamp failed_at = 4;`
     * @return Whether the failedAt field is set.
     */
    public fun hasFailedAt(): kotlin.Boolean {
      return _builder.hasFailedAt()
    }

    /**
     * `.google.protobuf.Timestamp last_retry_at = 5;`
     */
    public var lastRetryAt: com.google.protobuf.Timestamp
      @JvmName("getLastRetryAt")
      get() = _builder.getLastRetryAt()
      @JvmName("setLastRetryAt")
      set(value) {
        _builder.setLastRetryAt(value)
      }
    /**
     * `.google.protobuf.Timestamp last_retry_at = 5;`
     */
    public fun clearLastRetryAt() {
      _builder.clearLastRetryAt()
    }
    /**
     * `.google.protobuf.Timestamp last_retry_at = 5;`
     * @return Whether the lastRetryAt field is set.
     */
    public fun hasLastRetryAt(): kotlin.Boolean {
      return _builder.hasLastRetryAt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcService.DeadLetterEvent.copy(block: `unhinged.cdc`.DeadLetterEventKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.DeadLetterEvent =
  `unhinged.cdc`.DeadLetterEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.cdc.CdcService.DeadLetterEventOrBuilder.originalEventOrNull: unhinged.cdc.CdcEvents.UniversalEvent?
  get() = if (hasOriginalEvent()) getOriginalEvent() else null

public val unhinged.cdc.CdcService.DeadLetterEventOrBuilder.failedAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasFailedAt()) getFailedAt() else null

public val unhinged.cdc.CdcService.DeadLetterEventOrBuilder.lastRetryAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasLastRetryAt()) getLastRetryAt() else null

