// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializedeleteSubscriptionRequest")
public inline fun deleteSubscriptionRequest(block: unhinged.cdc.DeleteSubscriptionRequestKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.DeleteSubscriptionRequest =
  unhinged.cdc.DeleteSubscriptionRequestKt.Dsl._create(unhinged.cdc.CdcService.DeleteSubscriptionRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.DeleteSubscriptionRequest`
 */
public object DeleteSubscriptionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcService.DeleteSubscriptionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcService.DeleteSubscriptionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcService.DeleteSubscriptionRequest = _builder.build()

    /**
     * `string subscriber_id = 1;`
     */
    public var subscriberId: kotlin.String
      @JvmName("getSubscriberId")
      get() = _builder.getSubscriberId()
      @JvmName("setSubscriberId")
      set(value) {
        _builder.setSubscriberId(value)
      }
    /**
     * `string subscriber_id = 1;`
     */
    public fun clearSubscriberId() {
      _builder.clearSubscriberId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcService.DeleteSubscriptionRequest.copy(block: `unhinged.cdc`.DeleteSubscriptionRequestKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.DeleteSubscriptionRequest =
  `unhinged.cdc`.DeleteSubscriptionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

