// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializedocumentTagged")
public inline fun documentTagged(block: unhinged.cdc.DocumentTaggedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.DocumentTagged =
  unhinged.cdc.DocumentTaggedKt.Dsl._create(unhinged.cdc.CdcEvents.DocumentTagged.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.DocumentTagged`
 */
public object DocumentTaggedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.DocumentTagged.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.DocumentTagged.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.DocumentTagged = _builder.build()

    /**
     * `string tag = 1;`
     */
    public var tag: kotlin.String
      @JvmName("getTag")
      get() = _builder.getTag()
      @JvmName("setTag")
      set(value) {
        _builder.setTag(value)
      }
    /**
     * `string tag = 1;`
     */
    public fun clearTag() {
      _builder.clearTag()
    }

    /**
     * `string tagged_by = 2;`
     */
    public var taggedBy: kotlin.String
      @JvmName("getTaggedBy")
      get() = _builder.getTaggedBy()
      @JvmName("setTaggedBy")
      set(value) {
        _builder.setTaggedBy(value)
      }
    /**
     * `string tagged_by = 2;`
     */
    public fun clearTaggedBy() {
      _builder.clearTaggedBy()
    }

    /**
     * `string tagged_by_type = 3;`
     */
    public var taggedByType: kotlin.String
      @JvmName("getTaggedByType")
      get() = _builder.getTaggedByType()
      @JvmName("setTaggedByType")
      set(value) {
        _builder.setTaggedByType(value)
      }
    /**
     * `string tagged_by_type = 3;`
     */
    public fun clearTaggedByType() {
      _builder.clearTaggedByType()
    }

    /**
     * ```
     * "add", "remove", "update"
     * ```
     *
     * `string tag_operation = 4;`
     */
    public var tagOperation: kotlin.String
      @JvmName("getTagOperation")
      get() = _builder.getTagOperation()
      @JvmName("setTagOperation")
      set(value) {
        _builder.setTagOperation(value)
      }
    /**
     * ```
     * "add", "remove", "update"
     * ```
     *
     * `string tag_operation = 4;`
     */
    public fun clearTagOperation() {
      _builder.clearTagOperation()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.DocumentTagged.copy(block: `unhinged.cdc`.DocumentTaggedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.DocumentTagged =
  `unhinged.cdc`.DocumentTaggedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

