// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializedocumentUpdated")
public inline fun documentUpdated(block: unhinged.cdc.DocumentUpdatedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.DocumentUpdated =
  unhinged.cdc.DocumentUpdatedKt.Dsl._create(unhinged.cdc.CdcEvents.DocumentUpdated.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.DocumentUpdated`
 */
public object DocumentUpdatedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.DocumentUpdated.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.DocumentUpdated.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.DocumentUpdated = _builder.build()

    /**
     * `int32 previous_version = 1;`
     */
    public var previousVersion: kotlin.Int
      @JvmName("getPreviousVersion")
      get() = _builder.getPreviousVersion()
      @JvmName("setPreviousVersion")
      set(value) {
        _builder.setPreviousVersion(value)
      }
    /**
     * `int32 previous_version = 1;`
     */
    public fun clearPreviousVersion() {
      _builder.clearPreviousVersion()
    }

    /**
     * `string updated_by = 2;`
     */
    public var updatedBy: kotlin.String
      @JvmName("getUpdatedBy")
      get() = _builder.getUpdatedBy()
      @JvmName("setUpdatedBy")
      set(value) {
        _builder.setUpdatedBy(value)
      }
    /**
     * `string updated_by = 2;`
     */
    public fun clearUpdatedBy() {
      _builder.clearUpdatedBy()
    }

    /**
     * `string updated_by_type = 3;`
     */
    public var updatedByType: kotlin.String
      @JvmName("getUpdatedByType")
      get() = _builder.getUpdatedByType()
      @JvmName("setUpdatedByType")
      set(value) {
        _builder.setUpdatedByType(value)
      }
    /**
     * `string updated_by_type = 3;`
     */
    public fun clearUpdatedByType() {
      _builder.clearUpdatedByType()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ChangedFieldsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string changed_fields = 4;`
     * @return A list containing the changedFields.
     */
    public val changedFields: com.google.protobuf.kotlin.DslList<kotlin.String, ChangedFieldsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getChangedFieldsList()
      )
    /**
     * `repeated string changed_fields = 4;`
     * @param value The changedFields to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addChangedFields")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ChangedFieldsProxy>.add(value: kotlin.String) {
      _builder.addChangedFields(value)
    }
    /**
     * `repeated string changed_fields = 4;`
     * @param value The changedFields to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignChangedFields")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ChangedFieldsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string changed_fields = 4;`
     * @param values The changedFields to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllChangedFields")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ChangedFieldsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllChangedFields(values)
    }
    /**
     * `repeated string changed_fields = 4;`
     * @param values The changedFields to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllChangedFields")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ChangedFieldsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string changed_fields = 4;`
     * @param index The index to set the value at.
     * @param value The changedFields to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setChangedFields")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ChangedFieldsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setChangedFields(index, value)
    }/**
     * `repeated string changed_fields = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearChangedFields")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ChangedFieldsProxy>.clear() {
      _builder.clearChangedFields()
    }
    /**
     * `.google.protobuf.Struct changes = 5;`
     */
    public var changes: com.google.protobuf.Struct
      @JvmName("getChanges")
      get() = _builder.getChanges()
      @JvmName("setChanges")
      set(value) {
        _builder.setChanges(value)
      }
    /**
     * `.google.protobuf.Struct changes = 5;`
     */
    public fun clearChanges() {
      _builder.clearChanges()
    }
    /**
     * `.google.protobuf.Struct changes = 5;`
     * @return Whether the changes field is set.
     */
    public fun hasChanges(): kotlin.Boolean {
      return _builder.hasChanges()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.DocumentUpdated.copy(block: `unhinged.cdc`.DocumentUpdatedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.DocumentUpdated =
  `unhinged.cdc`.DocumentUpdatedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.cdc.CdcEvents.DocumentUpdatedOrBuilder.changesOrNull: com.google.protobuf.Struct?
  get() = if (hasChanges()) getChanges() else null

