// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializedocumentCreated")
public inline fun documentCreated(block: unhinged.cdc.DocumentCreatedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.DocumentCreated =
  unhinged.cdc.DocumentCreatedKt.Dsl._create(unhinged.cdc.CdcEvents.DocumentCreated.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.DocumentCreated`
 */
public object DocumentCreatedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.DocumentCreated.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.DocumentCreated.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.DocumentCreated = _builder.build()

    /**
     * `string document_name = 1;`
     */
    public var documentName: kotlin.String
      @JvmName("getDocumentName")
      get() = _builder.getDocumentName()
      @JvmName("setDocumentName")
      set(value) {
        _builder.setDocumentName(value)
      }
    /**
     * `string document_name = 1;`
     */
    public fun clearDocumentName() {
      _builder.clearDocumentName()
    }

    /**
     * `string created_by = 2;`
     */
    public var createdBy: kotlin.String
      @JvmName("getCreatedBy")
      get() = _builder.getCreatedBy()
      @JvmName("setCreatedBy")
      set(value) {
        _builder.setCreatedBy(value)
      }
    /**
     * `string created_by = 2;`
     */
    public fun clearCreatedBy() {
      _builder.clearCreatedBy()
    }

    /**
     * `string created_by_type = 3;`
     */
    public var createdByType: kotlin.String
      @JvmName("getCreatedByType")
      get() = _builder.getCreatedByType()
      @JvmName("setCreatedByType")
      set(value) {
        _builder.setCreatedByType(value)
      }
    /**
     * `string created_by_type = 3;`
     */
    public fun clearCreatedByType() {
      _builder.clearCreatedByType()
    }

    /**
     * `.google.protobuf.Struct document_metadata = 4;`
     */
    public var documentMetadata: com.google.protobuf.Struct
      @JvmName("getDocumentMetadata")
      get() = _builder.getDocumentMetadata()
      @JvmName("setDocumentMetadata")
      set(value) {
        _builder.setDocumentMetadata(value)
      }
    /**
     * `.google.protobuf.Struct document_metadata = 4;`
     */
    public fun clearDocumentMetadata() {
      _builder.clearDocumentMetadata()
    }
    /**
     * `.google.protobuf.Struct document_metadata = 4;`
     * @return Whether the documentMetadata field is set.
     */
    public fun hasDocumentMetadata(): kotlin.Boolean {
      return _builder.hasDocumentMetadata()
    }

    /**
     * `int64 document_size_bytes = 5;`
     */
    public var documentSizeBytes: kotlin.Long
      @JvmName("getDocumentSizeBytes")
      get() = _builder.getDocumentSizeBytes()
      @JvmName("setDocumentSizeBytes")
      set(value) {
        _builder.setDocumentSizeBytes(value)
      }
    /**
     * `int64 document_size_bytes = 5;`
     */
    public fun clearDocumentSizeBytes() {
      _builder.clearDocumentSizeBytes()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.DocumentCreated.copy(block: `unhinged.cdc`.DocumentCreatedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.DocumentCreated =
  `unhinged.cdc`.DocumentCreatedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.cdc.CdcEvents.DocumentCreatedOrBuilder.documentMetadataOrNull: com.google.protobuf.Struct?
  get() = if (hasDocumentMetadata()) getDocumentMetadata() else null

