// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializegetEventStatsRequest")
public inline fun getEventStatsRequest(block: unhinged.cdc.GetEventStatsRequestKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.GetEventStatsRequest =
  unhinged.cdc.GetEventStatsRequestKt.Dsl._create(unhinged.cdc.CdcService.GetEventStatsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.GetEventStatsRequest`
 */
public object GetEventStatsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcService.GetEventStatsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcService.GetEventStatsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcService.GetEventStatsRequest = _builder.build()

    /**
     * `.google.protobuf.Timestamp start_time = 1;`
     */
    public var startTime: com.google.protobuf.Timestamp
      @JvmName("getStartTime")
      get() = _builder.getStartTime()
      @JvmName("setStartTime")
      set(value) {
        _builder.setStartTime(value)
      }
    /**
     * `.google.protobuf.Timestamp start_time = 1;`
     */
    public fun clearStartTime() {
      _builder.clearStartTime()
    }
    /**
     * `.google.protobuf.Timestamp start_time = 1;`
     * @return Whether the startTime field is set.
     */
    public fun hasStartTime(): kotlin.Boolean {
      return _builder.hasStartTime()
    }

    /**
     * `.google.protobuf.Timestamp end_time = 2;`
     */
    public var endTime: com.google.protobuf.Timestamp
      @JvmName("getEndTime")
      get() = _builder.getEndTime()
      @JvmName("setEndTime")
      set(value) {
        _builder.setEndTime(value)
      }
    /**
     * `.google.protobuf.Timestamp end_time = 2;`
     */
    public fun clearEndTime() {
      _builder.clearEndTime()
    }
    /**
     * `.google.protobuf.Timestamp end_time = 2;`
     * @return Whether the endTime field is set.
     */
    public fun hasEndTime(): kotlin.Boolean {
      return _builder.hasEndTime()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EventTypesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string event_types = 3;`
     * @return A list containing the eventTypes.
     */
    public val eventTypes: com.google.protobuf.kotlin.DslList<kotlin.String, EventTypesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEventTypesList()
      )
    /**
     * `repeated string event_types = 3;`
     * @param value The eventTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEventTypes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, EventTypesProxy>.add(value: kotlin.String) {
      _builder.addEventTypes(value)
    }
    /**
     * `repeated string event_types = 3;`
     * @param value The eventTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEventTypes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EventTypesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string event_types = 3;`
     * @param values The eventTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEventTypes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, EventTypesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllEventTypes(values)
    }
    /**
     * `repeated string event_types = 3;`
     * @param values The eventTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEventTypes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EventTypesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string event_types = 3;`
     * @param index The index to set the value at.
     * @param value The eventTypes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEventTypes")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EventTypesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setEventTypes(index, value)
    }/**
     * `repeated string event_types = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEventTypes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, EventTypesProxy>.clear() {
      _builder.clearEventTypes()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SourceServicesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string source_services = 4;`
     * @return A list containing the sourceServices.
     */
    public val sourceServices: com.google.protobuf.kotlin.DslList<kotlin.String, SourceServicesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSourceServicesList()
      )
    /**
     * `repeated string source_services = 4;`
     * @param value The sourceServices to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSourceServices")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, SourceServicesProxy>.add(value: kotlin.String) {
      _builder.addSourceServices(value)
    }
    /**
     * `repeated string source_services = 4;`
     * @param value The sourceServices to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSourceServices")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SourceServicesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string source_services = 4;`
     * @param values The sourceServices to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSourceServices")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, SourceServicesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllSourceServices(values)
    }
    /**
     * `repeated string source_services = 4;`
     * @param values The sourceServices to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSourceServices")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SourceServicesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string source_services = 4;`
     * @param index The index to set the value at.
     * @param value The sourceServices to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSourceServices")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SourceServicesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setSourceServices(index, value)
    }/**
     * `repeated string source_services = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSourceServices")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, SourceServicesProxy>.clear() {
      _builder.clearSourceServices()
    }
    /**
     * ```
     * "1m", "5m", "1h", "1d"
     * ```
     *
     * `string aggregation_interval = 5;`
     */
    public var aggregationInterval: kotlin.String
      @JvmName("getAggregationInterval")
      get() = _builder.getAggregationInterval()
      @JvmName("setAggregationInterval")
      set(value) {
        _builder.setAggregationInterval(value)
      }
    /**
     * ```
     * "1m", "5m", "1h", "1d"
     * ```
     *
     * `string aggregation_interval = 5;`
     */
    public fun clearAggregationInterval() {
      _builder.clearAggregationInterval()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcService.GetEventStatsRequest.copy(block: `unhinged.cdc`.GetEventStatsRequestKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.GetEventStatsRequest =
  `unhinged.cdc`.GetEventStatsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.cdc.CdcService.GetEventStatsRequestOrBuilder.startTimeOrNull: com.google.protobuf.Timestamp?
  get() = if (hasStartTime()) getStartTime() else null

public val unhinged.cdc.CdcService.GetEventStatsRequestOrBuilder.endTimeOrNull: com.google.protobuf.Timestamp?
  get() = if (hasEndTime()) getEndTime() else null

