// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializegetEventStatsResponse")
public inline fun getEventStatsResponse(block: unhinged.cdc.GetEventStatsResponseKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.GetEventStatsResponse =
  unhinged.cdc.GetEventStatsResponseKt.Dsl._create(unhinged.cdc.CdcService.GetEventStatsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.GetEventStatsResponse`
 */
public object GetEventStatsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcService.GetEventStatsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcService.GetEventStatsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcService.GetEventStatsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class StatsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .unhinged.cdc.EventStats stats = 1;`
     */
     public val stats: com.google.protobuf.kotlin.DslList<unhinged.cdc.CdcService.EventStats, StatsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getStatsList()
      )
    /**
     * `repeated .unhinged.cdc.EventStats stats = 1;`
     * @param value The stats to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addStats")
    public fun com.google.protobuf.kotlin.DslList<unhinged.cdc.CdcService.EventStats, StatsProxy>.add(value: unhinged.cdc.CdcService.EventStats) {
      _builder.addStats(value)
    }
    /**
     * `repeated .unhinged.cdc.EventStats stats = 1;`
     * @param value The stats to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignStats")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.cdc.CdcService.EventStats, StatsProxy>.plusAssign(value: unhinged.cdc.CdcService.EventStats) {
      add(value)
    }
    /**
     * `repeated .unhinged.cdc.EventStats stats = 1;`
     * @param values The stats to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllStats")
    public fun com.google.protobuf.kotlin.DslList<unhinged.cdc.CdcService.EventStats, StatsProxy>.addAll(values: kotlin.collections.Iterable<unhinged.cdc.CdcService.EventStats>) {
      _builder.addAllStats(values)
    }
    /**
     * `repeated .unhinged.cdc.EventStats stats = 1;`
     * @param values The stats to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllStats")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.cdc.CdcService.EventStats, StatsProxy>.plusAssign(values: kotlin.collections.Iterable<unhinged.cdc.CdcService.EventStats>) {
      addAll(values)
    }
    /**
     * `repeated .unhinged.cdc.EventStats stats = 1;`
     * @param index The index to set the value at.
     * @param value The stats to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setStats")
    public operator fun com.google.protobuf.kotlin.DslList<unhinged.cdc.CdcService.EventStats, StatsProxy>.set(index: kotlin.Int, value: unhinged.cdc.CdcService.EventStats) {
      _builder.setStats(index, value)
    }
    /**
     * `repeated .unhinged.cdc.EventStats stats = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearStats")
    public fun com.google.protobuf.kotlin.DslList<unhinged.cdc.CdcService.EventStats, StatsProxy>.clear() {
      _builder.clearStats()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcService.GetEventStatsResponse.copy(block: `unhinged.cdc`.GetEventStatsResponseKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.GetEventStatsResponse =
  `unhinged.cdc`.GetEventStatsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

