// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializegetServiceStatusResponse")
public inline fun getServiceStatusResponse(block: unhinged.cdc.GetServiceStatusResponseKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.GetServiceStatusResponse =
  unhinged.cdc.GetServiceStatusResponseKt.Dsl._create(unhinged.cdc.CdcService.GetServiceStatusResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.GetServiceStatusResponse`
 */
public object GetServiceStatusResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcService.GetServiceStatusResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcService.GetServiceStatusResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcService.GetServiceStatusResponse = _builder.build()

    /**
     * `bool healthy = 1;`
     */
    public var healthy: kotlin.Boolean
      @JvmName("getHealthy")
      get() = _builder.getHealthy()
      @JvmName("setHealthy")
      set(value) {
        _builder.setHealthy(value)
      }
    /**
     * `bool healthy = 1;`
     */
    public fun clearHealthy() {
      _builder.clearHealthy()
    }

    /**
     * `string status = 2;`
     */
    public var status: kotlin.String
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * `string status = 2;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    /**
     * `.unhinged.cdc.ServiceMetrics metrics = 4;`
     */
    public var metrics: unhinged.cdc.CdcService.ServiceMetrics
      @JvmName("getMetrics")
      get() = _builder.getMetrics()
      @JvmName("setMetrics")
      set(value) {
        _builder.setMetrics(value)
      }
    /**
     * `.unhinged.cdc.ServiceMetrics metrics = 4;`
     */
    public fun clearMetrics() {
      _builder.clearMetrics()
    }
    /**
     * `.unhinged.cdc.ServiceMetrics metrics = 4;`
     * @return Whether the metrics field is set.
     */
    public fun hasMetrics(): kotlin.Boolean {
      return _builder.hasMetrics()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcService.GetServiceStatusResponse.copy(block: `unhinged.cdc`.GetServiceStatusResponseKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.GetServiceStatusResponse =
  `unhinged.cdc`.GetServiceStatusResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.cdc.CdcService.GetServiceStatusResponseOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

public val unhinged.cdc.CdcService.GetServiceStatusResponseOrBuilder.metricsOrNull: unhinged.cdc.CdcService.ServiceMetrics?
  get() = if (hasMetrics()) getMetrics() else null

