// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializegetServiceStatusRequest")
public inline fun getServiceStatusRequest(block: unhinged.cdc.GetServiceStatusRequestKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.GetServiceStatusRequest =
  unhinged.cdc.GetServiceStatusRequestKt.Dsl._create(unhinged.cdc.CdcService.GetServiceStatusRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.GetServiceStatusRequest`
 */
public object GetServiceStatusRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcService.GetServiceStatusRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcService.GetServiceStatusRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcService.GetServiceStatusRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcService.GetServiceStatusRequest.copy(block: `unhinged.cdc`.GetServiceStatusRequestKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.GetServiceStatusRequest =
  `unhinged.cdc`.GetServiceStatusRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

