// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializehealthCheck")
public inline fun healthCheck(block: unhinged.cdc.HealthCheckKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.HealthCheck =
  unhinged.cdc.HealthCheckKt.Dsl._create(unhinged.cdc.CdcEvents.HealthCheck.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.HealthCheck`
 */
public object HealthCheckKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.HealthCheck.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.HealthCheck.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.HealthCheck = _builder.build()

    /**
     * `bool is_healthy = 1;`
     */
    public var isHealthy: kotlin.Boolean
      @JvmName("getIsHealthy")
      get() = _builder.getIsHealthy()
      @JvmName("setIsHealthy")
      set(value) {
        _builder.setIsHealthy(value)
      }
    /**
     * `bool is_healthy = 1;`
     */
    public fun clearIsHealthy() {
      _builder.clearIsHealthy()
    }

    /**
     * `string status = 2;`
     */
    public var status: kotlin.String
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * `string status = 2;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.google.protobuf.Struct health_details = 3;`
     */
    public var healthDetails: com.google.protobuf.Struct
      @JvmName("getHealthDetails")
      get() = _builder.getHealthDetails()
      @JvmName("setHealthDetails")
      set(value) {
        _builder.setHealthDetails(value)
      }
    /**
     * `.google.protobuf.Struct health_details = 3;`
     */
    public fun clearHealthDetails() {
      _builder.clearHealthDetails()
    }
    /**
     * `.google.protobuf.Struct health_details = 3;`
     * @return Whether the healthDetails field is set.
     */
    public fun hasHealthDetails(): kotlin.Boolean {
      return _builder.hasHealthDetails()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.HealthCheck.copy(block: `unhinged.cdc`.HealthCheckKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.HealthCheck =
  `unhinged.cdc`.HealthCheckKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.cdc.CdcEvents.HealthCheckOrBuilder.healthDetailsOrNull: com.google.protobuf.Struct?
  get() = if (hasHealthDetails()) getHealthDetails() else null

