// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializelistDeadLetterEventsRequest")
public inline fun listDeadLetterEventsRequest(block: unhinged.cdc.ListDeadLetterEventsRequestKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.ListDeadLetterEventsRequest =
  unhinged.cdc.ListDeadLetterEventsRequestKt.Dsl._create(unhinged.cdc.CdcService.ListDeadLetterEventsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.ListDeadLetterEventsRequest`
 */
public object ListDeadLetterEventsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcService.ListDeadLetterEventsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcService.ListDeadLetterEventsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcService.ListDeadLetterEventsRequest = _builder.build()

    /**
     * `string subscriber_id = 1;`
     */
    public var subscriberId: kotlin.String
      @JvmName("getSubscriberId")
      get() = _builder.getSubscriberId()
      @JvmName("setSubscriberId")
      set(value) {
        _builder.setSubscriberId(value)
      }
    /**
     * `string subscriber_id = 1;`
     */
    public fun clearSubscriberId() {
      _builder.clearSubscriberId()
    }

    /**
     * `.google.protobuf.Timestamp since = 2;`
     */
    public var since: com.google.protobuf.Timestamp
      @JvmName("getSince")
      get() = _builder.getSince()
      @JvmName("setSince")
      set(value) {
        _builder.setSince(value)
      }
    /**
     * `.google.protobuf.Timestamp since = 2;`
     */
    public fun clearSince() {
      _builder.clearSince()
    }
    /**
     * `.google.protobuf.Timestamp since = 2;`
     * @return Whether the since field is set.
     */
    public fun hasSince(): kotlin.Boolean {
      return _builder.hasSince()
    }

    /**
     * `int32 page_size = 3;`
     */
    public var pageSize: kotlin.Int
      @JvmName("getPageSize")
      get() = _builder.getPageSize()
      @JvmName("setPageSize")
      set(value) {
        _builder.setPageSize(value)
      }
    /**
     * `int32 page_size = 3;`
     */
    public fun clearPageSize() {
      _builder.clearPageSize()
    }

    /**
     * `string page_token = 4;`
     */
    public var pageToken: kotlin.String
      @JvmName("getPageToken")
      get() = _builder.getPageToken()
      @JvmName("setPageToken")
      set(value) {
        _builder.setPageToken(value)
      }
    /**
     * `string page_token = 4;`
     */
    public fun clearPageToken() {
      _builder.clearPageToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcService.ListDeadLetterEventsRequest.copy(block: `unhinged.cdc`.ListDeadLetterEventsRequestKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.ListDeadLetterEventsRequest =
  `unhinged.cdc`.ListDeadLetterEventsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.cdc.CdcService.ListDeadLetterEventsRequestOrBuilder.sinceOrNull: com.google.protobuf.Timestamp?
  get() = if (hasSince()) getSince() else null

