// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializelLMError")
public inline fun lLMError(block: unhinged.cdc.LLMErrorKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.LLMError =
  unhinged.cdc.LLMErrorKt.Dsl._create(unhinged.cdc.CdcEvents.LLMError.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.LLMError`
 */
public object LLMErrorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.LLMError.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.LLMError.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.LLMError = _builder.build()

    /**
     * `string error_code = 1;`
     */
    public var errorCode: kotlin.String
      @JvmName("getErrorCode")
      get() = _builder.getErrorCode()
      @JvmName("setErrorCode")
      set(value) {
        _builder.setErrorCode(value)
      }
    /**
     * `string error_code = 1;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }

    /**
     * `string error_message = 2;`
     */
    public var errorMessage: kotlin.String
      @JvmName("getErrorMessage")
      get() = _builder.getErrorMessage()
      @JvmName("setErrorMessage")
      set(value) {
        _builder.setErrorMessage(value)
      }
    /**
     * `string error_message = 2;`
     */
    public fun clearErrorMessage() {
      _builder.clearErrorMessage()
    }

    /**
     * ```
     * "rate_limit", "context_length", "content_filter", etc.
     * ```
     *
     * `string error_type = 3;`
     */
    public var errorType: kotlin.String
      @JvmName("getErrorType")
      get() = _builder.getErrorType()
      @JvmName("setErrorType")
      set(value) {
        _builder.setErrorType(value)
      }
    /**
     * ```
     * "rate_limit", "context_length", "content_filter", etc.
     * ```
     *
     * `string error_type = 3;`
     */
    public fun clearErrorType() {
      _builder.clearErrorType()
    }

    /**
     * `bool is_retryable = 4;`
     */
    public var isRetryable: kotlin.Boolean
      @JvmName("getIsRetryable")
      get() = _builder.getIsRetryable()
      @JvmName("setIsRetryable")
      set(value) {
        _builder.setIsRetryable(value)
      }
    /**
     * `bool is_retryable = 4;`
     */
    public fun clearIsRetryable() {
      _builder.clearIsRetryable()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.LLMError.copy(block: `unhinged.cdc`.LLMErrorKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.LLMError =
  `unhinged.cdc`.LLMErrorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

