// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializemessageUpdated")
public inline fun messageUpdated(block: unhinged.cdc.MessageUpdatedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.MessageUpdated =
  unhinged.cdc.MessageUpdatedKt.Dsl._create(unhinged.cdc.CdcEvents.MessageUpdated.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.MessageUpdated`
 */
public object MessageUpdatedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.MessageUpdated.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.MessageUpdated.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.MessageUpdated = _builder.build()

    /**
     * `string content = 1;`
     */
    public var content: kotlin.String
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * `string content = 1;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }

    /**
     * `string updated_by = 2;`
     */
    public var updatedBy: kotlin.String
      @JvmName("getUpdatedBy")
      get() = _builder.getUpdatedBy()
      @JvmName("setUpdatedBy")
      set(value) {
        _builder.setUpdatedBy(value)
      }
    /**
     * `string updated_by = 2;`
     */
    public fun clearUpdatedBy() {
      _builder.clearUpdatedBy()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.MessageUpdated.copy(block: `unhinged.cdc`.MessageUpdatedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.MessageUpdated =
  `unhinged.cdc`.MessageUpdatedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

