// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializemessageSent")
public inline fun messageSent(block: unhinged.cdc.MessageSentKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.MessageSent =
  unhinged.cdc.MessageSentKt.Dsl._create(unhinged.cdc.CdcEvents.MessageSent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.MessageSent`
 */
public object MessageSentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.MessageSent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.MessageSent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.MessageSent = _builder.build()

    /**
     * `string content = 1;`
     */
    public var content: kotlin.String
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * `string content = 1;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }

    /**
     * `string role = 2;`
     */
    public var role: kotlin.String
      @JvmName("getRole")
      get() = _builder.getRole()
      @JvmName("setRole")
      set(value) {
        _builder.setRole(value)
      }
    /**
     * `string role = 2;`
     */
    public fun clearRole() {
      _builder.clearRole()
    }

    /**
     * `string sent_by = 3;`
     */
    public var sentBy: kotlin.String
      @JvmName("getSentBy")
      get() = _builder.getSentBy()
      @JvmName("setSentBy")
      set(value) {
        _builder.setSentBy(value)
      }
    /**
     * `string sent_by = 3;`
     */
    public fun clearSentBy() {
      _builder.clearSentBy()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.MessageSent.copy(block: `unhinged.cdc`.MessageSentKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.MessageSent =
  `unhinged.cdc`.MessageSentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

