// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializepublishEventRequest")
public inline fun publishEventRequest(block: unhinged.cdc.PublishEventRequestKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.PublishEventRequest =
  unhinged.cdc.PublishEventRequestKt.Dsl._create(unhinged.cdc.CdcService.PublishEventRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Publish a single event
 * ```
 *
 * Protobuf type `unhinged.cdc.PublishEventRequest`
 */
public object PublishEventRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcService.PublishEventRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcService.PublishEventRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcService.PublishEventRequest = _builder.build()

    /**
     * `.unhinged.cdc.UniversalEvent event = 1;`
     */
    public var event: unhinged.cdc.CdcEvents.UniversalEvent
      @JvmName("getEvent")
      get() = _builder.getEvent()
      @JvmName("setEvent")
      set(value) {
        _builder.setEvent(value)
      }
    /**
     * `.unhinged.cdc.UniversalEvent event = 1;`
     */
    public fun clearEvent() {
      _builder.clearEvent()
    }
    /**
     * `.unhinged.cdc.UniversalEvent event = 1;`
     * @return Whether the event field is set.
     */
    public fun hasEvent(): kotlin.Boolean {
      return _builder.hasEvent()
    }

    /**
     * ```
     * Publishing options
     * ```
     *
     * `bool ensure_delivery = 2;`
     */
    public var ensureDelivery: kotlin.Boolean
      @JvmName("getEnsureDelivery")
      get() = _builder.getEnsureDelivery()
      @JvmName("setEnsureDelivery")
      set(value) {
        _builder.setEnsureDelivery(value)
      }
    /**
     * ```
     * Publishing options
     * ```
     *
     * `bool ensure_delivery = 2;`
     */
    public fun clearEnsureDelivery() {
      _builder.clearEnsureDelivery()
    }

    /**
     * `int32 retry_attempts = 3;`
     */
    public var retryAttempts: kotlin.Int
      @JvmName("getRetryAttempts")
      get() = _builder.getRetryAttempts()
      @JvmName("setRetryAttempts")
      set(value) {
        _builder.setRetryAttempts(value)
      }
    /**
     * `int32 retry_attempts = 3;`
     */
    public fun clearRetryAttempts() {
      _builder.clearRetryAttempts()
    }

    /**
     * `.google.protobuf.Timestamp delivery_deadline = 4;`
     */
    public var deliveryDeadline: com.google.protobuf.Timestamp
      @JvmName("getDeliveryDeadline")
      get() = _builder.getDeliveryDeadline()
      @JvmName("setDeliveryDeadline")
      set(value) {
        _builder.setDeliveryDeadline(value)
      }
    /**
     * `.google.protobuf.Timestamp delivery_deadline = 4;`
     */
    public fun clearDeliveryDeadline() {
      _builder.clearDeliveryDeadline()
    }
    /**
     * `.google.protobuf.Timestamp delivery_deadline = 4;`
     * @return Whether the deliveryDeadline field is set.
     */
    public fun hasDeliveryDeadline(): kotlin.Boolean {
      return _builder.hasDeliveryDeadline()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TargetSubscribersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Routing options
     * ```
     *
     * `repeated string target_subscribers = 5;`
     * @return A list containing the targetSubscribers.
     */
    public val targetSubscribers: com.google.protobuf.kotlin.DslList<kotlin.String, TargetSubscribersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTargetSubscribersList()
      )
    /**
     * ```
     * Routing options
     * ```
     *
     * `repeated string target_subscribers = 5;`
     * @param value The targetSubscribers to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTargetSubscribers")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TargetSubscribersProxy>.add(value: kotlin.String) {
      _builder.addTargetSubscribers(value)
    }
    /**
     * ```
     * Routing options
     * ```
     *
     * `repeated string target_subscribers = 5;`
     * @param value The targetSubscribers to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTargetSubscribers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TargetSubscribersProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * Routing options
     * ```
     *
     * `repeated string target_subscribers = 5;`
     * @param values The targetSubscribers to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTargetSubscribers")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TargetSubscribersProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllTargetSubscribers(values)
    }
    /**
     * ```
     * Routing options
     * ```
     *
     * `repeated string target_subscribers = 5;`
     * @param values The targetSubscribers to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTargetSubscribers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TargetSubscribersProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * Routing options
     * ```
     *
     * `repeated string target_subscribers = 5;`
     * @param index The index to set the value at.
     * @param value The targetSubscribers to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTargetSubscribers")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TargetSubscribersProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setTargetSubscribers(index, value)
    }/**
     * ```
     * Routing options
     * ```
     *
     * `repeated string target_subscribers = 5;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTargetSubscribers")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TargetSubscribersProxy>.clear() {
      _builder.clearTargetSubscribers()
    }
    /**
     * ```
     * "broadcast", "round_robin", "sticky"
     * ```
     *
     * `string routing_strategy = 6;`
     */
    public var routingStrategy: kotlin.String
      @JvmName("getRoutingStrategy")
      get() = _builder.getRoutingStrategy()
      @JvmName("setRoutingStrategy")
      set(value) {
        _builder.setRoutingStrategy(value)
      }
    /**
     * ```
     * "broadcast", "round_robin", "sticky"
     * ```
     *
     * `string routing_strategy = 6;`
     */
    public fun clearRoutingStrategy() {
      _builder.clearRoutingStrategy()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcService.PublishEventRequest.copy(block: `unhinged.cdc`.PublishEventRequestKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.PublishEventRequest =
  `unhinged.cdc`.PublishEventRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.cdc.CdcService.PublishEventRequestOrBuilder.eventOrNull: unhinged.cdc.CdcEvents.UniversalEvent?
  get() = if (hasEvent()) getEvent() else null

public val unhinged.cdc.CdcService.PublishEventRequestOrBuilder.deliveryDeadlineOrNull: com.google.protobuf.Timestamp?
  get() = if (hasDeliveryDeadline()) getDeliveryDeadline() else null

