// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializereprocessDeadLetterEventsResponse")
public inline fun reprocessDeadLetterEventsResponse(block: unhinged.cdc.ReprocessDeadLetterEventsResponseKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.ReprocessDeadLetterEventsResponse =
  unhinged.cdc.ReprocessDeadLetterEventsResponseKt.Dsl._create(unhinged.cdc.CdcService.ReprocessDeadLetterEventsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.ReprocessDeadLetterEventsResponse`
 */
public object ReprocessDeadLetterEventsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcService.ReprocessDeadLetterEventsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcService.ReprocessDeadLetterEventsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcService.ReprocessDeadLetterEventsResponse = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * `int32 reprocessed_count = 3;`
     */
    public var reprocessedCount: kotlin.Int
      @JvmName("getReprocessedCount")
      get() = _builder.getReprocessedCount()
      @JvmName("setReprocessedCount")
      set(value) {
        _builder.setReprocessedCount(value)
      }
    /**
     * `int32 reprocessed_count = 3;`
     */
    public fun clearReprocessedCount() {
      _builder.clearReprocessedCount()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcService.ReprocessDeadLetterEventsResponse.copy(block: `unhinged.cdc`.ReprocessDeadLetterEventsResponseKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.ReprocessDeadLetterEventsResponse =
  `unhinged.cdc`.ReprocessDeadLetterEventsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

