// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializeserviceStopped")
public inline fun serviceStopped(block: unhinged.cdc.ServiceStoppedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.ServiceStopped =
  unhinged.cdc.ServiceStoppedKt.Dsl._create(unhinged.cdc.CdcEvents.ServiceStopped.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.ServiceStopped`
 */
public object ServiceStoppedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.ServiceStopped.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.ServiceStopped.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.ServiceStopped = _builder.build()

    /**
     * `string service_name = 1;`
     */
    public var serviceName: kotlin.String
      @JvmName("getServiceName")
      get() = _builder.getServiceName()
      @JvmName("setServiceName")
      set(value) {
        _builder.setServiceName(value)
      }
    /**
     * `string service_name = 1;`
     */
    public fun clearServiceName() {
      _builder.clearServiceName()
    }

    /**
     * `string stop_reason = 2;`
     */
    public var stopReason: kotlin.String
      @JvmName("getStopReason")
      get() = _builder.getStopReason()
      @JvmName("setStopReason")
      set(value) {
        _builder.setStopReason(value)
      }
    /**
     * `string stop_reason = 2;`
     */
    public fun clearStopReason() {
      _builder.clearStopReason()
    }

    /**
     * `float uptime_ms = 3;`
     */
    public var uptimeMs: kotlin.Float
      @JvmName("getUptimeMs")
      get() = _builder.getUptimeMs()
      @JvmName("setUptimeMs")
      set(value) {
        _builder.setUptimeMs(value)
      }
    /**
     * `float uptime_ms = 3;`
     */
    public fun clearUptimeMs() {
      _builder.clearUptimeMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.ServiceStopped.copy(block: `unhinged.cdc`.ServiceStoppedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.ServiceStopped =
  `unhinged.cdc`.ServiceStoppedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

