// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializeserviceMetrics")
public inline fun serviceMetrics(block: unhinged.cdc.ServiceMetricsKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.ServiceMetrics =
  unhinged.cdc.ServiceMetricsKt.Dsl._create(unhinged.cdc.CdcService.ServiceMetrics.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.ServiceMetrics`
 */
public object ServiceMetricsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcService.ServiceMetrics.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcService.ServiceMetrics.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcService.ServiceMetrics = _builder.build()

    /**
     * `int64 total_events_published = 1;`
     */
    public var totalEventsPublished: kotlin.Long
      @JvmName("getTotalEventsPublished")
      get() = _builder.getTotalEventsPublished()
      @JvmName("setTotalEventsPublished")
      set(value) {
        _builder.setTotalEventsPublished(value)
      }
    /**
     * `int64 total_events_published = 1;`
     */
    public fun clearTotalEventsPublished() {
      _builder.clearTotalEventsPublished()
    }

    /**
     * `int64 total_events_delivered = 2;`
     */
    public var totalEventsDelivered: kotlin.Long
      @JvmName("getTotalEventsDelivered")
      get() = _builder.getTotalEventsDelivered()
      @JvmName("setTotalEventsDelivered")
      set(value) {
        _builder.setTotalEventsDelivered(value)
      }
    /**
     * `int64 total_events_delivered = 2;`
     */
    public fun clearTotalEventsDelivered() {
      _builder.clearTotalEventsDelivered()
    }

    /**
     * `int64 active_subscriptions = 3;`
     */
    public var activeSubscriptions: kotlin.Long
      @JvmName("getActiveSubscriptions")
      get() = _builder.getActiveSubscriptions()
      @JvmName("setActiveSubscriptions")
      set(value) {
        _builder.setActiveSubscriptions(value)
      }
    /**
     * `int64 active_subscriptions = 3;`
     */
    public fun clearActiveSubscriptions() {
      _builder.clearActiveSubscriptions()
    }

    /**
     * `int64 events_in_dlq = 4;`
     */
    public var eventsInDlq: kotlin.Long
      @JvmName("getEventsInDlq")
      get() = _builder.getEventsInDlq()
      @JvmName("setEventsInDlq")
      set(value) {
        _builder.setEventsInDlq(value)
      }
    /**
     * `int64 events_in_dlq = 4;`
     */
    public fun clearEventsInDlq() {
      _builder.clearEventsInDlq()
    }

    /**
     * `double avg_publish_latency_ms = 5;`
     */
    public var avgPublishLatencyMs: kotlin.Double
      @JvmName("getAvgPublishLatencyMs")
      get() = _builder.getAvgPublishLatencyMs()
      @JvmName("setAvgPublishLatencyMs")
      set(value) {
        _builder.setAvgPublishLatencyMs(value)
      }
    /**
     * `double avg_publish_latency_ms = 5;`
     */
    public fun clearAvgPublishLatencyMs() {
      _builder.clearAvgPublishLatencyMs()
    }

    /**
     * `double avg_delivery_latency_ms = 6;`
     */
    public var avgDeliveryLatencyMs: kotlin.Double
      @JvmName("getAvgDeliveryLatencyMs")
      get() = _builder.getAvgDeliveryLatencyMs()
      @JvmName("setAvgDeliveryLatencyMs")
      set(value) {
        _builder.setAvgDeliveryLatencyMs(value)
      }
    /**
     * `double avg_delivery_latency_ms = 6;`
     */
    public fun clearAvgDeliveryLatencyMs() {
      _builder.clearAvgDeliveryLatencyMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcService.ServiceMetrics.copy(block: `unhinged.cdc`.ServiceMetricsKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.ServiceMetrics =
  `unhinged.cdc`.ServiceMetricsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

