// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializesessionStarted")
public inline fun sessionStarted(block: unhinged.cdc.SessionStartedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.SessionStarted =
  unhinged.cdc.SessionStartedKt.Dsl._create(unhinged.cdc.CdcEvents.SessionStarted.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.SessionStarted`
 */
public object SessionStartedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.SessionStarted.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.SessionStarted.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.SessionStarted = _builder.build()

    /**
     * `string user_agent = 1;`
     */
    public var userAgent: kotlin.String
      @JvmName("getUserAgent")
      get() = _builder.getUserAgent()
      @JvmName("setUserAgent")
      set(value) {
        _builder.setUserAgent(value)
      }
    /**
     * `string user_agent = 1;`
     */
    public fun clearUserAgent() {
      _builder.clearUserAgent()
    }

    /**
     * `string ip_address = 2;`
     */
    public var ipAddress: kotlin.String
      @JvmName("getIpAddress")
      get() = _builder.getIpAddress()
      @JvmName("setIpAddress")
      set(value) {
        _builder.setIpAddress(value)
      }
    /**
     * `string ip_address = 2;`
     */
    public fun clearIpAddress() {
      _builder.clearIpAddress()
    }

    /**
     * `.google.protobuf.Struct session_metadata = 3;`
     */
    public var sessionMetadata: com.google.protobuf.Struct
      @JvmName("getSessionMetadata")
      get() = _builder.getSessionMetadata()
      @JvmName("setSessionMetadata")
      set(value) {
        _builder.setSessionMetadata(value)
      }
    /**
     * `.google.protobuf.Struct session_metadata = 3;`
     */
    public fun clearSessionMetadata() {
      _builder.clearSessionMetadata()
    }
    /**
     * `.google.protobuf.Struct session_metadata = 3;`
     * @return Whether the sessionMetadata field is set.
     */
    public fun hasSessionMetadata(): kotlin.Boolean {
      return _builder.hasSessionMetadata()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.SessionStarted.copy(block: `unhinged.cdc`.SessionStartedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.SessionStarted =
  `unhinged.cdc`.SessionStartedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.cdc.CdcEvents.SessionStartedOrBuilder.sessionMetadataOrNull: com.google.protobuf.Struct?
  get() = if (hasSessionMetadata()) getSessionMetadata() else null

