// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializesTTCompleted")
public inline fun sTTCompleted(block: unhinged.cdc.STTCompletedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.STTCompleted =
  unhinged.cdc.STTCompletedKt.Dsl._create(unhinged.cdc.CdcEvents.STTCompleted.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.STTCompleted`
 */
public object STTCompletedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.STTCompleted.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.STTCompleted.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.STTCompleted = _builder.build()

    /**
     * `string transcript = 1;`
     */
    public var transcript: kotlin.String
      @JvmName("getTranscript")
      get() = _builder.getTranscript()
      @JvmName("setTranscript")
      set(value) {
        _builder.setTranscript(value)
      }
    /**
     * `string transcript = 1;`
     */
    public fun clearTranscript() {
      _builder.clearTranscript()
    }

    /**
     * `float confidence = 2;`
     */
    public var confidence: kotlin.Float
      @JvmName("getConfidence")
      get() = _builder.getConfidence()
      @JvmName("setConfidence")
      set(value) {
        _builder.setConfidence(value)
      }
    /**
     * `float confidence = 2;`
     */
    public fun clearConfidence() {
      _builder.clearConfidence()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.STTCompleted.copy(block: `unhinged.cdc`.STTCompletedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.STTCompleted =
  `unhinged.cdc`.STTCompletedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

