// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializetypingStarted")
public inline fun typingStarted(block: unhinged.cdc.TypingStartedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.TypingStarted =
  unhinged.cdc.TypingStartedKt.Dsl._create(unhinged.cdc.CdcEvents.TypingStarted.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.TypingStarted`
 */
public object TypingStartedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.TypingStarted.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.TypingStarted.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.TypingStarted = _builder.build()

    /**
     * `string user_id = 1;`
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * `string user_id = 1;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.TypingStarted.copy(block: `unhinged.cdc`.TypingStartedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.TypingStarted =
  `unhinged.cdc`.TypingStartedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

