// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializeupdateSubscriptionResponse")
public inline fun updateSubscriptionResponse(block: unhinged.cdc.UpdateSubscriptionResponseKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.UpdateSubscriptionResponse =
  unhinged.cdc.UpdateSubscriptionResponseKt.Dsl._create(unhinged.cdc.CdcService.UpdateSubscriptionResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.UpdateSubscriptionResponse`
 */
public object UpdateSubscriptionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcService.UpdateSubscriptionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcService.UpdateSubscriptionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcService.UpdateSubscriptionResponse = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcService.UpdateSubscriptionResponse.copy(block: `unhinged.cdc`.UpdateSubscriptionResponseKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcService.UpdateSubscriptionResponse =
  `unhinged.cdc`.UpdateSubscriptionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

