// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializeuserCreated")
public inline fun userCreated(block: unhinged.cdc.UserCreatedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.UserCreated =
  unhinged.cdc.UserCreatedKt.Dsl._create(unhinged.cdc.CdcEvents.UserCreated.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.UserCreated`
 */
public object UserCreatedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.UserCreated.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.UserCreated.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.UserCreated = _builder.build()

    /**
     * `string email = 1;`
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * `string email = 1;`
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.UserCreated.copy(block: `unhinged.cdc`.UserCreatedKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.UserCreated =
  `unhinged.cdc`.UserCreatedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

