// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cdc_events.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.cdc;

@kotlin.jvm.JvmName("-initializeuserLoggedIn")
public inline fun userLoggedIn(block: unhinged.cdc.UserLoggedInKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.UserLoggedIn =
  unhinged.cdc.UserLoggedInKt.Dsl._create(unhinged.cdc.CdcEvents.UserLoggedIn.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.cdc.UserLoggedIn`
 */
public object UserLoggedInKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.cdc.CdcEvents.UserLoggedIn.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.cdc.CdcEvents.UserLoggedIn.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.cdc.CdcEvents.UserLoggedIn = _builder.build()

    /**
     * `string ip_address = 1;`
     */
    public var ipAddress: kotlin.String
      @JvmName("getIpAddress")
      get() = _builder.getIpAddress()
      @JvmName("setIpAddress")
      set(value) {
        _builder.setIpAddress(value)
      }
    /**
     * `string ip_address = 1;`
     */
    public fun clearIpAddress() {
      _builder.clearIpAddress()
    }

    /**
     * `string user_agent = 2;`
     */
    public var userAgent: kotlin.String
      @JvmName("getUserAgent")
      get() = _builder.getUserAgent()
      @JvmName("setUserAgent")
      set(value) {
        _builder.setUserAgent(value)
      }
    /**
     * `string user_agent = 2;`
     */
    public fun clearUserAgent() {
      _builder.clearUserAgent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.cdc.CdcEvents.UserLoggedIn.copy(block: `unhinged.cdc`.UserLoggedInKt.Dsl.() -> kotlin.Unit): unhinged.cdc.CdcEvents.UserLoggedIn =
  `unhinged.cdc`.UserLoggedInKt.Dsl._create(this.toBuilder()).apply { block() }._build()

