// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.common;

@kotlin.jvm.JvmName("-initializeattachment")
public inline fun attachment(block: unhinged.common.AttachmentKt.Dsl.() -> kotlin.Unit): unhinged.common.Attachment =
  unhinged.common.AttachmentKt.Dsl._create(unhinged.common.Attachment.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Universal file attachment
 * 
 * Used across all services for file uploads, media, documents
 * ```
 *
 * Protobuf type `unhinged.common.v1.Attachment`
 */
public object AttachmentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.common.Attachment.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.common.Attachment.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.common.Attachment = _builder.build()

    /**
     * ```
     * UUID of the attachment
     * ```
     *
     * `string attachment_id = 1;`
     */
    public var attachmentId: kotlin.String
      @JvmName("getAttachmentId")
      get() = _builder.getAttachmentId()
      @JvmName("setAttachmentId")
      set(value) {
        _builder.setAttachmentId(value)
      }
    /**
     * ```
     * UUID of the attachment
     * ```
     *
     * `string attachment_id = 1;`
     */
    public fun clearAttachmentId() {
      _builder.clearAttachmentId()
    }

    /**
     * ```
     * Classification of attachment
     * ```
     *
     * `.unhinged.common.v1.AttachmentType type = 2;`
     */
    public var type: unhinged.common.AttachmentType
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    public var typeValue: kotlin.Int
      @JvmName("getTypeValue")
      get() = _builder.getTypeValue()
      @JvmName("setTypeValue")
      set(value) {
        _builder.setTypeValue(value)
      }
    /**
     * ```
     * Classification of attachment
     * ```
     *
     * `.unhinged.common.v1.AttachmentType type = 2;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * ```
     * Storage URL (internal or external)
     * ```
     *
     * `string url = 3;`
     */
    public var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.getUrl()
      @JvmName("setUrl")
      set(value) {
        _builder.setUrl(value)
      }
    /**
     * ```
     * Storage URL (internal or external)
     * ```
     *
     * `string url = 3;`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * ```
     * Original filename
     * ```
     *
     * `string filename = 4;`
     */
    public var filename: kotlin.String
      @JvmName("getFilename")
      get() = _builder.getFilename()
      @JvmName("setFilename")
      set(value) {
        _builder.setFilename(value)
      }
    /**
     * ```
     * Original filename
     * ```
     *
     * `string filename = 4;`
     */
    public fun clearFilename() {
      _builder.clearFilename()
    }

    /**
     * ```
     * File size in bytes
     * ```
     *
     * `int64 size_bytes = 5;`
     */
    public var sizeBytes: kotlin.Long
      @JvmName("getSizeBytes")
      get() = _builder.getSizeBytes()
      @JvmName("setSizeBytes")
      set(value) {
        _builder.setSizeBytes(value)
      }
    /**
     * ```
     * File size in bytes
     * ```
     *
     * `int64 size_bytes = 5;`
     */
    public fun clearSizeBytes() {
      _builder.clearSizeBytes()
    }

    /**
     * ```
     * MIME type
     * ```
     *
     * `string mime_type = 6;`
     */
    public var mimeType: kotlin.String
      @JvmName("getMimeType")
      get() = _builder.getMimeType()
      @JvmName("setMimeType")
      set(value) {
        _builder.setMimeType(value)
      }
    /**
     * ```
     * MIME type
     * ```
     *
     * `string mime_type = 6;`
     */
    public fun clearMimeType() {
      _builder.clearMimeType()
    }

    /**
     * ```
     * Optional: thumbnail for images/videos
     * ```
     *
     * `string thumbnail_url = 7;`
     */
    public var thumbnailUrl: kotlin.String
      @JvmName("getThumbnailUrl")
      get() = _builder.getThumbnailUrl()
      @JvmName("setThumbnailUrl")
      set(value) {
        _builder.setThumbnailUrl(value)
      }
    /**
     * ```
     * Optional: thumbnail for images/videos
     * ```
     *
     * `string thumbnail_url = 7;`
     */
    public fun clearThumbnailUrl() {
      _builder.clearThumbnailUrl()
    }

    /**
     * ```
     * File-specific metadata
     * ```
     *
     * `.google.protobuf.Struct metadata = 8;`
     */
    public var metadata: com.google.protobuf.Struct
      @JvmName("getMetadata")
      get() = _builder.getMetadata()
      @JvmName("setMetadata")
      set(value) {
        _builder.setMetadata(value)
      }
    /**
     * ```
     * File-specific metadata
     * ```
     *
     * `.google.protobuf.Struct metadata = 8;`
     */
    public fun clearMetadata() {
      _builder.clearMetadata()
    }
    /**
     * ```
     * File-specific metadata
     * ```
     *
     * `.google.protobuf.Struct metadata = 8;`
     * @return Whether the metadata field is set.
     */
    public fun hasMetadata(): kotlin.Boolean {
      return _builder.hasMetadata()
    }

    /**
     * `.google.protobuf.Timestamp uploaded_at = 9;`
     */
    public var uploadedAt: com.google.protobuf.Timestamp
      @JvmName("getUploadedAt")
      get() = _builder.getUploadedAt()
      @JvmName("setUploadedAt")
      set(value) {
        _builder.setUploadedAt(value)
      }
    /**
     * `.google.protobuf.Timestamp uploaded_at = 9;`
     */
    public fun clearUploadedAt() {
      _builder.clearUploadedAt()
    }
    /**
     * `.google.protobuf.Timestamp uploaded_at = 9;`
     * @return Whether the uploadedAt field is set.
     */
    public fun hasUploadedAt(): kotlin.Boolean {
      return _builder.hasUploadedAt()
    }

    /**
     * ```
     * User who uploaded the file
     * ```
     *
     * `string uploaded_by = 10;`
     */
    public var uploadedBy: kotlin.String
      @JvmName("getUploadedBy")
      get() = _builder.getUploadedBy()
      @JvmName("setUploadedBy")
      set(value) {
        _builder.setUploadedBy(value)
      }
    /**
     * ```
     * User who uploaded the file
     * ```
     *
     * `string uploaded_by = 10;`
     */
    public fun clearUploadedBy() {
      _builder.clearUploadedBy()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.common.Attachment.copy(block: `unhinged.common`.AttachmentKt.Dsl.() -> kotlin.Unit): unhinged.common.Attachment =
  `unhinged.common`.AttachmentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.common.AttachmentOrBuilder.metadataOrNull: com.google.protobuf.Struct?
  get() = if (hasMetadata()) getMetadata() else null

public val unhinged.common.AttachmentOrBuilder.uploadedAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasUploadedAt()) getUploadedAt() else null

