// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.common;

@kotlin.jvm.JvmName("-initializecomputeUsage")
public inline fun computeUsage(block: unhinged.common.ComputeUsageKt.Dsl.() -> kotlin.Unit): unhinged.common.ComputeUsage =
  unhinged.common.ComputeUsageKt.Dsl._create(unhinged.common.ComputeUsage.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Compute resource usage
 * ```
 *
 * Protobuf type `unhinged.common.v1.ComputeUsage`
 */
public object ComputeUsageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.common.ComputeUsage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.common.ComputeUsage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.common.ComputeUsage = _builder.build()

    /**
     * ```
     * CPU time consumed
     * ```
     *
     * `.google.protobuf.Duration cpu_time = 1;`
     */
    public var cpuTime: com.google.protobuf.Duration
      @JvmName("getCpuTime")
      get() = _builder.getCpuTime()
      @JvmName("setCpuTime")
      set(value) {
        _builder.setCpuTime(value)
      }
    /**
     * ```
     * CPU time consumed
     * ```
     *
     * `.google.protobuf.Duration cpu_time = 1;`
     */
    public fun clearCpuTime() {
      _builder.clearCpuTime()
    }
    /**
     * ```
     * CPU time consumed
     * ```
     *
     * `.google.protobuf.Duration cpu_time = 1;`
     * @return Whether the cpuTime field is set.
     */
    public fun hasCpuTime(): kotlin.Boolean {
      return _builder.hasCpuTime()
    }

    /**
     * ```
     * Peak memory usage
     * ```
     *
     * `int64 memory_bytes = 2;`
     */
    public var memoryBytes: kotlin.Long
      @JvmName("getMemoryBytes")
      get() = _builder.getMemoryBytes()
      @JvmName("setMemoryBytes")
      set(value) {
        _builder.setMemoryBytes(value)
      }
    /**
     * ```
     * Peak memory usage
     * ```
     *
     * `int64 memory_bytes = 2;`
     */
    public fun clearMemoryBytes() {
      _builder.clearMemoryBytes()
    }

    /**
     * ```
     * Storage space used
     * ```
     *
     * `int64 storage_bytes = 3;`
     */
    public var storageBytes: kotlin.Long
      @JvmName("getStorageBytes")
      get() = _builder.getStorageBytes()
      @JvmName("setStorageBytes")
      set(value) {
        _builder.setStorageBytes(value)
      }
    /**
     * ```
     * Storage space used
     * ```
     *
     * `int64 storage_bytes = 3;`
     */
    public fun clearStorageBytes() {
      _builder.clearStorageBytes()
    }

    /**
     * ```
     * GPU time (if applicable)
     * ```
     *
     * `int32 gpu_seconds = 4;`
     */
    public var gpuSeconds: kotlin.Int
      @JvmName("getGpuSeconds")
      get() = _builder.getGpuSeconds()
      @JvmName("setGpuSeconds")
      set(value) {
        _builder.setGpuSeconds(value)
      }
    /**
     * ```
     * GPU time (if applicable)
     * ```
     *
     * `int32 gpu_seconds = 4;`
     */
    public fun clearGpuSeconds() {
      _builder.clearGpuSeconds()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.common.ComputeUsage.copy(block: `unhinged.common`.ComputeUsageKt.Dsl.() -> kotlin.Unit): unhinged.common.ComputeUsage =
  `unhinged.common`.ComputeUsageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.common.ComputeUsageOrBuilder.cpuTimeOrNull: com.google.protobuf.Duration?
  get() = if (hasCpuTime()) getCpuTime() else null

