// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.common;

@kotlin.jvm.JvmName("-initializeerror")
public inline fun error(block: unhinged.common.ErrorKt.Dsl.() -> kotlin.Unit): unhinged.common.Error =
  unhinged.common.ErrorKt.Dsl._create(unhinged.common.Error.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Standardized error response
 * 
 * Provides consistent error handling across all services
 * with detailed field-level validation errors.
 * ```
 *
 * Protobuf type `unhinged.common.v1.Error`
 */
public object ErrorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.common.Error.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.common.Error.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.common.Error = _builder.build()

    /**
     * ```
     * Standard error code
     * ```
     *
     * `.unhinged.common.v1.ErrorCode code = 1;`
     */
    public var code: unhinged.common.ErrorCode
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    public var codeValue: kotlin.Int
      @JvmName("getCodeValue")
      get() = _builder.getCodeValue()
      @JvmName("setCodeValue")
      set(value) {
        _builder.setCodeValue(value)
      }
    /**
     * ```
     * Standard error code
     * ```
     *
     * `.unhinged.common.v1.ErrorCode code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * ```
     * Human-readable error message
     * ```
     *
     * `string message = 2;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * ```
     * Human-readable error message
     * ```
     *
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * ```
     * Additional error details
     * ```
     *
     * `string details = 3;`
     */
    public var details: kotlin.String
      @JvmName("getDetails")
      get() = _builder.getDetails()
      @JvmName("setDetails")
      set(value) {
        _builder.setDetails(value)
      }
    /**
     * ```
     * Additional error details
     * ```
     *
     * `string details = 3;`
     */
    public fun clearDetails() {
      _builder.clearDetails()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FieldErrorsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Field-specific validation errors
     * ```
     *
     * `repeated .unhinged.common.v1.ErrorField field_errors = 4;`
     */
     public val fieldErrors: com.google.protobuf.kotlin.DslList<unhinged.common.ErrorField, FieldErrorsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getFieldErrorsList()
      )
    /**
     * ```
     * Field-specific validation errors
     * ```
     *
     * `repeated .unhinged.common.v1.ErrorField field_errors = 4;`
     * @param value The fieldErrors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addFieldErrors")
    public fun com.google.protobuf.kotlin.DslList<unhinged.common.ErrorField, FieldErrorsProxy>.add(value: unhinged.common.ErrorField) {
      _builder.addFieldErrors(value)
    }
    /**
     * ```
     * Field-specific validation errors
     * ```
     *
     * `repeated .unhinged.common.v1.ErrorField field_errors = 4;`
     * @param value The fieldErrors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignFieldErrors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.common.ErrorField, FieldErrorsProxy>.plusAssign(value: unhinged.common.ErrorField) {
      add(value)
    }
    /**
     * ```
     * Field-specific validation errors
     * ```
     *
     * `repeated .unhinged.common.v1.ErrorField field_errors = 4;`
     * @param values The fieldErrors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllFieldErrors")
    public fun com.google.protobuf.kotlin.DslList<unhinged.common.ErrorField, FieldErrorsProxy>.addAll(values: kotlin.collections.Iterable<unhinged.common.ErrorField>) {
      _builder.addAllFieldErrors(values)
    }
    /**
     * ```
     * Field-specific validation errors
     * ```
     *
     * `repeated .unhinged.common.v1.ErrorField field_errors = 4;`
     * @param values The fieldErrors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllFieldErrors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.common.ErrorField, FieldErrorsProxy>.plusAssign(values: kotlin.collections.Iterable<unhinged.common.ErrorField>) {
      addAll(values)
    }
    /**
     * ```
     * Field-specific validation errors
     * ```
     *
     * `repeated .unhinged.common.v1.ErrorField field_errors = 4;`
     * @param index The index to set the value at.
     * @param value The fieldErrors to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setFieldErrors")
    public operator fun com.google.protobuf.kotlin.DslList<unhinged.common.ErrorField, FieldErrorsProxy>.set(index: kotlin.Int, value: unhinged.common.ErrorField) {
      _builder.setFieldErrors(index, value)
    }
    /**
     * ```
     * Field-specific validation errors
     * ```
     *
     * `repeated .unhinged.common.v1.ErrorField field_errors = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearFieldErrors")
    public fun com.google.protobuf.kotlin.DslList<unhinged.common.ErrorField, FieldErrorsProxy>.clear() {
      _builder.clearFieldErrors()
    }


    /**
     * ```
     * Debug info (dev/staging only)
     * ```
     *
     * `.google.protobuf.Struct debug_info = 5;`
     */
    public var debugInfo: com.google.protobuf.Struct
      @JvmName("getDebugInfo")
      get() = _builder.getDebugInfo()
      @JvmName("setDebugInfo")
      set(value) {
        _builder.setDebugInfo(value)
      }
    /**
     * ```
     * Debug info (dev/staging only)
     * ```
     *
     * `.google.protobuf.Struct debug_info = 5;`
     */
    public fun clearDebugInfo() {
      _builder.clearDebugInfo()
    }
    /**
     * ```
     * Debug info (dev/staging only)
     * ```
     *
     * `.google.protobuf.Struct debug_info = 5;`
     * @return Whether the debugInfo field is set.
     */
    public fun hasDebugInfo(): kotlin.Boolean {
      return _builder.hasDebugInfo()
    }

    /**
     * ```
     * Request ID for tracing
     * ```
     *
     * `string request_id = 6;`
     */
    public var requestId: kotlin.String
      @JvmName("getRequestId")
      get() = _builder.getRequestId()
      @JvmName("setRequestId")
      set(value) {
        _builder.setRequestId(value)
      }
    /**
     * ```
     * Request ID for tracing
     * ```
     *
     * `string request_id = 6;`
     */
    public fun clearRequestId() {
      _builder.clearRequestId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.common.Error.copy(block: `unhinged.common`.ErrorKt.Dsl.() -> kotlin.Unit): unhinged.common.Error =
  `unhinged.common`.ErrorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.common.ErrorOrBuilder.debugInfoOrNull: com.google.protobuf.Struct?
  get() = if (hasDebugInfo()) getDebugInfo() else null

