// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.common;

@kotlin.jvm.JvmName("-initializeerrorField")
public inline fun errorField(block: unhinged.common.ErrorFieldKt.Dsl.() -> kotlin.Unit): unhinged.common.ErrorField =
  unhinged.common.ErrorFieldKt.Dsl._create(unhinged.common.ErrorField.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Field-specific validation error
 * ```
 *
 * Protobuf type `unhinged.common.v1.ErrorField`
 */
public object ErrorFieldKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.common.ErrorField.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.common.ErrorField.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.common.ErrorField = _builder.build()

    /**
     * ```
     * Field name (dot notation for nested)
     * ```
     *
     * `string field = 1;`
     */
    public var field: kotlin.String
      @JvmName("getField")
      get() = _builder.getField()
      @JvmName("setField")
      set(value) {
        _builder.setField(value)
      }
    /**
     * ```
     * Field name (dot notation for nested)
     * ```
     *
     * `string field = 1;`
     */
    public fun clearField() {
      _builder.clearField()
    }

    /**
     * ```
     * Field-specific error message
     * ```
     *
     * `string message = 2;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * ```
     * Field-specific error message
     * ```
     *
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * ```
     * Field error code (optional)
     * ```
     *
     * `string code = 3;`
     */
    public var code: kotlin.String
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    /**
     * ```
     * Field error code (optional)
     * ```
     *
     * `string code = 3;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.common.ErrorField.copy(block: `unhinged.common`.ErrorFieldKt.Dsl.() -> kotlin.Unit): unhinged.common.ErrorField =
  `unhinged.common`.ErrorFieldKt.Dsl._create(this.toBuilder()).apply { block() }._build()

