// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.common;

@kotlin.jvm.JvmName("-initializehealthCheckResponse")
public inline fun healthCheckResponse(block: unhinged.common.HealthCheckResponseKt.Dsl.() -> kotlin.Unit): unhinged.common.HealthCheckResponse =
  unhinged.common.HealthCheckResponseKt.Dsl._create(unhinged.common.HealthCheckResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Universal health check response
 * ```
 *
 * Protobuf type `unhinged.common.v1.HealthCheckResponse`
 */
public object HealthCheckResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.common.HealthCheckResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.common.HealthCheckResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.common.HealthCheckResponse = _builder.build()

    /**
     * ```
     * Overall health status
     * ```
     *
     * `.unhinged.common.v1.HealthStatus status = 1;`
     */
    public var status: unhinged.common.HealthStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * ```
     * Overall health status
     * ```
     *
     * `.unhinged.common.v1.HealthStatus status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * ```
     * Human-readable status message
     * ```
     *
     * `string message = 2;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * ```
     * Human-readable status message
     * ```
     *
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DetailsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Component-specific health details
     * ```
     *
     * `map<string, string> details = 3;`
     */
     public val details: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getDetailsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getDetailsMap()
      )
    /**
     * ```
     * Component-specific health details
     * ```
     *
     * `map<string, string> details = 3;`
     */
    @JvmName("putDetails")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putDetails(key, value)
       }
    /**
     * ```
     * Component-specific health details
     * ```
     *
     * `map<string, string> details = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setDetails")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * ```
     * Component-specific health details
     * ```
     *
     * `map<string, string> details = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeDetails")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .remove(key: kotlin.String) {
         _builder.removeDetails(key)
       }
    /**
     * ```
     * Component-specific health details
     * ```
     *
     * `map<string, string> details = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllDetails")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllDetails(map)
       }
    /**
     * ```
     * Component-specific health details
     * ```
     *
     * `map<string, string> details = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearDetails")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .clear() {
         _builder.clearDetails()
       }

    /**
     * `.google.protobuf.Timestamp checked_at = 4;`
     */
    public var checkedAt: com.google.protobuf.Timestamp
      @JvmName("getCheckedAt")
      get() = _builder.getCheckedAt()
      @JvmName("setCheckedAt")
      set(value) {
        _builder.setCheckedAt(value)
      }
    /**
     * `.google.protobuf.Timestamp checked_at = 4;`
     */
    public fun clearCheckedAt() {
      _builder.clearCheckedAt()
    }
    /**
     * `.google.protobuf.Timestamp checked_at = 4;`
     * @return Whether the checkedAt field is set.
     */
    public fun hasCheckedAt(): kotlin.Boolean {
      return _builder.hasCheckedAt()
    }

    /**
     * `.google.protobuf.Duration response_time = 5;`
     */
    public var responseTime: com.google.protobuf.Duration
      @JvmName("getResponseTime")
      get() = _builder.getResponseTime()
      @JvmName("setResponseTime")
      set(value) {
        _builder.setResponseTime(value)
      }
    /**
     * `.google.protobuf.Duration response_time = 5;`
     */
    public fun clearResponseTime() {
      _builder.clearResponseTime()
    }
    /**
     * `.google.protobuf.Duration response_time = 5;`
     * @return Whether the responseTime field is set.
     */
    public fun hasResponseTime(): kotlin.Boolean {
      return _builder.hasResponseTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.common.HealthCheckResponse.copy(block: `unhinged.common`.HealthCheckResponseKt.Dsl.() -> kotlin.Unit): unhinged.common.HealthCheckResponse =
  `unhinged.common`.HealthCheckResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.common.HealthCheckResponseOrBuilder.checkedAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasCheckedAt()) getCheckedAt() else null

public val unhinged.common.HealthCheckResponseOrBuilder.responseTimeOrNull: com.google.protobuf.Duration?
  get() = if (hasResponseTime()) getResponseTime() else null

