// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.common;

@kotlin.jvm.JvmName("-initializepaginationResponse")
public inline fun paginationResponse(block: unhinged.common.PaginationResponseKt.Dsl.() -> kotlin.Unit): unhinged.common.PaginationResponse =
  unhinged.common.PaginationResponseKt.Dsl._create(unhinged.common.PaginationResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Universal pagination response
 * 
 * Provides consistent pagination metadata across all list operations
 * ```
 *
 * Protobuf type `unhinged.common.v1.PaginationResponse`
 */
public object PaginationResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.common.PaginationResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.common.PaginationResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.common.PaginationResponse = _builder.build()

    /**
     * ```
     * Cursor for next page (empty if last page)
     * ```
     *
     * `string next_page_token = 1;`
     */
    public var nextPageToken: kotlin.String
      @JvmName("getNextPageToken")
      get() = _builder.getNextPageToken()
      @JvmName("setNextPageToken")
      set(value) {
        _builder.setNextPageToken(value)
      }
    /**
     * ```
     * Cursor for next page (empty if last page)
     * ```
     *
     * `string next_page_token = 1;`
     */
    public fun clearNextPageToken() {
      _builder.clearNextPageToken()
    }

    /**
     * ```
     * Optional: expensive to compute
     * ```
     *
     * `int32 total_count = 2;`
     */
    public var totalCount: kotlin.Int
      @JvmName("getTotalCount")
      get() = _builder.getTotalCount()
      @JvmName("setTotalCount")
      set(value) {
        _builder.setTotalCount(value)
      }
    /**
     * ```
     * Optional: expensive to compute
     * ```
     *
     * `int32 total_count = 2;`
     */
    public fun clearTotalCount() {
      _builder.clearTotalCount()
    }

    /**
     * ```
     * Whether more results exist
     * ```
     *
     * `bool has_more = 3;`
     */
    public var hasMore: kotlin.Boolean
      @JvmName("getHasMore")
      get() = _builder.getHasMore()
      @JvmName("setHasMore")
      set(value) {
        _builder.setHasMore(value)
      }
    /**
     * ```
     * Whether more results exist
     * ```
     *
     * `bool has_more = 3;`
     */
    public fun clearHasMore() {
      _builder.clearHasMore()
    }

    /**
     * ```
     * Actual page size returned
     * ```
     *
     * `int32 page_size = 4;`
     */
    public var pageSize: kotlin.Int
      @JvmName("getPageSize")
      get() = _builder.getPageSize()
      @JvmName("setPageSize")
      set(value) {
        _builder.setPageSize(value)
      }
    /**
     * ```
     * Actual page size returned
     * ```
     *
     * `int32 page_size = 4;`
     */
    public fun clearPageSize() {
      _builder.clearPageSize()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.common.PaginationResponse.copy(block: `unhinged.common`.PaginationResponseKt.Dsl.() -> kotlin.Unit): unhinged.common.PaginationResponse =
  `unhinged.common`.PaginationResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

