// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.common;

@kotlin.jvm.JvmName("-initializeresourceMetadata")
public inline fun resourceMetadata(block: unhinged.common.ResourceMetadataKt.Dsl.() -> kotlin.Unit): unhinged.common.ResourceMetadata =
  unhinged.common.ResourceMetadataKt.Dsl._create(unhinged.common.ResourceMetadata.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Standard resource metadata for all entities
 * 
 * Every resource in the system (conversations, documents, audio, etc.)
 * should include this metadata for consistent ownership, auditing,
 * and lifecycle management.
 * ```
 *
 * Protobuf type `unhinged.common.v1.ResourceMetadata`
 */
public object ResourceMetadataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.common.ResourceMetadata.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.common.ResourceMetadata.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.common.ResourceMetadata = _builder.build()

    /**
     * ```
     * UUID of the resource
     * ```
     *
     * `string resource_id = 1;`
     */
    public var resourceId: kotlin.String
      @JvmName("getResourceId")
      get() = _builder.getResourceId()
      @JvmName("setResourceId")
      set(value) {
        _builder.setResourceId(value)
      }
    /**
     * ```
     * UUID of the resource
     * ```
     *
     * `string resource_id = 1;`
     */
    public fun clearResourceId() {
      _builder.clearResourceId()
    }

    /**
     * ```
     * Team ownership for multi-tenancy
     * ```
     *
     * `string team_id = 2;`
     */
    public var teamId: kotlin.String
      @JvmName("getTeamId")
      get() = _builder.getTeamId()
      @JvmName("setTeamId")
      set(value) {
        _builder.setTeamId(value)
      }
    /**
     * ```
     * Team ownership for multi-tenancy
     * ```
     *
     * `string team_id = 2;`
     */
    public fun clearTeamId() {
      _builder.clearTeamId()
    }

    /**
     * ```
     * Environment isolation
     * ```
     *
     * `string namespace_id = 3;`
     */
    public var namespaceId: kotlin.String
      @JvmName("getNamespaceId")
      get() = _builder.getNamespaceId()
      @JvmName("setNamespaceId")
      set(value) {
        _builder.setNamespaceId(value)
      }
    /**
     * ```
     * Environment isolation
     * ```
     *
     * `string namespace_id = 3;`
     */
    public fun clearNamespaceId() {
      _builder.clearNamespaceId()
    }

    /**
     * ```
     * User who created the resource
     * ```
     *
     * `string created_by = 4;`
     */
    public var createdBy: kotlin.String
      @JvmName("getCreatedBy")
      get() = _builder.getCreatedBy()
      @JvmName("setCreatedBy")
      set(value) {
        _builder.setCreatedBy(value)
      }
    /**
     * ```
     * User who created the resource
     * ```
     *
     * `string created_by = 4;`
     */
    public fun clearCreatedBy() {
      _builder.clearCreatedBy()
    }

    /**
     * `.google.protobuf.Timestamp created_at = 5;`
     */
    public var createdAt: com.google.protobuf.Timestamp
      @JvmName("getCreatedAt")
      get() = _builder.getCreatedAt()
      @JvmName("setCreatedAt")
      set(value) {
        _builder.setCreatedAt(value)
      }
    /**
     * `.google.protobuf.Timestamp created_at = 5;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
    /**
     * `.google.protobuf.Timestamp created_at = 5;`
     * @return Whether the createdAt field is set.
     */
    public fun hasCreatedAt(): kotlin.Boolean {
      return _builder.hasCreatedAt()
    }

    /**
     * `.google.protobuf.Timestamp updated_at = 6;`
     */
    public var updatedAt: com.google.protobuf.Timestamp
      @JvmName("getUpdatedAt")
      get() = _builder.getUpdatedAt()
      @JvmName("setUpdatedAt")
      set(value) {
        _builder.setUpdatedAt(value)
      }
    /**
     * `.google.protobuf.Timestamp updated_at = 6;`
     */
    public fun clearUpdatedAt() {
      _builder.clearUpdatedAt()
    }
    /**
     * `.google.protobuf.Timestamp updated_at = 6;`
     * @return Whether the updatedAt field is set.
     */
    public fun hasUpdatedAt(): kotlin.Boolean {
      return _builder.hasUpdatedAt()
    }

    /**
     * ```
     * Service-specific metadata
     * ```
     *
     * `.google.protobuf.Struct custom_metadata = 7;`
     */
    public var customMetadata: com.google.protobuf.Struct
      @JvmName("getCustomMetadata")
      get() = _builder.getCustomMetadata()
      @JvmName("setCustomMetadata")
      set(value) {
        _builder.setCustomMetadata(value)
      }
    /**
     * ```
     * Service-specific metadata
     * ```
     *
     * `.google.protobuf.Struct custom_metadata = 7;`
     */
    public fun clearCustomMetadata() {
      _builder.clearCustomMetadata()
    }
    /**
     * ```
     * Service-specific metadata
     * ```
     *
     * `.google.protobuf.Struct custom_metadata = 7;`
     * @return Whether the customMetadata field is set.
     */
    public fun hasCustomMetadata(): kotlin.Boolean {
      return _builder.hasCustomMetadata()
    }

    /**
     * ```
     * Optimistic locking version
     * ```
     *
     * `int32 version = 8;`
     */
    public var version: kotlin.Int
      @JvmName("getVersion")
      get() = _builder.getVersion()
      @JvmName("setVersion")
      set(value) {
        _builder.setVersion(value)
      }
    /**
     * ```
     * Optimistic locking version
     * ```
     *
     * `int32 version = 8;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TagsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * User-defined tags
     * ```
     *
     * `repeated string tags = 9;`
     * @return A list containing the tags.
     */
    public val tags: com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTagsList()
      )
    /**
     * ```
     * User-defined tags
     * ```
     *
     * `repeated string tags = 9;`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.add(value: kotlin.String) {
      _builder.addTags(value)
    }
    /**
     * ```
     * User-defined tags
     * ```
     *
     * `repeated string tags = 9;`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * User-defined tags
     * ```
     *
     * `repeated string tags = 9;`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllTags(values)
    }
    /**
     * ```
     * User-defined tags
     * ```
     *
     * `repeated string tags = 9;`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * User-defined tags
     * ```
     *
     * `repeated string tags = 9;`
     * @param index The index to set the value at.
     * @param value The tags to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTags")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setTags(index, value)
    }/**
     * ```
     * User-defined tags
     * ```
     *
     * `repeated string tags = 9;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.clear() {
      _builder.clearTags()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.common.ResourceMetadata.copy(block: `unhinged.common`.ResourceMetadataKt.Dsl.() -> kotlin.Unit): unhinged.common.ResourceMetadata =
  `unhinged.common`.ResourceMetadataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.common.ResourceMetadataOrBuilder.createdAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasCreatedAt()) getCreatedAt() else null

public val unhinged.common.ResourceMetadataOrBuilder.updatedAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasUpdatedAt()) getUpdatedAt() else null

public val unhinged.common.ResourceMetadataOrBuilder.customMetadataOrNull: com.google.protobuf.Struct?
  get() = if (hasCustomMetadata()) getCustomMetadata() else null

