// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.common;

@kotlin.jvm.JvmName("-initializeresourceReference")
public inline fun resourceReference(block: unhinged.common.ResourceReferenceKt.Dsl.() -> kotlin.Unit): unhinged.common.ResourceReference =
  unhinged.common.ResourceReferenceKt.Dsl._create(unhinged.common.ResourceReference.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Lightweight reference to any resource
 * 
 * Used for linking between resources without full object embedding
 * ```
 *
 * Protobuf type `unhinged.common.v1.ResourceReference`
 */
public object ResourceReferenceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.common.ResourceReference.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.common.ResourceReference.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.common.ResourceReference = _builder.build()

    /**
     * ```
     * "conversation", "document", "audio"
     * ```
     *
     * `string resource_type = 1;`
     */
    public var resourceType: kotlin.String
      @JvmName("getResourceType")
      get() = _builder.getResourceType()
      @JvmName("setResourceType")
      set(value) {
        _builder.setResourceType(value)
      }
    /**
     * ```
     * "conversation", "document", "audio"
     * ```
     *
     * `string resource_type = 1;`
     */
    public fun clearResourceType() {
      _builder.clearResourceType()
    }

    /**
     * ```
     * UUID of the referenced resource
     * ```
     *
     * `string resource_id = 2;`
     */
    public var resourceId: kotlin.String
      @JvmName("getResourceId")
      get() = _builder.getResourceId()
      @JvmName("setResourceId")
      set(value) {
        _builder.setResourceId(value)
      }
    /**
     * ```
     * UUID of the referenced resource
     * ```
     *
     * `string resource_id = 2;`
     */
    public fun clearResourceId() {
      _builder.clearResourceId()
    }

    /**
     * ```
     * Human-readable identifier
     * ```
     *
     * `string display_name = 3;`
     */
    public var displayName: kotlin.String
      @JvmName("getDisplayName")
      get() = _builder.getDisplayName()
      @JvmName("setDisplayName")
      set(value) {
        _builder.setDisplayName(value)
      }
    /**
     * ```
     * Human-readable identifier
     * ```
     *
     * `string display_name = 3;`
     */
    public fun clearDisplayName() {
      _builder.clearDisplayName()
    }

    /**
     * ```
     * Optional: direct access URL
     * ```
     *
     * `string url = 4;`
     */
    public var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.getUrl()
      @JvmName("setUrl")
      set(value) {
        _builder.setUrl(value)
      }
    /**
     * ```
     * Optional: direct access URL
     * ```
     *
     * `string url = 4;`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.common.ResourceReference.copy(block: `unhinged.common`.ResourceReferenceKt.Dsl.() -> kotlin.Unit): unhinged.common.ResourceReference =
  `unhinged.common`.ResourceReferenceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

