// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.common;

@kotlin.jvm.JvmName("-initializestandardResponse")
public inline fun standardResponse(block: unhinged.common.StandardResponseKt.Dsl.() -> kotlin.Unit): unhinged.common.StandardResponse =
  unhinged.common.StandardResponseKt.Dsl._create(unhinged.common.StandardResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Standard response wrapper for all operations
 * 
 * Provides consistent success/error handling across all services
 * ```
 *
 * Protobuf type `unhinged.common.v1.StandardResponse`
 */
public object StandardResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.common.StandardResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.common.StandardResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.common.StandardResponse = _builder.build()

    /**
     * ```
     * Operation success indicator
     * ```
     *
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * ```
     * Operation success indicator
     * ```
     *
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * ```
     * Human-readable result message
     * ```
     *
     * `string message = 2;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * ```
     * Human-readable result message
     * ```
     *
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * ```
     * Error details (if success = false)
     * ```
     *
     * `.unhinged.common.v1.Error error = 3;`
     */
    public var error: unhinged.common.Error
      @JvmName("getError")
      get() = _builder.getError()
      @JvmName("setError")
      set(value) {
        _builder.setError(value)
      }
    /**
     * ```
     * Error details (if success = false)
     * ```
     *
     * `.unhinged.common.v1.Error error = 3;`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * ```
     * Error details (if success = false)
     * ```
     *
     * `.unhinged.common.v1.Error error = 3;`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    /**
     * ```
     * Operation-specific metadata
     * ```
     *
     * `.google.protobuf.Struct metadata = 4;`
     */
    public var metadata: com.google.protobuf.Struct
      @JvmName("getMetadata")
      get() = _builder.getMetadata()
      @JvmName("setMetadata")
      set(value) {
        _builder.setMetadata(value)
      }
    /**
     * ```
     * Operation-specific metadata
     * ```
     *
     * `.google.protobuf.Struct metadata = 4;`
     */
    public fun clearMetadata() {
      _builder.clearMetadata()
    }
    /**
     * ```
     * Operation-specific metadata
     * ```
     *
     * `.google.protobuf.Struct metadata = 4;`
     * @return Whether the metadata field is set.
     */
    public fun hasMetadata(): kotlin.Boolean {
      return _builder.hasMetadata()
    }

    /**
     * ```
     * Request ID for tracing
     * ```
     *
     * `string request_id = 5;`
     */
    public var requestId: kotlin.String
      @JvmName("getRequestId")
      get() = _builder.getRequestId()
      @JvmName("setRequestId")
      set(value) {
        _builder.setRequestId(value)
      }
    /**
     * ```
     * Request ID for tracing
     * ```
     *
     * `string request_id = 5;`
     */
    public fun clearRequestId() {
      _builder.clearRequestId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.common.StandardResponse.copy(block: `unhinged.common`.StandardResponseKt.Dsl.() -> kotlin.Unit): unhinged.common.StandardResponse =
  `unhinged.common`.StandardResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.common.StandardResponseOrBuilder.errorOrNull: unhinged.common.Error?
  get() = if (hasError()) getError() else null

public val unhinged.common.StandardResponseOrBuilder.metadataOrNull: com.google.protobuf.Struct?
  get() = if (hasMetadata()) getMetadata() else null

