// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.common;

@kotlin.jvm.JvmName("-initializestreamChunk")
public inline fun streamChunk(block: unhinged.common.StreamChunkKt.Dsl.() -> kotlin.Unit): unhinged.common.StreamChunk =
  unhinged.common.StreamChunkKt.Dsl._create(unhinged.common.StreamChunk.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Universal streaming chunk
 * 
 * Used for all streaming operations (chat, audio, LLM completions)
 * to provide consistent streaming behavior across services.
 * ```
 *
 * Protobuf type `unhinged.common.v1.StreamChunk`
 */
public object StreamChunkKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.common.StreamChunk.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.common.StreamChunk.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.common.StreamChunk = _builder.build()

    /**
     * ```
     * Unique identifier for this stream
     * ```
     *
     * `string stream_id = 1;`
     */
    public var streamId: kotlin.String
      @JvmName("getStreamId")
      get() = _builder.getStreamId()
      @JvmName("setStreamId")
      set(value) {
        _builder.setStreamId(value)
      }
    /**
     * ```
     * Unique identifier for this stream
     * ```
     *
     * `string stream_id = 1;`
     */
    public fun clearStreamId() {
      _builder.clearStreamId()
    }

    /**
     * ```
     * Ordering within stream
     * ```
     *
     * `int32 sequence_number = 2;`
     */
    public var sequenceNumber: kotlin.Int
      @JvmName("getSequenceNumber")
      get() = _builder.getSequenceNumber()
      @JvmName("setSequenceNumber")
      set(value) {
        _builder.setSequenceNumber(value)
      }
    /**
     * ```
     * Ordering within stream
     * ```
     *
     * `int32 sequence_number = 2;`
     */
    public fun clearSequenceNumber() {
      _builder.clearSequenceNumber()
    }

    /**
     * ```
     * Type of chunk content
     * ```
     *
     * `.unhinged.common.v1.ChunkType type = 3;`
     */
    public var type: unhinged.common.ChunkType
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    public var typeValue: kotlin.Int
      @JvmName("getTypeValue")
      get() = _builder.getTypeValue()
      @JvmName("setTypeValue")
      set(value) {
        _builder.setTypeValue(value)
      }
    /**
     * ```
     * Type of chunk content
     * ```
     *
     * `.unhinged.common.v1.ChunkType type = 3;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * ```
     * Payload (use one of these)
     * ```
     *
     * `bytes data = 4;`
     */
    public var data: com.google.protobuf.ByteString
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * ```
     * Payload (use one of these)
     * ```
     *
     * `bytes data = 4;`
     */
    public fun clearData() {
      _builder.clearData()
    }

    /**
     * ```
     * Text payload
     * ```
     *
     * `string text = 5;`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * ```
     * Text payload
     * ```
     *
     * `string text = 5;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * ```
     * Structured data payload
     * ```
     *
     * `.google.protobuf.Struct structured = 6;`
     */
    public var structured: com.google.protobuf.Struct
      @JvmName("getStructured")
      get() = _builder.getStructured()
      @JvmName("setStructured")
      set(value) {
        _builder.setStructured(value)
      }
    /**
     * ```
     * Structured data payload
     * ```
     *
     * `.google.protobuf.Struct structured = 6;`
     */
    public fun clearStructured() {
      _builder.clearStructured()
    }
    /**
     * ```
     * Structured data payload
     * ```
     *
     * `.google.protobuf.Struct structured = 6;`
     * @return Whether the structured field is set.
     */
    public fun hasStructured(): kotlin.Boolean {
      return _builder.hasStructured()
    }

    /**
     * ```
     * Chunk-specific metadata
     * ```
     *
     * `.google.protobuf.Struct metadata = 7;`
     */
    public var metadata: com.google.protobuf.Struct
      @JvmName("getMetadata")
      get() = _builder.getMetadata()
      @JvmName("setMetadata")
      set(value) {
        _builder.setMetadata(value)
      }
    /**
     * ```
     * Chunk-specific metadata
     * ```
     *
     * `.google.protobuf.Struct metadata = 7;`
     */
    public fun clearMetadata() {
      _builder.clearMetadata()
    }
    /**
     * ```
     * Chunk-specific metadata
     * ```
     *
     * `.google.protobuf.Struct metadata = 7;`
     * @return Whether the metadata field is set.
     */
    public fun hasMetadata(): kotlin.Boolean {
      return _builder.hasMetadata()
    }

    /**
     * ```
     * Last chunk in stream
     * ```
     *
     * `bool is_final = 8;`
     */
    public var isFinal: kotlin.Boolean
      @JvmName("getIsFinal")
      get() = _builder.getIsFinal()
      @JvmName("setIsFinal")
      set(value) {
        _builder.setIsFinal(value)
      }
    /**
     * ```
     * Last chunk in stream
     * ```
     *
     * `bool is_final = 8;`
     */
    public fun clearIsFinal() {
      _builder.clearIsFinal()
    }

    /**
     * ```
     * Processing status
     * ```
     *
     * `.unhinged.common.v1.ChunkStatus status = 9;`
     */
    public var status: unhinged.common.ChunkStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * ```
     * Processing status
     * ```
     *
     * `.unhinged.common.v1.ChunkStatus status = 9;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 10;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 10;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 10;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.common.StreamChunk.copy(block: `unhinged.common`.StreamChunkKt.Dsl.() -> kotlin.Unit): unhinged.common.StreamChunk =
  `unhinged.common`.StreamChunkKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.common.StreamChunkOrBuilder.structuredOrNull: com.google.protobuf.Struct?
  get() = if (hasStructured()) getStructured() else null

public val unhinged.common.StreamChunkOrBuilder.metadataOrNull: com.google.protobuf.Struct?
  get() = if (hasMetadata()) getMetadata() else null

public val unhinged.common.StreamChunkOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

