// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.common;

@kotlin.jvm.JvmName("-initializeusageMetrics")
public inline fun usageMetrics(block: unhinged.common.UsageMetricsKt.Dsl.() -> kotlin.Unit): unhinged.common.UsageMetrics =
  unhinged.common.UsageMetricsKt.Dsl._create(unhinged.common.UsageMetrics.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Universal usage metrics
 * 
 * Tracks resource consumption across different service types
 * for billing, monitoring, and optimization.
 * ```
 *
 * Protobuf type `unhinged.common.v1.UsageMetrics`
 */
public object UsageMetricsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.common.UsageMetrics.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.common.UsageMetrics.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.common.UsageMetrics = _builder.build()

    /**
     * ```
     * LLM token consumption
     * ```
     *
     * `.unhinged.common.v1.TokenUsage tokens = 1;`
     */
    public var tokens: unhinged.common.TokenUsage
      @JvmName("getTokens")
      get() = _builder.getTokens()
      @JvmName("setTokens")
      set(value) {
        _builder.setTokens(value)
      }
    /**
     * ```
     * LLM token consumption
     * ```
     *
     * `.unhinged.common.v1.TokenUsage tokens = 1;`
     */
    public fun clearTokens() {
      _builder.clearTokens()
    }
    /**
     * ```
     * LLM token consumption
     * ```
     *
     * `.unhinged.common.v1.TokenUsage tokens = 1;`
     * @return Whether the tokens field is set.
     */
    public fun hasTokens(): kotlin.Boolean {
      return _builder.hasTokens()
    }

    /**
     * ```
     * Audio processing metrics
     * ```
     *
     * `.unhinged.common.v1.AudioUsage audio = 2;`
     */
    public var audio: unhinged.common.AudioUsage
      @JvmName("getAudio")
      get() = _builder.getAudio()
      @JvmName("setAudio")
      set(value) {
        _builder.setAudio(value)
      }
    /**
     * ```
     * Audio processing metrics
     * ```
     *
     * `.unhinged.common.v1.AudioUsage audio = 2;`
     */
    public fun clearAudio() {
      _builder.clearAudio()
    }
    /**
     * ```
     * Audio processing metrics
     * ```
     *
     * `.unhinged.common.v1.AudioUsage audio = 2;`
     * @return Whether the audio field is set.
     */
    public fun hasAudio(): kotlin.Boolean {
      return _builder.hasAudio()
    }

    /**
     * ```
     * Data transfer metrics
     * ```
     *
     * `.unhinged.common.v1.DataUsage data = 3;`
     */
    public var data: unhinged.common.DataUsage
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * ```
     * Data transfer metrics
     * ```
     *
     * `.unhinged.common.v1.DataUsage data = 3;`
     */
    public fun clearData() {
      _builder.clearData()
    }
    /**
     * ```
     * Data transfer metrics
     * ```
     *
     * `.unhinged.common.v1.DataUsage data = 3;`
     * @return Whether the data field is set.
     */
    public fun hasData(): kotlin.Boolean {
      return _builder.hasData()
    }

    /**
     * ```
     * Compute resource usage
     * ```
     *
     * `.unhinged.common.v1.ComputeUsage compute = 4;`
     */
    public var compute: unhinged.common.ComputeUsage
      @JvmName("getCompute")
      get() = _builder.getCompute()
      @JvmName("setCompute")
      set(value) {
        _builder.setCompute(value)
      }
    /**
     * ```
     * Compute resource usage
     * ```
     *
     * `.unhinged.common.v1.ComputeUsage compute = 4;`
     */
    public fun clearCompute() {
      _builder.clearCompute()
    }
    /**
     * ```
     * Compute resource usage
     * ```
     *
     * `.unhinged.common.v1.ComputeUsage compute = 4;`
     * @return Whether the compute field is set.
     */
    public fun hasCompute(): kotlin.Boolean {
      return _builder.hasCompute()
    }

    /**
     * `.google.protobuf.Duration processing_time = 5;`
     */
    public var processingTime: com.google.protobuf.Duration
      @JvmName("getProcessingTime")
      get() = _builder.getProcessingTime()
      @JvmName("setProcessingTime")
      set(value) {
        _builder.setProcessingTime(value)
      }
    /**
     * `.google.protobuf.Duration processing_time = 5;`
     */
    public fun clearProcessingTime() {
      _builder.clearProcessingTime()
    }
    /**
     * `.google.protobuf.Duration processing_time = 5;`
     * @return Whether the processingTime field is set.
     */
    public fun hasProcessingTime(): kotlin.Boolean {
      return _builder.hasProcessingTime()
    }

    /**
     * `.google.protobuf.Timestamp recorded_at = 6;`
     */
    public var recordedAt: com.google.protobuf.Timestamp
      @JvmName("getRecordedAt")
      get() = _builder.getRecordedAt()
      @JvmName("setRecordedAt")
      set(value) {
        _builder.setRecordedAt(value)
      }
    /**
     * `.google.protobuf.Timestamp recorded_at = 6;`
     */
    public fun clearRecordedAt() {
      _builder.clearRecordedAt()
    }
    /**
     * `.google.protobuf.Timestamp recorded_at = 6;`
     * @return Whether the recordedAt field is set.
     */
    public fun hasRecordedAt(): kotlin.Boolean {
      return _builder.hasRecordedAt()
    }

    /**
     * ```
     * Estimated cost in USD
     * ```
     *
     * `float cost_usd = 7;`
     */
    public var costUsd: kotlin.Float
      @JvmName("getCostUsd")
      get() = _builder.getCostUsd()
      @JvmName("setCostUsd")
      set(value) {
        _builder.setCostUsd(value)
      }
    /**
     * ```
     * Estimated cost in USD
     * ```
     *
     * `float cost_usd = 7;`
     */
    public fun clearCostUsd() {
      _builder.clearCostUsd()
    }
    public val metricCase: unhinged.common.UsageMetrics.MetricCase
      @JvmName("getMetricCase")
      get() = _builder.getMetricCase()

    public fun clearMetric() {
      _builder.clearMetric()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.common.UsageMetrics.copy(block: `unhinged.common`.UsageMetricsKt.Dsl.() -> kotlin.Unit): unhinged.common.UsageMetrics =
  `unhinged.common`.UsageMetricsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.common.UsageMetricsOrBuilder.tokensOrNull: unhinged.common.TokenUsage?
  get() = if (hasTokens()) getTokens() else null

public val unhinged.common.UsageMetricsOrBuilder.audioOrNull: unhinged.common.AudioUsage?
  get() = if (hasAudio()) getAudio() else null

public val unhinged.common.UsageMetricsOrBuilder.dataOrNull: unhinged.common.DataUsage?
  get() = if (hasData()) getData() else null

public val unhinged.common.UsageMetricsOrBuilder.computeOrNull: unhinged.common.ComputeUsage?
  get() = if (hasCompute()) getCompute() else null

public val unhinged.common.UsageMetricsOrBuilder.processingTimeOrNull: com.google.protobuf.Duration?
  get() = if (hasProcessingTime()) getProcessingTime() else null

public val unhinged.common.UsageMetricsOrBuilder.recordedAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasRecordedAt()) getRecordedAt() else null

