// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializeanalyzeAudioResponse")
public inline fun analyzeAudioResponse(block: unhinged.audio.AnalyzeAudioResponseKt.Dsl.() -> kotlin.Unit): unhinged.audio.AnalyzeAudioResponse =
  unhinged.audio.AnalyzeAudioResponseKt.Dsl._create(unhinged.audio.AnalyzeAudioResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.audio.v1.AnalyzeAudioResponse`
 */
public object AnalyzeAudioResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.AnalyzeAudioResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.AnalyzeAudioResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.AnalyzeAudioResponse = _builder.build()

    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     */
    public var response: unhinged.common.StandardResponse
      @JvmName("getResponse")
      get() = _builder.getResponse()
      @JvmName("setResponse")
      set(value) {
        _builder.setResponse(value)
      }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     */
    public fun clearResponse() {
      _builder.clearResponse()
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     * @return Whether the response field is set.
     */
    public fun hasResponse(): kotlin.Boolean {
      return _builder.hasResponse()
    }

    /**
     * `.unhinged.audio.v1.AudioAnalysis analysis = 2;`
     */
    public var analysis: unhinged.audio.AudioAnalysis
      @JvmName("getAnalysis")
      get() = _builder.getAnalysis()
      @JvmName("setAnalysis")
      set(value) {
        _builder.setAnalysis(value)
      }
    /**
     * `.unhinged.audio.v1.AudioAnalysis analysis = 2;`
     */
    public fun clearAnalysis() {
      _builder.clearAnalysis()
    }
    /**
     * `.unhinged.audio.v1.AudioAnalysis analysis = 2;`
     * @return Whether the analysis field is set.
     */
    public fun hasAnalysis(): kotlin.Boolean {
      return _builder.hasAnalysis()
    }

    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.AudioUsage usage = 3;`
     */
    public var usage: unhinged.common.AudioUsage
      @JvmName("getUsage")
      get() = _builder.getUsage()
      @JvmName("setUsage")
      set(value) {
        _builder.setUsage(value)
      }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.AudioUsage usage = 3;`
     */
    public fun clearUsage() {
      _builder.clearUsage()
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.AudioUsage usage = 3;`
     * @return Whether the usage field is set.
     */
    public fun hasUsage(): kotlin.Boolean {
      return _builder.hasUsage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.AnalyzeAudioResponse.copy(block: `unhinged.audio`.AnalyzeAudioResponseKt.Dsl.() -> kotlin.Unit): unhinged.audio.AnalyzeAudioResponse =
  `unhinged.audio`.AnalyzeAudioResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.audio.AnalyzeAudioResponseOrBuilder.responseOrNull: unhinged.common.StandardResponse?
  get() = if (hasResponse()) getResponse() else null

public val unhinged.audio.AnalyzeAudioResponseOrBuilder.analysisOrNull: unhinged.audio.AudioAnalysis?
  get() = if (hasAnalysis()) getAnalysis() else null

public val unhinged.audio.AnalyzeAudioResponseOrBuilder.usageOrNull: unhinged.common.AudioUsage?
  get() = if (hasUsage()) getUsage() else null

