// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializeaudioQualityMetrics")
public inline fun audioQualityMetrics(block: unhinged.audio.AudioQualityMetricsKt.Dsl.() -> kotlin.Unit): unhinged.audio.AudioQualityMetrics =
  unhinged.audio.AudioQualityMetricsKt.Dsl._create(unhinged.audio.AudioQualityMetrics.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.audio.v1.AudioQualityMetrics`
 */
public object AudioQualityMetricsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.AudioQualityMetrics.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.AudioQualityMetrics.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.AudioQualityMetrics = _builder.build()

    /**
     * `float signal_to_noise_ratio = 1;`
     */
    public var signalToNoiseRatio: kotlin.Float
      @JvmName("getSignalToNoiseRatio")
      get() = _builder.getSignalToNoiseRatio()
      @JvmName("setSignalToNoiseRatio")
      set(value) {
        _builder.setSignalToNoiseRatio(value)
      }
    /**
     * `float signal_to_noise_ratio = 1;`
     */
    public fun clearSignalToNoiseRatio() {
      _builder.clearSignalToNoiseRatio()
    }

    /**
     * `float dynamic_range = 2;`
     */
    public var dynamicRange: kotlin.Float
      @JvmName("getDynamicRange")
      get() = _builder.getDynamicRange()
      @JvmName("setDynamicRange")
      set(value) {
        _builder.setDynamicRange(value)
      }
    /**
     * `float dynamic_range = 2;`
     */
    public fun clearDynamicRange() {
      _builder.clearDynamicRange()
    }

    /**
     * `bool has_clipping = 3;`
     */
    public var hasClipping: kotlin.Boolean
      @JvmName("getHasClipping")
      get() = _builder.getHasClipping()
      @JvmName("setHasClipping")
      set(value) {
        _builder.setHasClipping(value)
      }
    /**
     * `bool has_clipping = 3;`
     */
    public fun clearHasClipping() {
      _builder.clearHasClipping()
    }

    /**
     * `bool has_background_noise = 4;`
     */
    public var hasBackgroundNoise: kotlin.Boolean
      @JvmName("getHasBackgroundNoise")
      get() = _builder.getHasBackgroundNoise()
      @JvmName("setHasBackgroundNoise")
      set(value) {
        _builder.setHasBackgroundNoise(value)
      }
    /**
     * `bool has_background_noise = 4;`
     */
    public fun clearHasBackgroundNoise() {
      _builder.clearHasBackgroundNoise()
    }

    /**
     * ```
     * 0.0 to 1.0
     * ```
     *
     * `float overall_quality_score = 5;`
     */
    public var overallQualityScore: kotlin.Float
      @JvmName("getOverallQualityScore")
      get() = _builder.getOverallQualityScore()
      @JvmName("setOverallQualityScore")
      set(value) {
        _builder.setOverallQualityScore(value)
      }
    /**
     * ```
     * 0.0 to 1.0
     * ```
     *
     * `float overall_quality_score = 5;`
     */
    public fun clearOverallQualityScore() {
      _builder.clearOverallQualityScore()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.AudioQualityMetrics.copy(block: `unhinged.audio`.AudioQualityMetricsKt.Dsl.() -> kotlin.Unit): unhinged.audio.AudioQualityMetrics =
  `unhinged.audio`.AudioQualityMetricsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

