// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializeaudioOptions")
public inline fun audioOptions(block: unhinged.audio.AudioOptionsKt.Dsl.() -> kotlin.Unit): unhinged.audio.AudioOptions =
  unhinged.audio.AudioOptionsKt.Dsl._create(unhinged.audio.AudioOptions.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Audio processing options
 * ```
 *
 * Protobuf type `unhinged.audio.v1.AudioOptions`
 */
public object AudioOptionsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.AudioOptions.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.AudioOptions.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.AudioOptions = _builder.build()

    /**
     * ```
     * 0.25 to 4.0 (playback speed)
     * ```
     *
     * `float speed = 1;`
     */
    public var speed: kotlin.Float
      @JvmName("getSpeed")
      get() = _builder.getSpeed()
      @JvmName("setSpeed")
      set(value) {
        _builder.setSpeed(value)
      }
    /**
     * ```
     * 0.25 to 4.0 (playback speed)
     * ```
     *
     * `float speed = 1;`
     */
    public fun clearSpeed() {
      _builder.clearSpeed()
    }

    /**
     * ```
     * -20 to 20 semitones
     * ```
     *
     * `float pitch = 2;`
     */
    public var pitch: kotlin.Float
      @JvmName("getPitch")
      get() = _builder.getPitch()
      @JvmName("setPitch")
      set(value) {
        _builder.setPitch(value)
      }
    /**
     * ```
     * -20 to 20 semitones
     * ```
     *
     * `float pitch = 2;`
     */
    public fun clearPitch() {
      _builder.clearPitch()
    }

    /**
     * ```
     * 0.0 to 2.0 (volume multiplier)
     * ```
     *
     * `float volume = 3;`
     */
    public var volume: kotlin.Float
      @JvmName("getVolume")
      get() = _builder.getVolume()
      @JvmName("setVolume")
      set(value) {
        _builder.setVolume(value)
      }
    /**
     * ```
     * 0.0 to 2.0 (volume multiplier)
     * ```
     *
     * `float volume = 3;`
     */
    public fun clearVolume() {
      _builder.clearVolume()
    }

    /**
     * ```
     * Quality settings
     * ```
     *
     * `.unhinged.audio.v1.AudioQuality quality = 4;`
     */
    public var quality: unhinged.audio.AudioQuality
      @JvmName("getQuality")
      get() = _builder.getQuality()
      @JvmName("setQuality")
      set(value) {
        _builder.setQuality(value)
      }
    public var qualityValue: kotlin.Int
      @JvmName("getQualityValue")
      get() = _builder.getQualityValue()
      @JvmName("setQualityValue")
      set(value) {
        _builder.setQualityValue(value)
      }
    /**
     * ```
     * Quality settings
     * ```
     *
     * `.unhinged.audio.v1.AudioQuality quality = 4;`
     */
    public fun clearQuality() {
      _builder.clearQuality()
    }

    /**
     * `bool enable_noise_reduction = 5;`
     */
    public var enableNoiseReduction: kotlin.Boolean
      @JvmName("getEnableNoiseReduction")
      get() = _builder.getEnableNoiseReduction()
      @JvmName("setEnableNoiseReduction")
      set(value) {
        _builder.setEnableNoiseReduction(value)
      }
    /**
     * `bool enable_noise_reduction = 5;`
     */
    public fun clearEnableNoiseReduction() {
      _builder.clearEnableNoiseReduction()
    }

    /**
     * `bool enable_echo_cancellation = 6;`
     */
    public var enableEchoCancellation: kotlin.Boolean
      @JvmName("getEnableEchoCancellation")
      get() = _builder.getEnableEchoCancellation()
      @JvmName("setEnableEchoCancellation")
      set(value) {
        _builder.setEnableEchoCancellation(value)
      }
    /**
     * `bool enable_echo_cancellation = 6;`
     */
    public fun clearEnableEchoCancellation() {
      _builder.clearEnableEchoCancellation()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.AudioOptions.copy(block: `unhinged.audio`.AudioOptionsKt.Dsl.() -> kotlin.Unit): unhinged.audio.AudioOptions =
  `unhinged.audio`.AudioOptionsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

