// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializeaudioMetadata")
public inline fun audioMetadata(block: unhinged.audio.AudioMetadataKt.Dsl.() -> kotlin.Unit): unhinged.audio.AudioMetadata =
  unhinged.audio.AudioMetadataKt.Dsl._create(unhinged.audio.AudioMetadata.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Audio metadata for streaming
 * ```
 *
 * Protobuf type `unhinged.audio.v1.AudioMetadata`
 */
public object AudioMetadataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.AudioMetadata.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.AudioMetadata.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.AudioMetadata = _builder.build()

    /**
     * `.unhinged.audio.v1.AudioFormat format = 1;`
     */
    public var format: unhinged.audio.AudioFormat
      @JvmName("getFormat")
      get() = _builder.getFormat()
      @JvmName("setFormat")
      set(value) {
        _builder.setFormat(value)
      }
    public var formatValue: kotlin.Int
      @JvmName("getFormatValue")
      get() = _builder.getFormatValue()
      @JvmName("setFormatValue")
      set(value) {
        _builder.setFormatValue(value)
      }
    /**
     * `.unhinged.audio.v1.AudioFormat format = 1;`
     */
    public fun clearFormat() {
      _builder.clearFormat()
    }

    /**
     * `int32 sample_rate = 2;`
     */
    public var sampleRate: kotlin.Int
      @JvmName("getSampleRate")
      get() = _builder.getSampleRate()
      @JvmName("setSampleRate")
      set(value) {
        _builder.setSampleRate(value)
      }
    /**
     * `int32 sample_rate = 2;`
     */
    public fun clearSampleRate() {
      _builder.clearSampleRate()
    }

    /**
     * `int32 channels = 3;`
     */
    public var channels: kotlin.Int
      @JvmName("getChannels")
      get() = _builder.getChannels()
      @JvmName("setChannels")
      set(value) {
        _builder.setChannels(value)
      }
    /**
     * `int32 channels = 3;`
     */
    public fun clearChannels() {
      _builder.clearChannels()
    }

    /**
     * `int32 bit_depth = 4;`
     */
    public var bitDepth: kotlin.Int
      @JvmName("getBitDepth")
      get() = _builder.getBitDepth()
      @JvmName("setBitDepth")
      set(value) {
        _builder.setBitDepth(value)
      }
    /**
     * `int32 bit_depth = 4;`
     */
    public fun clearBitDepth() {
      _builder.clearBitDepth()
    }

    /**
     * `float duration_seconds = 5;`
     */
    public var durationSeconds: kotlin.Float
      @JvmName("getDurationSeconds")
      get() = _builder.getDurationSeconds()
      @JvmName("setDurationSeconds")
      set(value) {
        _builder.setDurationSeconds(value)
      }
    /**
     * `float duration_seconds = 5;`
     */
    public fun clearDurationSeconds() {
      _builder.clearDurationSeconds()
    }

    /**
     * `int64 total_bytes = 6;`
     */
    public var totalBytes: kotlin.Long
      @JvmName("getTotalBytes")
      get() = _builder.getTotalBytes()
      @JvmName("setTotalBytes")
      set(value) {
        _builder.setTotalBytes(value)
      }
    /**
     * `int64 total_bytes = 6;`
     */
    public fun clearTotalBytes() {
      _builder.clearTotalBytes()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.AudioMetadata.copy(block: `unhinged.audio`.AudioMetadataKt.Dsl.() -> kotlin.Unit): unhinged.audio.AudioMetadata =
  `unhinged.audio`.AudioMetadataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

