// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializeconvertAudioResponse")
public inline fun convertAudioResponse(block: unhinged.audio.ConvertAudioResponseKt.Dsl.() -> kotlin.Unit): unhinged.audio.ConvertAudioResponse =
  unhinged.audio.ConvertAudioResponseKt.Dsl._create(unhinged.audio.ConvertAudioResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.audio.v1.ConvertAudioResponse`
 */
public object ConvertAudioResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.ConvertAudioResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.ConvertAudioResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.ConvertAudioResponse = _builder.build()

    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     */
    public var response: unhinged.common.StandardResponse
      @JvmName("getResponse")
      get() = _builder.getResponse()
      @JvmName("setResponse")
      set(value) {
        _builder.setResponse(value)
      }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     */
    public fun clearResponse() {
      _builder.clearResponse()
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     * @return Whether the response field is set.
     */
    public fun hasResponse(): kotlin.Boolean {
      return _builder.hasResponse()
    }

    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.Attachment converted_audio = 2;`
     */
    public var convertedAudio: unhinged.common.Attachment
      @JvmName("getConvertedAudio")
      get() = _builder.getConvertedAudio()
      @JvmName("setConvertedAudio")
      set(value) {
        _builder.setConvertedAudio(value)
      }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.Attachment converted_audio = 2;`
     */
    public fun clearConvertedAudio() {
      _builder.clearConvertedAudio()
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.Attachment converted_audio = 2;`
     * @return Whether the convertedAudio field is set.
     */
    public fun hasConvertedAudio(): kotlin.Boolean {
      return _builder.hasConvertedAudio()
    }

    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.AudioUsage usage = 3;`
     */
    public var usage: unhinged.common.AudioUsage
      @JvmName("getUsage")
      get() = _builder.getUsage()
      @JvmName("setUsage")
      set(value) {
        _builder.setUsage(value)
      }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.AudioUsage usage = 3;`
     */
    public fun clearUsage() {
      _builder.clearUsage()
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.AudioUsage usage = 3;`
     * @return Whether the usage field is set.
     */
    public fun hasUsage(): kotlin.Boolean {
      return _builder.hasUsage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.ConvertAudioResponse.copy(block: `unhinged.audio`.ConvertAudioResponseKt.Dsl.() -> kotlin.Unit): unhinged.audio.ConvertAudioResponse =
  `unhinged.audio`.ConvertAudioResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.audio.ConvertAudioResponseOrBuilder.responseOrNull: unhinged.common.StandardResponse?
  get() = if (hasResponse()) getResponse() else null

public val unhinged.audio.ConvertAudioResponseOrBuilder.convertedAudioOrNull: unhinged.common.Attachment?
  get() = if (hasConvertedAudio()) getConvertedAudio() else null

public val unhinged.audio.ConvertAudioResponseOrBuilder.usageOrNull: unhinged.common.AudioUsage?
  get() = if (hasUsage()) getUsage() else null

