// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializecreateCustomVoiceRequest")
public inline fun createCustomVoiceRequest(block: unhinged.audio.CreateCustomVoiceRequestKt.Dsl.() -> kotlin.Unit): unhinged.audio.CreateCustomVoiceRequest =
  unhinged.audio.CreateCustomVoiceRequestKt.Dsl._create(unhinged.audio.CreateCustomVoiceRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.audio.v1.CreateCustomVoiceRequest`
 */
public object CreateCustomVoiceRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.CreateCustomVoiceRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.CreateCustomVoiceRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.CreateCustomVoiceRequest = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string description = 2;`
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.getDescription()
      @JvmName("setDescription")
      set(value) {
        _builder.setDescription(value)
      }
    /**
     * `string description = 2;`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TrainingSamplesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Attachment training_samples = 3;`
     */
     public val trainingSamples: com.google.protobuf.kotlin.DslList<unhinged.common.Attachment, TrainingSamplesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTrainingSamplesList()
      )
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Attachment training_samples = 3;`
     * @param value The trainingSamples to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTrainingSamples")
    public fun com.google.protobuf.kotlin.DslList<unhinged.common.Attachment, TrainingSamplesProxy>.add(value: unhinged.common.Attachment) {
      _builder.addTrainingSamples(value)
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Attachment training_samples = 3;`
     * @param value The trainingSamples to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTrainingSamples")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.common.Attachment, TrainingSamplesProxy>.plusAssign(value: unhinged.common.Attachment) {
      add(value)
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Attachment training_samples = 3;`
     * @param values The trainingSamples to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTrainingSamples")
    public fun com.google.protobuf.kotlin.DslList<unhinged.common.Attachment, TrainingSamplesProxy>.addAll(values: kotlin.collections.Iterable<unhinged.common.Attachment>) {
      _builder.addAllTrainingSamples(values)
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Attachment training_samples = 3;`
     * @param values The trainingSamples to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTrainingSamples")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.common.Attachment, TrainingSamplesProxy>.plusAssign(values: kotlin.collections.Iterable<unhinged.common.Attachment>) {
      addAll(values)
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Attachment training_samples = 3;`
     * @param index The index to set the value at.
     * @param value The trainingSamples to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTrainingSamples")
    public operator fun com.google.protobuf.kotlin.DslList<unhinged.common.Attachment, TrainingSamplesProxy>.set(index: kotlin.Int, value: unhinged.common.Attachment) {
      _builder.setTrainingSamples(index, value)
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Attachment training_samples = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTrainingSamples")
    public fun com.google.protobuf.kotlin.DslList<unhinged.common.Attachment, TrainingSamplesProxy>.clear() {
      _builder.clearTrainingSamples()
    }


    /**
     * `.unhinged.audio.v1.VoiceGender target_gender = 4;`
     */
    public var targetGender: unhinged.audio.VoiceGender
      @JvmName("getTargetGender")
      get() = _builder.getTargetGender()
      @JvmName("setTargetGender")
      set(value) {
        _builder.setTargetGender(value)
      }
    public var targetGenderValue: kotlin.Int
      @JvmName("getTargetGenderValue")
      get() = _builder.getTargetGenderValue()
      @JvmName("setTargetGenderValue")
      set(value) {
        _builder.setTargetGenderValue(value)
      }
    /**
     * `.unhinged.audio.v1.VoiceGender target_gender = 4;`
     */
    public fun clearTargetGender() {
      _builder.clearTargetGender()
    }

    /**
     * `.unhinged.audio.v1.VoiceStyle target_style = 5;`
     */
    public var targetStyle: unhinged.audio.VoiceStyle
      @JvmName("getTargetStyle")
      get() = _builder.getTargetStyle()
      @JvmName("setTargetStyle")
      set(value) {
        _builder.setTargetStyle(value)
      }
    public var targetStyleValue: kotlin.Int
      @JvmName("getTargetStyleValue")
      get() = _builder.getTargetStyleValue()
      @JvmName("setTargetStyleValue")
      set(value) {
        _builder.setTargetStyleValue(value)
      }
    /**
     * `.unhinged.audio.v1.VoiceStyle target_style = 5;`
     */
    public fun clearTargetStyle() {
      _builder.clearTargetStyle()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.CreateCustomVoiceRequest.copy(block: `unhinged.audio`.CreateCustomVoiceRequestKt.Dsl.() -> kotlin.Unit): unhinged.audio.CreateCustomVoiceRequest =
  `unhinged.audio`.CreateCustomVoiceRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

