// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializecreateCustomVoiceResponse")
public inline fun createCustomVoiceResponse(block: unhinged.audio.CreateCustomVoiceResponseKt.Dsl.() -> kotlin.Unit): unhinged.audio.CreateCustomVoiceResponse =
  unhinged.audio.CreateCustomVoiceResponseKt.Dsl._create(unhinged.audio.CreateCustomVoiceResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.audio.v1.CreateCustomVoiceResponse`
 */
public object CreateCustomVoiceResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.CreateCustomVoiceResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.CreateCustomVoiceResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.CreateCustomVoiceResponse = _builder.build()

    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     */
    public var response: unhinged.common.StandardResponse
      @JvmName("getResponse")
      get() = _builder.getResponse()
      @JvmName("setResponse")
      set(value) {
        _builder.setResponse(value)
      }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     */
    public fun clearResponse() {
      _builder.clearResponse()
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     * @return Whether the response field is set.
     */
    public fun hasResponse(): kotlin.Boolean {
      return _builder.hasResponse()
    }

    /**
     * `.unhinged.audio.v1.Voice voice = 2;`
     */
    public var voice: unhinged.audio.Voice
      @JvmName("getVoice")
      get() = _builder.getVoice()
      @JvmName("setVoice")
      set(value) {
        _builder.setVoice(value)
      }
    /**
     * `.unhinged.audio.v1.Voice voice = 2;`
     */
    public fun clearVoice() {
      _builder.clearVoice()
    }
    /**
     * `.unhinged.audio.v1.Voice voice = 2;`
     * @return Whether the voice field is set.
     */
    public fun hasVoice(): kotlin.Boolean {
      return _builder.hasVoice()
    }

    /**
     * ```
     * For tracking training progress
     * ```
     *
     * `string training_job_id = 3;`
     */
    public var trainingJobId: kotlin.String
      @JvmName("getTrainingJobId")
      get() = _builder.getTrainingJobId()
      @JvmName("setTrainingJobId")
      set(value) {
        _builder.setTrainingJobId(value)
      }
    /**
     * ```
     * For tracking training progress
     * ```
     *
     * `string training_job_id = 3;`
     */
    public fun clearTrainingJobId() {
      _builder.clearTrainingJobId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.CreateCustomVoiceResponse.copy(block: `unhinged.audio`.CreateCustomVoiceResponseKt.Dsl.() -> kotlin.Unit): unhinged.audio.CreateCustomVoiceResponse =
  `unhinged.audio`.CreateCustomVoiceResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.audio.CreateCustomVoiceResponseOrBuilder.responseOrNull: unhinged.common.StandardResponse?
  get() = if (hasResponse()) getResponse() else null

public val unhinged.audio.CreateCustomVoiceResponseOrBuilder.voiceOrNull: unhinged.audio.Voice?
  get() = if (hasVoice()) getVoice() else null

