// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializeemotionSegment")
public inline fun emotionSegment(block: unhinged.audio.EmotionSegmentKt.Dsl.() -> kotlin.Unit): unhinged.audio.EmotionSegment =
  unhinged.audio.EmotionSegmentKt.Dsl._create(unhinged.audio.EmotionSegment.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.audio.v1.EmotionSegment`
 */
public object EmotionSegmentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.EmotionSegment.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.EmotionSegment.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.EmotionSegment = _builder.build()

    /**
     * ```
     * "happy", "sad", "angry", "neutral", etc.
     * ```
     *
     * `string emotion = 1;`
     */
    public var emotion: kotlin.String
      @JvmName("getEmotion")
      get() = _builder.getEmotion()
      @JvmName("setEmotion")
      set(value) {
        _builder.setEmotion(value)
      }
    /**
     * ```
     * "happy", "sad", "angry", "neutral", etc.
     * ```
     *
     * `string emotion = 1;`
     */
    public fun clearEmotion() {
      _builder.clearEmotion()
    }

    /**
     * `float start_time = 2;`
     */
    public var startTime: kotlin.Float
      @JvmName("getStartTime")
      get() = _builder.getStartTime()
      @JvmName("setStartTime")
      set(value) {
        _builder.setStartTime(value)
      }
    /**
     * `float start_time = 2;`
     */
    public fun clearStartTime() {
      _builder.clearStartTime()
    }

    /**
     * `float end_time = 3;`
     */
    public var endTime: kotlin.Float
      @JvmName("getEndTime")
      get() = _builder.getEndTime()
      @JvmName("setEndTime")
      set(value) {
        _builder.setEndTime(value)
      }
    /**
     * `float end_time = 3;`
     */
    public fun clearEndTime() {
      _builder.clearEndTime()
    }

    /**
     * `float confidence = 4;`
     */
    public var confidence: kotlin.Float
      @JvmName("getConfidence")
      get() = _builder.getConfidence()
      @JvmName("setConfidence")
      set(value) {
        _builder.setConfidence(value)
      }
    /**
     * `float confidence = 4;`
     */
    public fun clearConfidence() {
      _builder.clearConfidence()
    }

    /**
     * ```
     * 0.0 to 1.0
     * ```
     *
     * `float intensity = 5;`
     */
    public var intensity: kotlin.Float
      @JvmName("getIntensity")
      get() = _builder.getIntensity()
      @JvmName("setIntensity")
      set(value) {
        _builder.setIntensity(value)
      }
    /**
     * ```
     * 0.0 to 1.0
     * ```
     *
     * `float intensity = 5;`
     */
    public fun clearIntensity() {
      _builder.clearIntensity()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.EmotionSegment.copy(block: `unhinged.audio`.EmotionSegmentKt.Dsl.() -> kotlin.Unit): unhinged.audio.EmotionSegment =
  `unhinged.audio`.EmotionSegmentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

