// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializegetVoiceResponse")
public inline fun getVoiceResponse(block: unhinged.audio.GetVoiceResponseKt.Dsl.() -> kotlin.Unit): unhinged.audio.GetVoiceResponse =
  unhinged.audio.GetVoiceResponseKt.Dsl._create(unhinged.audio.GetVoiceResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.audio.v1.GetVoiceResponse`
 */
public object GetVoiceResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.GetVoiceResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.GetVoiceResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.GetVoiceResponse = _builder.build()

    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     */
    public var response: unhinged.common.StandardResponse
      @JvmName("getResponse")
      get() = _builder.getResponse()
      @JvmName("setResponse")
      set(value) {
        _builder.setResponse(value)
      }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     */
    public fun clearResponse() {
      _builder.clearResponse()
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     * @return Whether the response field is set.
     */
    public fun hasResponse(): kotlin.Boolean {
      return _builder.hasResponse()
    }

    /**
     * `.unhinged.audio.v1.Voice voice = 2;`
     */
    public var voice: unhinged.audio.Voice
      @JvmName("getVoice")
      get() = _builder.getVoice()
      @JvmName("setVoice")
      set(value) {
        _builder.setVoice(value)
      }
    /**
     * `.unhinged.audio.v1.Voice voice = 2;`
     */
    public fun clearVoice() {
      _builder.clearVoice()
    }
    /**
     * `.unhinged.audio.v1.Voice voice = 2;`
     * @return Whether the voice field is set.
     */
    public fun hasVoice(): kotlin.Boolean {
      return _builder.hasVoice()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.GetVoiceResponse.copy(block: `unhinged.audio`.GetVoiceResponseKt.Dsl.() -> kotlin.Unit): unhinged.audio.GetVoiceResponse =
  `unhinged.audio`.GetVoiceResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.audio.GetVoiceResponseOrBuilder.responseOrNull: unhinged.common.StandardResponse?
  get() = if (hasResponse()) getResponse() else null

public val unhinged.audio.GetVoiceResponseOrBuilder.voiceOrNull: unhinged.audio.Voice?
  get() = if (hasVoice()) getVoice() else null

