// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializelistVoicesRequest")
public inline fun listVoicesRequest(block: unhinged.audio.ListVoicesRequestKt.Dsl.() -> kotlin.Unit): unhinged.audio.ListVoicesRequest =
  unhinged.audio.ListVoicesRequestKt.Dsl._create(unhinged.audio.ListVoicesRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.audio.v1.ListVoicesRequest`
 */
public object ListVoicesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.ListVoicesRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.ListVoicesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.ListVoicesRequest = _builder.build()

    /**
     * `string language = 1;`
     */
    public var language: kotlin.String
      @JvmName("getLanguage")
      get() = _builder.getLanguage()
      @JvmName("setLanguage")
      set(value) {
        _builder.setLanguage(value)
      }
    /**
     * `string language = 1;`
     */
    public fun clearLanguage() {
      _builder.clearLanguage()
    }

    /**
     * `.unhinged.audio.v1.VoiceGender gender = 2;`
     */
    public var gender: unhinged.audio.VoiceGender
      @JvmName("getGender")
      get() = _builder.getGender()
      @JvmName("setGender")
      set(value) {
        _builder.setGender(value)
      }
    public var genderValue: kotlin.Int
      @JvmName("getGenderValue")
      get() = _builder.getGenderValue()
      @JvmName("setGenderValue")
      set(value) {
        _builder.setGenderValue(value)
      }
    /**
     * `.unhinged.audio.v1.VoiceGender gender = 2;`
     */
    public fun clearGender() {
      _builder.clearGender()
    }

    /**
     * `.unhinged.audio.v1.VoiceStyle style = 3;`
     */
    public var style: unhinged.audio.VoiceStyle
      @JvmName("getStyle")
      get() = _builder.getStyle()
      @JvmName("setStyle")
      set(value) {
        _builder.setStyle(value)
      }
    public var styleValue: kotlin.Int
      @JvmName("getStyleValue")
      get() = _builder.getStyleValue()
      @JvmName("setStyleValue")
      set(value) {
        _builder.setStyleValue(value)
      }
    /**
     * `.unhinged.audio.v1.VoiceStyle style = 3;`
     */
    public fun clearStyle() {
      _builder.clearStyle()
    }

    /**
     * `bool premium_only = 4;`
     */
    public var premiumOnly: kotlin.Boolean
      @JvmName("getPremiumOnly")
      get() = _builder.getPremiumOnly()
      @JvmName("setPremiumOnly")
      set(value) {
        _builder.setPremiumOnly(value)
      }
    /**
     * `bool premium_only = 4;`
     */
    public fun clearPremiumOnly() {
      _builder.clearPremiumOnly()
    }

    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.PaginationRequest pagination = 5;`
     */
    public var pagination: unhinged.common.PaginationRequest
      @JvmName("getPagination")
      get() = _builder.getPagination()
      @JvmName("setPagination")
      set(value) {
        _builder.setPagination(value)
      }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.PaginationRequest pagination = 5;`
     */
    public fun clearPagination() {
      _builder.clearPagination()
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.PaginationRequest pagination = 5;`
     * @return Whether the pagination field is set.
     */
    public fun hasPagination(): kotlin.Boolean {
      return _builder.hasPagination()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FiltersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Filter filters = 6;`
     */
     public val filters: com.google.protobuf.kotlin.DslList<unhinged.common.Filter, FiltersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getFiltersList()
      )
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Filter filters = 6;`
     * @param value The filters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addFilters")
    public fun com.google.protobuf.kotlin.DslList<unhinged.common.Filter, FiltersProxy>.add(value: unhinged.common.Filter) {
      _builder.addFilters(value)
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Filter filters = 6;`
     * @param value The filters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignFilters")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.common.Filter, FiltersProxy>.plusAssign(value: unhinged.common.Filter) {
      add(value)
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Filter filters = 6;`
     * @param values The filters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllFilters")
    public fun com.google.protobuf.kotlin.DslList<unhinged.common.Filter, FiltersProxy>.addAll(values: kotlin.collections.Iterable<unhinged.common.Filter>) {
      _builder.addAllFilters(values)
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Filter filters = 6;`
     * @param values The filters to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllFilters")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.common.Filter, FiltersProxy>.plusAssign(values: kotlin.collections.Iterable<unhinged.common.Filter>) {
      addAll(values)
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Filter filters = 6;`
     * @param index The index to set the value at.
     * @param value The filters to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setFilters")
    public operator fun com.google.protobuf.kotlin.DslList<unhinged.common.Filter, FiltersProxy>.set(index: kotlin.Int, value: unhinged.common.Filter) {
      _builder.setFilters(index, value)
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `repeated .unhinged.common.v1.Filter filters = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearFilters")
    public fun com.google.protobuf.kotlin.DslList<unhinged.common.Filter, FiltersProxy>.clear() {
      _builder.clearFilters()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.ListVoicesRequest.copy(block: `unhinged.audio`.ListVoicesRequestKt.Dsl.() -> kotlin.Unit): unhinged.audio.ListVoicesRequest =
  `unhinged.audio`.ListVoicesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.audio.ListVoicesRequestOrBuilder.paginationOrNull: unhinged.common.PaginationRequest?
  get() = if (hasPagination()) getPagination() else null

