// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializeprocessAudioResponse")
public inline fun processAudioResponse(block: unhinged.audio.ProcessAudioResponseKt.Dsl.() -> kotlin.Unit): unhinged.audio.ProcessAudioResponse =
  unhinged.audio.ProcessAudioResponseKt.Dsl._create(unhinged.audio.ProcessAudioResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.audio.v1.ProcessAudioResponse`
 */
public object ProcessAudioResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.ProcessAudioResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.ProcessAudioResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.ProcessAudioResponse = _builder.build()

    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     */
    public var response: unhinged.common.StandardResponse
      @JvmName("getResponse")
      get() = _builder.getResponse()
      @JvmName("setResponse")
      set(value) {
        _builder.setResponse(value)
      }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     */
    public fun clearResponse() {
      _builder.clearResponse()
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     * @return Whether the response field is set.
     */
    public fun hasResponse(): kotlin.Boolean {
      return _builder.hasResponse()
    }

    /**
     * ```
     * For transcription
     * ```
     *
     * `string transcript = 2;`
     */
    public var transcript: kotlin.String
      @JvmName("getTranscript")
      get() = _builder.getTranscript()
      @JvmName("setTranscript")
      set(value) {
        _builder.setTranscript(value)
      }
    /**
     * ```
     * For transcription
     * ```
     *
     * `string transcript = 2;`
     */
    public fun clearTranscript() {
      _builder.clearTranscript()
    }
    /**
     * ```
     * For transcription
     * ```
     *
     * `string transcript = 2;`
     * @return Whether the transcript field is set.
     */
    public fun hasTranscript(): kotlin.Boolean {
      return _builder.hasTranscript()
    }

    /**
     * ```
     * For translation
     * ```
     *
     * `string translation = 3;`
     */
    public var translation: kotlin.String
      @JvmName("getTranslation")
      get() = _builder.getTranslation()
      @JvmName("setTranslation")
      set(value) {
        _builder.setTranslation(value)
      }
    /**
     * ```
     * For translation
     * ```
     *
     * `string translation = 3;`
     */
    public fun clearTranslation() {
      _builder.clearTranslation()
    }
    /**
     * ```
     * For translation
     * ```
     *
     * `string translation = 3;`
     * @return Whether the translation field is set.
     */
    public fun hasTranslation(): kotlin.Boolean {
      return _builder.hasTranslation()
    }

    /**
     * ```
     * ← DRY! For enhancement
     * ```
     *
     * `.unhinged.common.v1.Attachment enhanced_audio = 4;`
     */
    public var enhancedAudio: unhinged.common.Attachment
      @JvmName("getEnhancedAudio")
      get() = _builder.getEnhancedAudio()
      @JvmName("setEnhancedAudio")
      set(value) {
        _builder.setEnhancedAudio(value)
      }
    /**
     * ```
     * ← DRY! For enhancement
     * ```
     *
     * `.unhinged.common.v1.Attachment enhanced_audio = 4;`
     */
    public fun clearEnhancedAudio() {
      _builder.clearEnhancedAudio()
    }
    /**
     * ```
     * ← DRY! For enhancement
     * ```
     *
     * `.unhinged.common.v1.Attachment enhanced_audio = 4;`
     * @return Whether the enhancedAudio field is set.
     */
    public fun hasEnhancedAudio(): kotlin.Boolean {
      return _builder.hasEnhancedAudio()
    }

    /**
     * ```
     * ← DRY! For conversion
     * ```
     *
     * `.unhinged.common.v1.Attachment converted_audio = 5;`
     */
    public var convertedAudio: unhinged.common.Attachment
      @JvmName("getConvertedAudio")
      get() = _builder.getConvertedAudio()
      @JvmName("setConvertedAudio")
      set(value) {
        _builder.setConvertedAudio(value)
      }
    /**
     * ```
     * ← DRY! For conversion
     * ```
     *
     * `.unhinged.common.v1.Attachment converted_audio = 5;`
     */
    public fun clearConvertedAudio() {
      _builder.clearConvertedAudio()
    }
    /**
     * ```
     * ← DRY! For conversion
     * ```
     *
     * `.unhinged.common.v1.Attachment converted_audio = 5;`
     * @return Whether the convertedAudio field is set.
     */
    public fun hasConvertedAudio(): kotlin.Boolean {
      return _builder.hasConvertedAudio()
    }

    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.AudioUsage usage = 6;`
     */
    public var usage: unhinged.common.AudioUsage
      @JvmName("getUsage")
      get() = _builder.getUsage()
      @JvmName("setUsage")
      set(value) {
        _builder.setUsage(value)
      }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.AudioUsage usage = 6;`
     */
    public fun clearUsage() {
      _builder.clearUsage()
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.AudioUsage usage = 6;`
     * @return Whether the usage field is set.
     */
    public fun hasUsage(): kotlin.Boolean {
      return _builder.hasUsage()
    }
    public val resultCase: unhinged.audio.ProcessAudioResponse.ResultCase
      @JvmName("getResultCase")
      get() = _builder.getResultCase()

    public fun clearResult() {
      _builder.clearResult()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.ProcessAudioResponse.copy(block: `unhinged.audio`.ProcessAudioResponseKt.Dsl.() -> kotlin.Unit): unhinged.audio.ProcessAudioResponse =
  `unhinged.audio`.ProcessAudioResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.audio.ProcessAudioResponseOrBuilder.responseOrNull: unhinged.common.StandardResponse?
  get() = if (hasResponse()) getResponse() else null

public val unhinged.audio.ProcessAudioResponseOrBuilder.enhancedAudioOrNull: unhinged.common.Attachment?
  get() = if (hasEnhancedAudio()) getEnhancedAudio() else null

public val unhinged.audio.ProcessAudioResponseOrBuilder.convertedAudioOrNull: unhinged.common.Attachment?
  get() = if (hasConvertedAudio()) getConvertedAudio() else null

public val unhinged.audio.ProcessAudioResponseOrBuilder.usageOrNull: unhinged.common.AudioUsage?
  get() = if (hasUsage()) getUsage() else null

