// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializespeakerSegment")
public inline fun speakerSegment(block: unhinged.audio.SpeakerSegmentKt.Dsl.() -> kotlin.Unit): unhinged.audio.SpeakerSegment =
  unhinged.audio.SpeakerSegmentKt.Dsl._create(unhinged.audio.SpeakerSegment.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.audio.v1.SpeakerSegment`
 */
public object SpeakerSegmentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.SpeakerSegment.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.SpeakerSegment.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.SpeakerSegment = _builder.build()

    /**
     * `string speaker_id = 1;`
     */
    public var speakerId: kotlin.String
      @JvmName("getSpeakerId")
      get() = _builder.getSpeakerId()
      @JvmName("setSpeakerId")
      set(value) {
        _builder.setSpeakerId(value)
      }
    /**
     * `string speaker_id = 1;`
     */
    public fun clearSpeakerId() {
      _builder.clearSpeakerId()
    }

    /**
     * `float start_time = 2;`
     */
    public var startTime: kotlin.Float
      @JvmName("getStartTime")
      get() = _builder.getStartTime()
      @JvmName("setStartTime")
      set(value) {
        _builder.setStartTime(value)
      }
    /**
     * `float start_time = 2;`
     */
    public fun clearStartTime() {
      _builder.clearStartTime()
    }

    /**
     * `float end_time = 3;`
     */
    public var endTime: kotlin.Float
      @JvmName("getEndTime")
      get() = _builder.getEndTime()
      @JvmName("setEndTime")
      set(value) {
        _builder.setEndTime(value)
      }
    /**
     * `float end_time = 3;`
     */
    public fun clearEndTime() {
      _builder.clearEndTime()
    }

    /**
     * `float confidence = 4;`
     */
    public var confidence: kotlin.Float
      @JvmName("getConfidence")
      get() = _builder.getConfidence()
      @JvmName("setConfidence")
      set(value) {
        _builder.setConfidence(value)
      }
    /**
     * `float confidence = 4;`
     */
    public fun clearConfidence() {
      _builder.clearConfidence()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.SpeakerSegment.copy(block: `unhinged.audio`.SpeakerSegmentKt.Dsl.() -> kotlin.Unit): unhinged.audio.SpeakerSegment =
  `unhinged.audio`.SpeakerSegmentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

