// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializesTTMetadata")
public inline fun sTTMetadata(block: unhinged.audio.STTMetadataKt.Dsl.() -> kotlin.Unit): unhinged.audio.STTMetadata =
  unhinged.audio.STTMetadataKt.Dsl._create(unhinged.audio.STTMetadata.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * STT processing metadata
 * ```
 *
 * Protobuf type `unhinged.audio.v1.STTMetadata`
 */
public object STTMetadataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.STTMetadata.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.STTMetadata.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.STTMetadata = _builder.build()

    /**
     * `string model = 1;`
     */
    public var model: kotlin.String
      @JvmName("getModel")
      get() = _builder.getModel()
      @JvmName("setModel")
      set(value) {
        _builder.setModel(value)
      }
    /**
     * `string model = 1;`
     */
    public fun clearModel() {
      _builder.clearModel()
    }

    /**
     * ```
     * Detected or specified language
     * ```
     *
     * `string language = 2;`
     */
    public var language: kotlin.String
      @JvmName("getLanguage")
      get() = _builder.getLanguage()
      @JvmName("setLanguage")
      set(value) {
        _builder.setLanguage(value)
      }
    /**
     * ```
     * Detected or specified language
     * ```
     *
     * `string language = 2;`
     */
    public fun clearLanguage() {
      _builder.clearLanguage()
    }

    /**
     * `float processing_time_ms = 3;`
     */
    public var processingTimeMs: kotlin.Float
      @JvmName("getProcessingTimeMs")
      get() = _builder.getProcessingTimeMs()
      @JvmName("setProcessingTimeMs")
      set(value) {
        _builder.setProcessingTimeMs(value)
      }
    /**
     * `float processing_time_ms = 3;`
     */
    public fun clearProcessingTimeMs() {
      _builder.clearProcessingTimeMs()
    }

    /**
     * ```
     * Audio analysis
     * ```
     *
     * `float signal_to_noise_ratio = 4;`
     */
    public var signalToNoiseRatio: kotlin.Float
      @JvmName("getSignalToNoiseRatio")
      get() = _builder.getSignalToNoiseRatio()
      @JvmName("setSignalToNoiseRatio")
      set(value) {
        _builder.setSignalToNoiseRatio(value)
      }
    /**
     * ```
     * Audio analysis
     * ```
     *
     * `float signal_to_noise_ratio = 4;`
     */
    public fun clearSignalToNoiseRatio() {
      _builder.clearSignalToNoiseRatio()
    }

    /**
     * ```
     * Words per minute
     * ```
     *
     * `float speech_rate_wpm = 5;`
     */
    public var speechRateWpm: kotlin.Float
      @JvmName("getSpeechRateWpm")
      get() = _builder.getSpeechRateWpm()
      @JvmName("setSpeechRateWpm")
      set(value) {
        _builder.setSpeechRateWpm(value)
      }
    /**
     * ```
     * Words per minute
     * ```
     *
     * `float speech_rate_wpm = 5;`
     */
    public fun clearSpeechRateWpm() {
      _builder.clearSpeechRateWpm()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DetectedLanguagesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string detected_languages = 6;`
     * @return A list containing the detectedLanguages.
     */
    public val detectedLanguages: com.google.protobuf.kotlin.DslList<kotlin.String, DetectedLanguagesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getDetectedLanguagesList()
      )
    /**
     * `repeated string detected_languages = 6;`
     * @param value The detectedLanguages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addDetectedLanguages")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, DetectedLanguagesProxy>.add(value: kotlin.String) {
      _builder.addDetectedLanguages(value)
    }
    /**
     * `repeated string detected_languages = 6;`
     * @param value The detectedLanguages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignDetectedLanguages")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, DetectedLanguagesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string detected_languages = 6;`
     * @param values The detectedLanguages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllDetectedLanguages")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, DetectedLanguagesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllDetectedLanguages(values)
    }
    /**
     * `repeated string detected_languages = 6;`
     * @param values The detectedLanguages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllDetectedLanguages")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, DetectedLanguagesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string detected_languages = 6;`
     * @param index The index to set the value at.
     * @param value The detectedLanguages to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setDetectedLanguages")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, DetectedLanguagesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setDetectedLanguages(index, value)
    }/**
     * `repeated string detected_languages = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearDetectedLanguages")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, DetectedLanguagesProxy>.clear() {
      _builder.clearDetectedLanguages()
    }
    /**
     * ```
     * Quality metrics
     * ```
     *
     * `bool has_background_noise = 7;`
     */
    public var hasBackgroundNoise: kotlin.Boolean
      @JvmName("getHasBackgroundNoise")
      get() = _builder.getHasBackgroundNoise()
      @JvmName("setHasBackgroundNoise")
      set(value) {
        _builder.setHasBackgroundNoise(value)
      }
    /**
     * ```
     * Quality metrics
     * ```
     *
     * `bool has_background_noise = 7;`
     */
    public fun clearHasBackgroundNoise() {
      _builder.clearHasBackgroundNoise()
    }

    /**
     * `bool has_multiple_speakers = 8;`
     */
    public var hasMultipleSpeakers: kotlin.Boolean
      @JvmName("getHasMultipleSpeakers")
      get() = _builder.getHasMultipleSpeakers()
      @JvmName("setHasMultipleSpeakers")
      set(value) {
        _builder.setHasMultipleSpeakers(value)
      }
    /**
     * `bool has_multiple_speakers = 8;`
     */
    public fun clearHasMultipleSpeakers() {
      _builder.clearHasMultipleSpeakers()
    }

    /**
     * `.unhinged.audio.v1.AudioQuality detected_quality = 9;`
     */
    public var detectedQuality: unhinged.audio.AudioQuality
      @JvmName("getDetectedQuality")
      get() = _builder.getDetectedQuality()
      @JvmName("setDetectedQuality")
      set(value) {
        _builder.setDetectedQuality(value)
      }
    public var detectedQualityValue: kotlin.Int
      @JvmName("getDetectedQualityValue")
      get() = _builder.getDetectedQualityValue()
      @JvmName("setDetectedQualityValue")
      set(value) {
        _builder.setDetectedQualityValue(value)
      }
    /**
     * `.unhinged.audio.v1.AudioQuality detected_quality = 9;`
     */
    public fun clearDetectedQuality() {
      _builder.clearDetectedQuality()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.STTMetadata.copy(block: `unhinged.audio`.STTMetadataKt.Dsl.() -> kotlin.Unit): unhinged.audio.STTMetadata =
  `unhinged.audio`.STTMetadataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

