// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializesTTResponse")
public inline fun sTTResponse(block: unhinged.audio.STTResponseKt.Dsl.() -> kotlin.Unit): unhinged.audio.STTResponse =
  unhinged.audio.STTResponseKt.Dsl._create(unhinged.audio.STTResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Speech-to-Text response
 * ```
 *
 * Protobuf type `unhinged.audio.v1.STTResponse`
 */
public object STTResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.STTResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.STTResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.STTResponse = _builder.build()

    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     */
    public var response: unhinged.common.StandardResponse
      @JvmName("getResponse")
      get() = _builder.getResponse()
      @JvmName("setResponse")
      set(value) {
        _builder.setResponse(value)
      }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     */
    public fun clearResponse() {
      _builder.clearResponse()
    }
    /**
     * ```
     * ← DRY!
     * ```
     *
     * `.unhinged.common.v1.StandardResponse response = 1;`
     * @return Whether the response field is set.
     */
    public fun hasResponse(): kotlin.Boolean {
      return _builder.hasResponse()
    }

    /**
     * `string transcript = 2;`
     */
    public var transcript: kotlin.String
      @JvmName("getTranscript")
      get() = _builder.getTranscript()
      @JvmName("setTranscript")
      set(value) {
        _builder.setTranscript(value)
      }
    /**
     * `string transcript = 2;`
     */
    public fun clearTranscript() {
      _builder.clearTranscript()
    }

    /**
     * `float confidence = 3;`
     */
    public var confidence: kotlin.Float
      @JvmName("getConfidence")
      get() = _builder.getConfidence()
      @JvmName("setConfidence")
      set(value) {
        _builder.setConfidence(value)
      }
    /**
     * `float confidence = 3;`
     */
    public fun clearConfidence() {
      _builder.clearConfidence()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SegmentsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .unhinged.audio.v1.TranscriptSegment segments = 4;`
     */
     public val segments: com.google.protobuf.kotlin.DslList<unhinged.audio.TranscriptSegment, SegmentsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSegmentsList()
      )
    /**
     * `repeated .unhinged.audio.v1.TranscriptSegment segments = 4;`
     * @param value The segments to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSegments")
    public fun com.google.protobuf.kotlin.DslList<unhinged.audio.TranscriptSegment, SegmentsProxy>.add(value: unhinged.audio.TranscriptSegment) {
      _builder.addSegments(value)
    }
    /**
     * `repeated .unhinged.audio.v1.TranscriptSegment segments = 4;`
     * @param value The segments to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSegments")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.audio.TranscriptSegment, SegmentsProxy>.plusAssign(value: unhinged.audio.TranscriptSegment) {
      add(value)
    }
    /**
     * `repeated .unhinged.audio.v1.TranscriptSegment segments = 4;`
     * @param values The segments to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSegments")
    public fun com.google.protobuf.kotlin.DslList<unhinged.audio.TranscriptSegment, SegmentsProxy>.addAll(values: kotlin.collections.Iterable<unhinged.audio.TranscriptSegment>) {
      _builder.addAllSegments(values)
    }
    /**
     * `repeated .unhinged.audio.v1.TranscriptSegment segments = 4;`
     * @param values The segments to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSegments")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.audio.TranscriptSegment, SegmentsProxy>.plusAssign(values: kotlin.collections.Iterable<unhinged.audio.TranscriptSegment>) {
      addAll(values)
    }
    /**
     * `repeated .unhinged.audio.v1.TranscriptSegment segments = 4;`
     * @param index The index to set the value at.
     * @param value The segments to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSegments")
    public operator fun com.google.protobuf.kotlin.DslList<unhinged.audio.TranscriptSegment, SegmentsProxy>.set(index: kotlin.Int, value: unhinged.audio.TranscriptSegment) {
      _builder.setSegments(index, value)
    }
    /**
     * `repeated .unhinged.audio.v1.TranscriptSegment segments = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSegments")
    public fun com.google.protobuf.kotlin.DslList<unhinged.audio.TranscriptSegment, SegmentsProxy>.clear() {
      _builder.clearSegments()
    }


    /**
     * ```
     * ← DRY! (duration, bytes, etc.)
     * ```
     *
     * `.unhinged.common.v1.AudioUsage usage = 5;`
     */
    public var usage: unhinged.common.AudioUsage
      @JvmName("getUsage")
      get() = _builder.getUsage()
      @JvmName("setUsage")
      set(value) {
        _builder.setUsage(value)
      }
    /**
     * ```
     * ← DRY! (duration, bytes, etc.)
     * ```
     *
     * `.unhinged.common.v1.AudioUsage usage = 5;`
     */
    public fun clearUsage() {
      _builder.clearUsage()
    }
    /**
     * ```
     * ← DRY! (duration, bytes, etc.)
     * ```
     *
     * `.unhinged.common.v1.AudioUsage usage = 5;`
     * @return Whether the usage field is set.
     */
    public fun hasUsage(): kotlin.Boolean {
      return _builder.hasUsage()
    }

    /**
     * `.unhinged.audio.v1.STTMetadata metadata = 6;`
     */
    public var metadata: unhinged.audio.STTMetadata
      @JvmName("getMetadata")
      get() = _builder.getMetadata()
      @JvmName("setMetadata")
      set(value) {
        _builder.setMetadata(value)
      }
    /**
     * `.unhinged.audio.v1.STTMetadata metadata = 6;`
     */
    public fun clearMetadata() {
      _builder.clearMetadata()
    }
    /**
     * `.unhinged.audio.v1.STTMetadata metadata = 6;`
     * @return Whether the metadata field is set.
     */
    public fun hasMetadata(): kotlin.Boolean {
      return _builder.hasMetadata()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.STTResponse.copy(block: `unhinged.audio`.STTResponseKt.Dsl.() -> kotlin.Unit): unhinged.audio.STTResponse =
  `unhinged.audio`.STTResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.audio.STTResponseOrBuilder.responseOrNull: unhinged.common.StandardResponse?
  get() = if (hasResponse()) getResponse() else null

public val unhinged.audio.STTResponseOrBuilder.usageOrNull: unhinged.common.AudioUsage?
  get() = if (hasUsage()) getUsage() else null

public val unhinged.audio.STTResponseOrBuilder.metadataOrNull: unhinged.audio.STTMetadata?
  get() = if (hasMetadata()) getMetadata() else null

