// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializetranscriptSegment")
public inline fun transcriptSegment(block: unhinged.audio.TranscriptSegmentKt.Dsl.() -> kotlin.Unit): unhinged.audio.TranscriptSegment =
  unhinged.audio.TranscriptSegmentKt.Dsl._create(unhinged.audio.TranscriptSegment.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Transcript segment with timing information
 * ```
 *
 * Protobuf type `unhinged.audio.v1.TranscriptSegment`
 */
public object TranscriptSegmentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.TranscriptSegment.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.TranscriptSegment.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.TranscriptSegment = _builder.build()

    /**
     * `string text = 1;`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * `string text = 1;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * ```
     * Seconds from start
     * ```
     *
     * `float start_time = 2;`
     */
    public var startTime: kotlin.Float
      @JvmName("getStartTime")
      get() = _builder.getStartTime()
      @JvmName("setStartTime")
      set(value) {
        _builder.setStartTime(value)
      }
    /**
     * ```
     * Seconds from start
     * ```
     *
     * `float start_time = 2;`
     */
    public fun clearStartTime() {
      _builder.clearStartTime()
    }

    /**
     * ```
     * Seconds from start
     * ```
     *
     * `float end_time = 3;`
     */
    public var endTime: kotlin.Float
      @JvmName("getEndTime")
      get() = _builder.getEndTime()
      @JvmName("setEndTime")
      set(value) {
        _builder.setEndTime(value)
      }
    /**
     * ```
     * Seconds from start
     * ```
     *
     * `float end_time = 3;`
     */
    public fun clearEndTime() {
      _builder.clearEndTime()
    }

    /**
     * ```
     * 0.0 to 1.0
     * ```
     *
     * `float confidence = 4;`
     */
    public var confidence: kotlin.Float
      @JvmName("getConfidence")
      get() = _builder.getConfidence()
      @JvmName("setConfidence")
      set(value) {
        _builder.setConfidence(value)
      }
    /**
     * ```
     * 0.0 to 1.0
     * ```
     *
     * `float confidence = 4;`
     */
    public fun clearConfidence() {
      _builder.clearConfidence()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class WordsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Word-level timing (optional)
     * ```
     *
     * `repeated .unhinged.audio.v1.WordTiming words = 5;`
     */
     public val words: com.google.protobuf.kotlin.DslList<unhinged.audio.WordTiming, WordsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getWordsList()
      )
    /**
     * ```
     * Word-level timing (optional)
     * ```
     *
     * `repeated .unhinged.audio.v1.WordTiming words = 5;`
     * @param value The words to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addWords")
    public fun com.google.protobuf.kotlin.DslList<unhinged.audio.WordTiming, WordsProxy>.add(value: unhinged.audio.WordTiming) {
      _builder.addWords(value)
    }
    /**
     * ```
     * Word-level timing (optional)
     * ```
     *
     * `repeated .unhinged.audio.v1.WordTiming words = 5;`
     * @param value The words to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignWords")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.audio.WordTiming, WordsProxy>.plusAssign(value: unhinged.audio.WordTiming) {
      add(value)
    }
    /**
     * ```
     * Word-level timing (optional)
     * ```
     *
     * `repeated .unhinged.audio.v1.WordTiming words = 5;`
     * @param values The words to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllWords")
    public fun com.google.protobuf.kotlin.DslList<unhinged.audio.WordTiming, WordsProxy>.addAll(values: kotlin.collections.Iterable<unhinged.audio.WordTiming>) {
      _builder.addAllWords(values)
    }
    /**
     * ```
     * Word-level timing (optional)
     * ```
     *
     * `repeated .unhinged.audio.v1.WordTiming words = 5;`
     * @param values The words to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllWords")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.audio.WordTiming, WordsProxy>.plusAssign(values: kotlin.collections.Iterable<unhinged.audio.WordTiming>) {
      addAll(values)
    }
    /**
     * ```
     * Word-level timing (optional)
     * ```
     *
     * `repeated .unhinged.audio.v1.WordTiming words = 5;`
     * @param index The index to set the value at.
     * @param value The words to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setWords")
    public operator fun com.google.protobuf.kotlin.DslList<unhinged.audio.WordTiming, WordsProxy>.set(index: kotlin.Int, value: unhinged.audio.WordTiming) {
      _builder.setWords(index, value)
    }
    /**
     * ```
     * Word-level timing (optional)
     * ```
     *
     * `repeated .unhinged.audio.v1.WordTiming words = 5;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearWords")
    public fun com.google.protobuf.kotlin.DslList<unhinged.audio.WordTiming, WordsProxy>.clear() {
      _builder.clearWords()
    }


    /**
     * ```
     * Speaker identification (if available)
     * ```
     *
     * `string speaker_id = 6;`
     */
    public var speakerId: kotlin.String
      @JvmName("getSpeakerId")
      get() = _builder.getSpeakerId()
      @JvmName("setSpeakerId")
      set(value) {
        _builder.setSpeakerId(value)
      }
    /**
     * ```
     * Speaker identification (if available)
     * ```
     *
     * `string speaker_id = 6;`
     */
    public fun clearSpeakerId() {
      _builder.clearSpeakerId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.TranscriptSegment.copy(block: `unhinged.audio`.TranscriptSegmentKt.Dsl.() -> kotlin.Unit): unhinged.audio.TranscriptSegment =
  `unhinged.audio`.TranscriptSegmentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

