// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializetTSChunkPayload")
public inline fun tTSChunkPayload(block: unhinged.audio.TTSChunkPayloadKt.Dsl.() -> kotlin.Unit): unhinged.audio.TTSChunkPayload =
  unhinged.audio.TTSChunkPayloadKt.Dsl._create(unhinged.audio.TTSChunkPayload.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * TTS audio chunk payload
 * Used with common.v1.StreamChunk.data field for binary audio
 * ```
 *
 * Protobuf type `unhinged.audio.v1.TTSChunkPayload`
 */
public object TTSChunkPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.TTSChunkPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.TTSChunkPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.TTSChunkPayload = _builder.build()

    /**
     * `string tts_id = 1;`
     */
    public var ttsId: kotlin.String
      @JvmName("getTtsId")
      get() = _builder.getTtsId()
      @JvmName("setTtsId")
      set(value) {
        _builder.setTtsId(value)
      }
    /**
     * `string tts_id = 1;`
     */
    public fun clearTtsId() {
      _builder.clearTtsId()
    }

    /**
     * `.unhinged.audio.v1.AudioMetadata audio_metadata = 2;`
     */
    public var audioMetadata: unhinged.audio.AudioMetadata
      @JvmName("getAudioMetadata")
      get() = _builder.getAudioMetadata()
      @JvmName("setAudioMetadata")
      set(value) {
        _builder.setAudioMetadata(value)
      }
    /**
     * `.unhinged.audio.v1.AudioMetadata audio_metadata = 2;`
     */
    public fun clearAudioMetadata() {
      _builder.clearAudioMetadata()
    }
    /**
     * `.unhinged.audio.v1.AudioMetadata audio_metadata = 2;`
     * @return Whether the audioMetadata field is set.
     */
    public fun hasAudioMetadata(): kotlin.Boolean {
      return _builder.hasAudioMetadata()
    }

    /**
     * `int32 chunk_index = 3;`
     */
    public var chunkIndex: kotlin.Int
      @JvmName("getChunkIndex")
      get() = _builder.getChunkIndex()
      @JvmName("setChunkIndex")
      set(value) {
        _builder.setChunkIndex(value)
      }
    /**
     * `int32 chunk_index = 3;`
     */
    public fun clearChunkIndex() {
      _builder.clearChunkIndex()
    }

    /**
     * ```
     * 0.0 to 100.0
     * ```
     *
     * `float progress_percent = 4;`
     */
    public var progressPercent: kotlin.Float
      @JvmName("getProgressPercent")
      get() = _builder.getProgressPercent()
      @JvmName("setProgressPercent")
      set(value) {
        _builder.setProgressPercent(value)
      }
    /**
     * ```
     * 0.0 to 100.0
     * ```
     *
     * `float progress_percent = 4;`
     */
    public fun clearProgressPercent() {
      _builder.clearProgressPercent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.TTSChunkPayload.copy(block: `unhinged.audio`.TTSChunkPayloadKt.Dsl.() -> kotlin.Unit): unhinged.audio.TTSChunkPayload =
  `unhinged.audio`.TTSChunkPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.audio.TTSChunkPayloadOrBuilder.audioMetadataOrNull: unhinged.audio.AudioMetadata?
  get() = if (hasAudioMetadata()) getAudioMetadata() else null

