// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: audio.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.audio;

@kotlin.jvm.JvmName("-initializewordTiming")
public inline fun wordTiming(block: unhinged.audio.WordTimingKt.Dsl.() -> kotlin.Unit): unhinged.audio.WordTiming =
  unhinged.audio.WordTimingKt.Dsl._create(unhinged.audio.WordTiming.newBuilder()).apply { block() }._build()
/**
 * ```
 **
 * Word-level timing information
 * ```
 *
 * Protobuf type `unhinged.audio.v1.WordTiming`
 */
public object WordTimingKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.audio.WordTiming.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.audio.WordTiming.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.audio.WordTiming = _builder.build()

    /**
     * `string word = 1;`
     */
    public var word: kotlin.String
      @JvmName("getWord")
      get() = _builder.getWord()
      @JvmName("setWord")
      set(value) {
        _builder.setWord(value)
      }
    /**
     * `string word = 1;`
     */
    public fun clearWord() {
      _builder.clearWord()
    }

    /**
     * `float start_time = 2;`
     */
    public var startTime: kotlin.Float
      @JvmName("getStartTime")
      get() = _builder.getStartTime()
      @JvmName("setStartTime")
      set(value) {
        _builder.setStartTime(value)
      }
    /**
     * `float start_time = 2;`
     */
    public fun clearStartTime() {
      _builder.clearStartTime()
    }

    /**
     * `float end_time = 3;`
     */
    public var endTime: kotlin.Float
      @JvmName("getEndTime")
      get() = _builder.getEndTime()
      @JvmName("setEndTime")
      set(value) {
        _builder.setEndTime(value)
      }
    /**
     * `float end_time = 3;`
     */
    public fun clearEndTime() {
      _builder.clearEndTime()
    }

    /**
     * `float confidence = 4;`
     */
    public var confidence: kotlin.Float
      @JvmName("getConfidence")
      get() = _builder.getConfidence()
      @JvmName("setConfidence")
      set(value) {
        _builder.setConfidence(value)
      }
    /**
     * `float confidence = 4;`
     */
    public fun clearConfidence() {
      _builder.clearConfidence()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.audio.WordTiming.copy(block: `unhinged.audio`.WordTimingKt.Dsl.() -> kotlin.Unit): unhinged.audio.WordTiming =
  `unhinged.audio`.WordTimingKt.Dsl._create(this.toBuilder()).apply { block() }._build()

