[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unhinged-proto-clients"
version = "1.0.0"
description = "Generated Python protobuf clients for Unhinged platform"
authors = [{name = "Unhinged Team", email = "team@unhinged.dev"}]
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "grpcio>=1.50.0",
    "grpcio-tools>=1.50.0",
    "protobuf>=4.21.0",
]
keywords = ["protobuf", "grpc", "unhinged"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://github.com/unhinged/proto-clients"
Repository = "https://github.com/unhinged/proto-clients.git"
