// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messaging.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.messaging;

@kotlin.jvm.JvmName("-initializeagentTaskRequest")
public inline fun agentTaskRequest(block: unhinged.messaging.AgentTaskRequestKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.AgentTaskRequest =
  unhinged.messaging.AgentTaskRequestKt.Dsl._create(unhinged.messaging.Messaging.AgentTaskRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.messaging.AgentTaskRequest`
 */
public object AgentTaskRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.messaging.Messaging.AgentTaskRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.messaging.Messaging.AgentTaskRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.messaging.Messaging.AgentTaskRequest = _builder.build()

    /**
     * `string task_description = 1;`
     */
    public var taskDescription: kotlin.String
      @JvmName("getTaskDescription")
      get() = _builder.getTaskDescription()
      @JvmName("setTaskDescription")
      set(value) {
        _builder.setTaskDescription(value)
      }
    /**
     * `string task_description = 1;`
     */
    public fun clearTaskDescription() {
      _builder.clearTaskDescription()
    }

    /**
     * `string task_type = 2;`
     */
    public var taskType: kotlin.String
      @JvmName("getTaskType")
      get() = _builder.getTaskType()
      @JvmName("setTaskType")
      set(value) {
        _builder.setTaskType(value)
      }
    /**
     * `string task_type = 2;`
     */
    public fun clearTaskType() {
      _builder.clearTaskType()
    }

    /**
     * `.google.protobuf.Struct task_parameters = 3;`
     */
    public var taskParameters: com.google.protobuf.Struct
      @JvmName("getTaskParameters")
      get() = _builder.getTaskParameters()
      @JvmName("setTaskParameters")
      set(value) {
        _builder.setTaskParameters(value)
      }
    /**
     * `.google.protobuf.Struct task_parameters = 3;`
     */
    public fun clearTaskParameters() {
      _builder.clearTaskParameters()
    }
    /**
     * `.google.protobuf.Struct task_parameters = 3;`
     * @return Whether the taskParameters field is set.
     */
    public fun hasTaskParameters(): kotlin.Boolean {
      return _builder.hasTaskParameters()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RequiredCapabilitiesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string required_capabilities = 4;`
     * @return A list containing the requiredCapabilities.
     */
    public val requiredCapabilities: com.google.protobuf.kotlin.DslList<kotlin.String, RequiredCapabilitiesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRequiredCapabilitiesList()
      )
    /**
     * `repeated string required_capabilities = 4;`
     * @param value The requiredCapabilities to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRequiredCapabilities")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RequiredCapabilitiesProxy>.add(value: kotlin.String) {
      _builder.addRequiredCapabilities(value)
    }
    /**
     * `repeated string required_capabilities = 4;`
     * @param value The requiredCapabilities to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRequiredCapabilities")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RequiredCapabilitiesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string required_capabilities = 4;`
     * @param values The requiredCapabilities to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRequiredCapabilities")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RequiredCapabilitiesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllRequiredCapabilities(values)
    }
    /**
     * `repeated string required_capabilities = 4;`
     * @param values The requiredCapabilities to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRequiredCapabilities")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RequiredCapabilitiesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string required_capabilities = 4;`
     * @param index The index to set the value at.
     * @param value The requiredCapabilities to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRequiredCapabilities")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RequiredCapabilitiesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setRequiredCapabilities(index, value)
    }/**
     * `repeated string required_capabilities = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRequiredCapabilities")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RequiredCapabilitiesProxy>.clear() {
      _builder.clearRequiredCapabilities()
    }
    /**
     * `.google.protobuf.Struct context = 5;`
     */
    public var context: com.google.protobuf.Struct
      @JvmName("getContext")
      get() = _builder.getContext()
      @JvmName("setContext")
      set(value) {
        _builder.setContext(value)
      }
    /**
     * `.google.protobuf.Struct context = 5;`
     */
    public fun clearContext() {
      _builder.clearContext()
    }
    /**
     * `.google.protobuf.Struct context = 5;`
     * @return Whether the context field is set.
     */
    public fun hasContext(): kotlin.Boolean {
      return _builder.hasContext()
    }

    /**
     * `int32 priority = 6;`
     */
    public var priority: kotlin.Int
      @JvmName("getPriority")
      get() = _builder.getPriority()
      @JvmName("setPriority")
      set(value) {
        _builder.setPriority(value)
      }
    /**
     * `int32 priority = 6;`
     */
    public fun clearPriority() {
      _builder.clearPriority()
    }

    /**
     * `.google.protobuf.Timestamp deadline = 7;`
     */
    public var deadline: com.google.protobuf.Timestamp
      @JvmName("getDeadline")
      get() = _builder.getDeadline()
      @JvmName("setDeadline")
      set(value) {
        _builder.setDeadline(value)
      }
    /**
     * `.google.protobuf.Timestamp deadline = 7;`
     */
    public fun clearDeadline() {
      _builder.clearDeadline()
    }
    /**
     * `.google.protobuf.Timestamp deadline = 7;`
     * @return Whether the deadline field is set.
     */
    public fun hasDeadline(): kotlin.Boolean {
      return _builder.hasDeadline()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.messaging.Messaging.AgentTaskRequest.copy(block: `unhinged.messaging`.AgentTaskRequestKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.AgentTaskRequest =
  `unhinged.messaging`.AgentTaskRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.messaging.Messaging.AgentTaskRequestOrBuilder.taskParametersOrNull: com.google.protobuf.Struct?
  get() = if (hasTaskParameters()) getTaskParameters() else null

public val unhinged.messaging.Messaging.AgentTaskRequestOrBuilder.contextOrNull: com.google.protobuf.Struct?
  get() = if (hasContext()) getContext() else null

public val unhinged.messaging.Messaging.AgentTaskRequestOrBuilder.deadlineOrNull: com.google.protobuf.Timestamp?
  get() = if (hasDeadline()) getDeadline() else null

