// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messaging.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.messaging;

@kotlin.jvm.JvmName("-initializelLMError")
public inline fun lLMError(block: unhinged.messaging.LLMErrorKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.LLMError =
  unhinged.messaging.LLMErrorKt.Dsl._create(unhinged.messaging.Messaging.LLMError.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.messaging.LLMError`
 */
public object LLMErrorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.messaging.Messaging.LLMError.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.messaging.Messaging.LLMError.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.messaging.Messaging.LLMError = _builder.build()

    /**
     * `string error_code = 1;`
     */
    public var errorCode: kotlin.String
      @JvmName("getErrorCode")
      get() = _builder.getErrorCode()
      @JvmName("setErrorCode")
      set(value) {
        _builder.setErrorCode(value)
      }
    /**
     * `string error_code = 1;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }

    /**
     * `string error_message = 2;`
     */
    public var errorMessage: kotlin.String
      @JvmName("getErrorMessage")
      get() = _builder.getErrorMessage()
      @JvmName("setErrorMessage")
      set(value) {
        _builder.setErrorMessage(value)
      }
    /**
     * `string error_message = 2;`
     */
    public fun clearErrorMessage() {
      _builder.clearErrorMessage()
    }

    /**
     * ```
     * "rate_limit", "context_length", "content_filter", "model_error"
     * ```
     *
     * `string error_type = 3;`
     */
    public var errorType: kotlin.String
      @JvmName("getErrorType")
      get() = _builder.getErrorType()
      @JvmName("setErrorType")
      set(value) {
        _builder.setErrorType(value)
      }
    /**
     * ```
     * "rate_limit", "context_length", "content_filter", "model_error"
     * ```
     *
     * `string error_type = 3;`
     */
    public fun clearErrorType() {
      _builder.clearErrorType()
    }

    /**
     * `bool is_retryable = 4;`
     */
    public var isRetryable: kotlin.Boolean
      @JvmName("getIsRetryable")
      get() = _builder.getIsRetryable()
      @JvmName("setIsRetryable")
      set(value) {
        _builder.setIsRetryable(value)
      }
    /**
     * `bool is_retryable = 4;`
     */
    public fun clearIsRetryable() {
      _builder.clearIsRetryable()
    }

    /**
     * `int32 retry_after_seconds = 5;`
     */
    public var retryAfterSeconds: kotlin.Int
      @JvmName("getRetryAfterSeconds")
      get() = _builder.getRetryAfterSeconds()
      @JvmName("setRetryAfterSeconds")
      set(value) {
        _builder.setRetryAfterSeconds(value)
      }
    /**
     * `int32 retry_after_seconds = 5;`
     */
    public fun clearRetryAfterSeconds() {
      _builder.clearRetryAfterSeconds()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.messaging.Messaging.LLMError.copy(block: `unhinged.messaging`.LLMErrorKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.LLMError =
  `unhinged.messaging`.LLMErrorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

