// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messaging.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.messaging;

@kotlin.jvm.JvmName("-initializelLMPromptResponse")
public inline fun lLMPromptResponse(block: unhinged.messaging.LLMPromptResponseKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.LLMPromptResponse =
  unhinged.messaging.LLMPromptResponseKt.Dsl._create(unhinged.messaging.Messaging.LLMPromptResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.messaging.LLMPromptResponse`
 */
public object LLMPromptResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.messaging.Messaging.LLMPromptResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.messaging.Messaging.LLMPromptResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.messaging.Messaging.LLMPromptResponse = _builder.build()

    /**
     * ```
     * Response content
     * ```
     *
     * `string response_text = 1;`
     */
    public var responseText: kotlin.String
      @JvmName("getResponseText")
      get() = _builder.getResponseText()
      @JvmName("setResponseText")
      set(value) {
        _builder.setResponseText(value)
      }
    /**
     * ```
     * Response content
     * ```
     *
     * `string response_text = 1;`
     */
    public fun clearResponseText() {
      _builder.clearResponseText()
    }

    /**
     * ```
     * "stop", "length", "content_filter", "tool_calls"
     * ```
     *
     * `string finish_reason = 2;`
     */
    public var finishReason: kotlin.String
      @JvmName("getFinishReason")
      get() = _builder.getFinishReason()
      @JvmName("setFinishReason")
      set(value) {
        _builder.setFinishReason(value)
      }
    /**
     * ```
     * "stop", "length", "content_filter", "tool_calls"
     * ```
     *
     * `string finish_reason = 2;`
     */
    public fun clearFinishReason() {
      _builder.clearFinishReason()
    }

    /**
     * ```
     * Token usage
     * ```
     *
     * `int32 prompt_tokens = 3;`
     */
    public var promptTokens: kotlin.Int
      @JvmName("getPromptTokens")
      get() = _builder.getPromptTokens()
      @JvmName("setPromptTokens")
      set(value) {
        _builder.setPromptTokens(value)
      }
    /**
     * ```
     * Token usage
     * ```
     *
     * `int32 prompt_tokens = 3;`
     */
    public fun clearPromptTokens() {
      _builder.clearPromptTokens()
    }

    /**
     * `int32 completion_tokens = 4;`
     */
    public var completionTokens: kotlin.Int
      @JvmName("getCompletionTokens")
      get() = _builder.getCompletionTokens()
      @JvmName("setCompletionTokens")
      set(value) {
        _builder.setCompletionTokens(value)
      }
    /**
     * `int32 completion_tokens = 4;`
     */
    public fun clearCompletionTokens() {
      _builder.clearCompletionTokens()
    }

    /**
     * `int32 total_tokens = 5;`
     */
    public var totalTokens: kotlin.Int
      @JvmName("getTotalTokens")
      get() = _builder.getTotalTokens()
      @JvmName("setTotalTokens")
      set(value) {
        _builder.setTotalTokens(value)
      }
    /**
     * `int32 total_tokens = 5;`
     */
    public fun clearTotalTokens() {
      _builder.clearTotalTokens()
    }

    /**
     * ```
     * Timing and performance
     * ```
     *
     * `float response_time_ms = 6;`
     */
    public var responseTimeMs: kotlin.Float
      @JvmName("getResponseTimeMs")
      get() = _builder.getResponseTimeMs()
      @JvmName("setResponseTimeMs")
      set(value) {
        _builder.setResponseTimeMs(value)
      }
    /**
     * ```
     * Timing and performance
     * ```
     *
     * `float response_time_ms = 6;`
     */
    public fun clearResponseTimeMs() {
      _builder.clearResponseTimeMs()
    }

    /**
     * `float tokens_per_second = 7;`
     */
    public var tokensPerSecond: kotlin.Float
      @JvmName("getTokensPerSecond")
      get() = _builder.getTokensPerSecond()
      @JvmName("setTokensPerSecond")
      set(value) {
        _builder.setTokensPerSecond(value)
      }
    /**
     * `float tokens_per_second = 7;`
     */
    public fun clearTokensPerSecond() {
      _builder.clearTokensPerSecond()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ToolCallsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Tool calls (if any)
     * ```
     *
     * `repeated .unhinged.messaging.ToolCall tool_calls = 8;`
     */
     public val toolCalls: com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, ToolCallsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getToolCallsList()
      )
    /**
     * ```
     * Tool calls (if any)
     * ```
     *
     * `repeated .unhinged.messaging.ToolCall tool_calls = 8;`
     * @param value The toolCalls to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addToolCalls")
    public fun com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, ToolCallsProxy>.add(value: unhinged.messaging.Messaging.ToolCall) {
      _builder.addToolCalls(value)
    }
    /**
     * ```
     * Tool calls (if any)
     * ```
     *
     * `repeated .unhinged.messaging.ToolCall tool_calls = 8;`
     * @param value The toolCalls to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignToolCalls")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, ToolCallsProxy>.plusAssign(value: unhinged.messaging.Messaging.ToolCall) {
      add(value)
    }
    /**
     * ```
     * Tool calls (if any)
     * ```
     *
     * `repeated .unhinged.messaging.ToolCall tool_calls = 8;`
     * @param values The toolCalls to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllToolCalls")
    public fun com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, ToolCallsProxy>.addAll(values: kotlin.collections.Iterable<unhinged.messaging.Messaging.ToolCall>) {
      _builder.addAllToolCalls(values)
    }
    /**
     * ```
     * Tool calls (if any)
     * ```
     *
     * `repeated .unhinged.messaging.ToolCall tool_calls = 8;`
     * @param values The toolCalls to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllToolCalls")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, ToolCallsProxy>.plusAssign(values: kotlin.collections.Iterable<unhinged.messaging.Messaging.ToolCall>) {
      addAll(values)
    }
    /**
     * ```
     * Tool calls (if any)
     * ```
     *
     * `repeated .unhinged.messaging.ToolCall tool_calls = 8;`
     * @param index The index to set the value at.
     * @param value The toolCalls to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setToolCalls")
    public operator fun com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, ToolCallsProxy>.set(index: kotlin.Int, value: unhinged.messaging.Messaging.ToolCall) {
      _builder.setToolCalls(index, value)
    }
    /**
     * ```
     * Tool calls (if any)
     * ```
     *
     * `repeated .unhinged.messaging.ToolCall tool_calls = 8;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearToolCalls")
    public fun com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, ToolCallsProxy>.clear() {
      _builder.clearToolCalls()
    }


    /**
     * ```
     * Response metadata
     * ```
     *
     * `.google.protobuf.Struct response_metadata = 9;`
     */
    public var responseMetadata: com.google.protobuf.Struct
      @JvmName("getResponseMetadata")
      get() = _builder.getResponseMetadata()
      @JvmName("setResponseMetadata")
      set(value) {
        _builder.setResponseMetadata(value)
      }
    /**
     * ```
     * Response metadata
     * ```
     *
     * `.google.protobuf.Struct response_metadata = 9;`
     */
    public fun clearResponseMetadata() {
      _builder.clearResponseMetadata()
    }
    /**
     * ```
     * Response metadata
     * ```
     *
     * `.google.protobuf.Struct response_metadata = 9;`
     * @return Whether the responseMetadata field is set.
     */
    public fun hasResponseMetadata(): kotlin.Boolean {
      return _builder.hasResponseMetadata()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.messaging.Messaging.LLMPromptResponse.copy(block: `unhinged.messaging`.LLMPromptResponseKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.LLMPromptResponse =
  `unhinged.messaging`.LLMPromptResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.messaging.Messaging.LLMPromptResponseOrBuilder.responseMetadataOrNull: com.google.protobuf.Struct?
  get() = if (hasResponseMetadata()) getResponseMetadata() else null

