// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messaging.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.messaging;

@kotlin.jvm.JvmName("-initializelLMStreamChunk")
public inline fun lLMStreamChunk(block: unhinged.messaging.LLMStreamChunkKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.LLMStreamChunk =
  unhinged.messaging.LLMStreamChunkKt.Dsl._create(unhinged.messaging.Messaging.LLMStreamChunk.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.messaging.LLMStreamChunk`
 */
public object LLMStreamChunkKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.messaging.Messaging.LLMStreamChunk.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.messaging.Messaging.LLMStreamChunk.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.messaging.Messaging.LLMStreamChunk = _builder.build()

    /**
     * `string chunk_text = 1;`
     */
    public var chunkText: kotlin.String
      @JvmName("getChunkText")
      get() = _builder.getChunkText()
      @JvmName("setChunkText")
      set(value) {
        _builder.setChunkText(value)
      }
    /**
     * `string chunk_text = 1;`
     */
    public fun clearChunkText() {
      _builder.clearChunkText()
    }

    /**
     * `int32 chunk_index = 2;`
     */
    public var chunkIndex: kotlin.Int
      @JvmName("getChunkIndex")
      get() = _builder.getChunkIndex()
      @JvmName("setChunkIndex")
      set(value) {
        _builder.setChunkIndex(value)
      }
    /**
     * `int32 chunk_index = 2;`
     */
    public fun clearChunkIndex() {
      _builder.clearChunkIndex()
    }

    /**
     * `bool is_final = 3;`
     */
    public var isFinal: kotlin.Boolean
      @JvmName("getIsFinal")
      get() = _builder.getIsFinal()
      @JvmName("setIsFinal")
      set(value) {
        _builder.setIsFinal(value)
      }
    /**
     * `bool is_final = 3;`
     */
    public fun clearIsFinal() {
      _builder.clearIsFinal()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PartialToolCallsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .unhinged.messaging.ToolCall partial_tool_calls = 4;`
     */
     public val partialToolCalls: com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, PartialToolCallsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getPartialToolCallsList()
      )
    /**
     * `repeated .unhinged.messaging.ToolCall partial_tool_calls = 4;`
     * @param value The partialToolCalls to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPartialToolCalls")
    public fun com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, PartialToolCallsProxy>.add(value: unhinged.messaging.Messaging.ToolCall) {
      _builder.addPartialToolCalls(value)
    }
    /**
     * `repeated .unhinged.messaging.ToolCall partial_tool_calls = 4;`
     * @param value The partialToolCalls to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPartialToolCalls")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, PartialToolCallsProxy>.plusAssign(value: unhinged.messaging.Messaging.ToolCall) {
      add(value)
    }
    /**
     * `repeated .unhinged.messaging.ToolCall partial_tool_calls = 4;`
     * @param values The partialToolCalls to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPartialToolCalls")
    public fun com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, PartialToolCallsProxy>.addAll(values: kotlin.collections.Iterable<unhinged.messaging.Messaging.ToolCall>) {
      _builder.addAllPartialToolCalls(values)
    }
    /**
     * `repeated .unhinged.messaging.ToolCall partial_tool_calls = 4;`
     * @param values The partialToolCalls to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPartialToolCalls")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, PartialToolCallsProxy>.plusAssign(values: kotlin.collections.Iterable<unhinged.messaging.Messaging.ToolCall>) {
      addAll(values)
    }
    /**
     * `repeated .unhinged.messaging.ToolCall partial_tool_calls = 4;`
     * @param index The index to set the value at.
     * @param value The partialToolCalls to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPartialToolCalls")
    public operator fun com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, PartialToolCallsProxy>.set(index: kotlin.Int, value: unhinged.messaging.Messaging.ToolCall) {
      _builder.setPartialToolCalls(index, value)
    }
    /**
     * `repeated .unhinged.messaging.ToolCall partial_tool_calls = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPartialToolCalls")
    public fun com.google.protobuf.kotlin.DslList<unhinged.messaging.Messaging.ToolCall, PartialToolCallsProxy>.clear() {
      _builder.clearPartialToolCalls()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.messaging.Messaging.LLMStreamChunk.copy(block: `unhinged.messaging`.LLMStreamChunkKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.LLMStreamChunk =
  `unhinged.messaging`.LLMStreamChunkKt.Dsl._create(this.toBuilder()).apply { block() }._build()

