// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messaging.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.messaging;

@kotlin.jvm.JvmName("-initializemessage")
public inline fun message(block: unhinged.messaging.MessageKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.Message =
  unhinged.messaging.MessageKt.Dsl._create(unhinged.messaging.Messaging.Message.newBuilder()).apply { block() }._build()
/**
 * ```
 * Universal message envelope for all inter-service communication
 * ```
 *
 * Protobuf type `unhinged.messaging.Message`
 */
public object MessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.messaging.Messaging.Message.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.messaging.Messaging.Message.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.messaging.Messaging.Message = _builder.build()

    /**
     * ```
     * Message identification
     * ```
     *
     * `string message_id = 1;`
     */
    public var messageId: kotlin.String
      @JvmName("getMessageId")
      get() = _builder.getMessageId()
      @JvmName("setMessageId")
      set(value) {
        _builder.setMessageId(value)
      }
    /**
     * ```
     * Message identification
     * ```
     *
     * `string message_id = 1;`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }

    /**
     * `string message_type = 2;`
     */
    public var messageType: kotlin.String
      @JvmName("getMessageType")
      get() = _builder.getMessageType()
      @JvmName("setMessageType")
      set(value) {
        _builder.setMessageType(value)
      }
    /**
     * `string message_type = 2;`
     */
    public fun clearMessageType() {
      _builder.clearMessageType()
    }

    /**
     * `string message_version = 3;`
     */
    public var messageVersion: kotlin.String
      @JvmName("getMessageVersion")
      get() = _builder.getMessageVersion()
      @JvmName("setMessageVersion")
      set(value) {
        _builder.setMessageVersion(value)
      }
    /**
     * `string message_version = 3;`
     */
    public fun clearMessageVersion() {
      _builder.clearMessageVersion()
    }

    /**
     * ```
     * Routing and delivery
     * ```
     *
     * `string from_service = 4;`
     */
    public var fromService: kotlin.String
      @JvmName("getFromService")
      get() = _builder.getFromService()
      @JvmName("setFromService")
      set(value) {
        _builder.setFromService(value)
      }
    /**
     * ```
     * Routing and delivery
     * ```
     *
     * `string from_service = 4;`
     */
    public fun clearFromService() {
      _builder.clearFromService()
    }

    /**
     * `string to_service = 5;`
     */
    public var toService: kotlin.String
      @JvmName("getToService")
      get() = _builder.getToService()
      @JvmName("setToService")
      set(value) {
        _builder.setToService(value)
      }
    /**
     * `string to_service = 5;`
     */
    public fun clearToService() {
      _builder.clearToService()
    }

    /**
     * `string routing_key = 6;`
     */
    public var routingKey: kotlin.String
      @JvmName("getRoutingKey")
      get() = _builder.getRoutingKey()
      @JvmName("setRoutingKey")
      set(value) {
        _builder.setRoutingKey(value)
      }
    /**
     * `string routing_key = 6;`
     */
    public fun clearRoutingKey() {
      _builder.clearRoutingKey()
    }

    /**
     * ```
     * Timing and correlation
     * ```
     *
     * `.google.protobuf.Timestamp created_at = 7;`
     */
    public var createdAt: com.google.protobuf.Timestamp
      @JvmName("getCreatedAt")
      get() = _builder.getCreatedAt()
      @JvmName("setCreatedAt")
      set(value) {
        _builder.setCreatedAt(value)
      }
    /**
     * ```
     * Timing and correlation
     * ```
     *
     * `.google.protobuf.Timestamp created_at = 7;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
    /**
     * ```
     * Timing and correlation
     * ```
     *
     * `.google.protobuf.Timestamp created_at = 7;`
     * @return Whether the createdAt field is set.
     */
    public fun hasCreatedAt(): kotlin.Boolean {
      return _builder.hasCreatedAt()
    }

    /**
     * `.google.protobuf.Timestamp expires_at = 8;`
     */
    public var expiresAt: com.google.protobuf.Timestamp
      @JvmName("getExpiresAt")
      get() = _builder.getExpiresAt()
      @JvmName("setExpiresAt")
      set(value) {
        _builder.setExpiresAt(value)
      }
    /**
     * `.google.protobuf.Timestamp expires_at = 8;`
     */
    public fun clearExpiresAt() {
      _builder.clearExpiresAt()
    }
    /**
     * `.google.protobuf.Timestamp expires_at = 8;`
     * @return Whether the expiresAt field is set.
     */
    public fun hasExpiresAt(): kotlin.Boolean {
      return _builder.hasExpiresAt()
    }

    /**
     * `string correlation_id = 9;`
     */
    public var correlationId: kotlin.String
      @JvmName("getCorrelationId")
      get() = _builder.getCorrelationId()
      @JvmName("setCorrelationId")
      set(value) {
        _builder.setCorrelationId(value)
      }
    /**
     * `string correlation_id = 9;`
     */
    public fun clearCorrelationId() {
      _builder.clearCorrelationId()
    }

    /**
     * `string reply_to = 10;`
     */
    public var replyTo: kotlin.String
      @JvmName("getReplyTo")
      get() = _builder.getReplyTo()
      @JvmName("setReplyTo")
      set(value) {
        _builder.setReplyTo(value)
      }
    /**
     * `string reply_to = 10;`
     */
    public fun clearReplyTo() {
      _builder.clearReplyTo()
    }

    /**
     * ```
     * Context
     * ```
     *
     * `string user_id = 11;`
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * ```
     * Context
     * ```
     *
     * `string user_id = 11;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `string session_id = 12;`
     */
    public var sessionId: kotlin.String
      @JvmName("getSessionId")
      get() = _builder.getSessionId()
      @JvmName("setSessionId")
      set(value) {
        _builder.setSessionId(value)
      }
    /**
     * `string session_id = 12;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `string trace_id = 13;`
     */
    public var traceId: kotlin.String
      @JvmName("getTraceId")
      get() = _builder.getTraceId()
      @JvmName("setTraceId")
      set(value) {
        _builder.setTraceId(value)
      }
    /**
     * `string trace_id = 13;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }

    /**
     * `.unhinged.messaging.LLMMessage llm_message = 20;`
     */
    public var llmMessage: unhinged.messaging.Messaging.LLMMessage
      @JvmName("getLlmMessage")
      get() = _builder.getLlmMessage()
      @JvmName("setLlmMessage")
      set(value) {
        _builder.setLlmMessage(value)
      }
    /**
     * `.unhinged.messaging.LLMMessage llm_message = 20;`
     */
    public fun clearLlmMessage() {
      _builder.clearLlmMessage()
    }
    /**
     * `.unhinged.messaging.LLMMessage llm_message = 20;`
     * @return Whether the llmMessage field is set.
     */
    public fun hasLlmMessage(): kotlin.Boolean {
      return _builder.hasLlmMessage()
    }

    /**
     * `.unhinged.messaging.AgentMessage agent_message = 21;`
     */
    public var agentMessage: unhinged.messaging.Messaging.AgentMessage
      @JvmName("getAgentMessage")
      get() = _builder.getAgentMessage()
      @JvmName("setAgentMessage")
      set(value) {
        _builder.setAgentMessage(value)
      }
    /**
     * `.unhinged.messaging.AgentMessage agent_message = 21;`
     */
    public fun clearAgentMessage() {
      _builder.clearAgentMessage()
    }
    /**
     * `.unhinged.messaging.AgentMessage agent_message = 21;`
     * @return Whether the agentMessage field is set.
     */
    public fun hasAgentMessage(): kotlin.Boolean {
      return _builder.hasAgentMessage()
    }

    /**
     * `.unhinged.messaging.ToolMessage tool_message = 22;`
     */
    public var toolMessage: unhinged.messaging.Messaging.ToolMessage
      @JvmName("getToolMessage")
      get() = _builder.getToolMessage()
      @JvmName("setToolMessage")
      set(value) {
        _builder.setToolMessage(value)
      }
    /**
     * `.unhinged.messaging.ToolMessage tool_message = 22;`
     */
    public fun clearToolMessage() {
      _builder.clearToolMessage()
    }
    /**
     * `.unhinged.messaging.ToolMessage tool_message = 22;`
     * @return Whether the toolMessage field is set.
     */
    public fun hasToolMessage(): kotlin.Boolean {
      return _builder.hasToolMessage()
    }

    /**
     * `.unhinged.messaging.WorkflowMessage workflow_message = 23;`
     */
    public var workflowMessage: unhinged.messaging.Messaging.WorkflowMessage
      @JvmName("getWorkflowMessage")
      get() = _builder.getWorkflowMessage()
      @JvmName("setWorkflowMessage")
      set(value) {
        _builder.setWorkflowMessage(value)
      }
    /**
     * `.unhinged.messaging.WorkflowMessage workflow_message = 23;`
     */
    public fun clearWorkflowMessage() {
      _builder.clearWorkflowMessage()
    }
    /**
     * `.unhinged.messaging.WorkflowMessage workflow_message = 23;`
     * @return Whether the workflowMessage field is set.
     */
    public fun hasWorkflowMessage(): kotlin.Boolean {
      return _builder.hasWorkflowMessage()
    }

    /**
     * `.unhinged.messaging.UIMessage ui_message = 24;`
     */
    public var uiMessage: unhinged.messaging.Messaging.UIMessage
      @JvmName("getUiMessage")
      get() = _builder.getUiMessage()
      @JvmName("setUiMessage")
      set(value) {
        _builder.setUiMessage(value)
      }
    /**
     * `.unhinged.messaging.UIMessage ui_message = 24;`
     */
    public fun clearUiMessage() {
      _builder.clearUiMessage()
    }
    /**
     * `.unhinged.messaging.UIMessage ui_message = 24;`
     * @return Whether the uiMessage field is set.
     */
    public fun hasUiMessage(): kotlin.Boolean {
      return _builder.hasUiMessage()
    }

    /**
     * `.unhinged.messaging.SystemMessage system_message = 25;`
     */
    public var systemMessage: unhinged.messaging.Messaging.SystemMessage
      @JvmName("getSystemMessage")
      get() = _builder.getSystemMessage()
      @JvmName("setSystemMessage")
      set(value) {
        _builder.setSystemMessage(value)
      }
    /**
     * `.unhinged.messaging.SystemMessage system_message = 25;`
     */
    public fun clearSystemMessage() {
      _builder.clearSystemMessage()
    }
    /**
     * `.unhinged.messaging.SystemMessage system_message = 25;`
     * @return Whether the systemMessage field is set.
     */
    public fun hasSystemMessage(): kotlin.Boolean {
      return _builder.hasSystemMessage()
    }

    /**
     * ```
     * Delivery options
     * ```
     *
     * `.unhinged.messaging.MessageOptions options = 30;`
     */
    public var options: unhinged.messaging.Messaging.MessageOptions
      @JvmName("getOptions")
      get() = _builder.getOptions()
      @JvmName("setOptions")
      set(value) {
        _builder.setOptions(value)
      }
    /**
     * ```
     * Delivery options
     * ```
     *
     * `.unhinged.messaging.MessageOptions options = 30;`
     */
    public fun clearOptions() {
      _builder.clearOptions()
    }
    /**
     * ```
     * Delivery options
     * ```
     *
     * `.unhinged.messaging.MessageOptions options = 30;`
     * @return Whether the options field is set.
     */
    public fun hasOptions(): kotlin.Boolean {
      return _builder.hasOptions()
    }

    /**
     * `.google.protobuf.Struct metadata = 31;`
     */
    public var metadata: com.google.protobuf.Struct
      @JvmName("getMetadata")
      get() = _builder.getMetadata()
      @JvmName("setMetadata")
      set(value) {
        _builder.setMetadata(value)
      }
    /**
     * `.google.protobuf.Struct metadata = 31;`
     */
    public fun clearMetadata() {
      _builder.clearMetadata()
    }
    /**
     * `.google.protobuf.Struct metadata = 31;`
     * @return Whether the metadata field is set.
     */
    public fun hasMetadata(): kotlin.Boolean {
      return _builder.hasMetadata()
    }
    public val payloadCase: unhinged.messaging.Messaging.Message.PayloadCase
      @JvmName("getPayloadCase")
      get() = _builder.getPayloadCase()

    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.messaging.Messaging.Message.copy(block: `unhinged.messaging`.MessageKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.Message =
  `unhinged.messaging`.MessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.messaging.Messaging.MessageOrBuilder.createdAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasCreatedAt()) getCreatedAt() else null

public val unhinged.messaging.Messaging.MessageOrBuilder.expiresAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasExpiresAt()) getExpiresAt() else null

public val unhinged.messaging.Messaging.MessageOrBuilder.llmMessageOrNull: unhinged.messaging.Messaging.LLMMessage?
  get() = if (hasLlmMessage()) getLlmMessage() else null

public val unhinged.messaging.Messaging.MessageOrBuilder.agentMessageOrNull: unhinged.messaging.Messaging.AgentMessage?
  get() = if (hasAgentMessage()) getAgentMessage() else null

public val unhinged.messaging.Messaging.MessageOrBuilder.toolMessageOrNull: unhinged.messaging.Messaging.ToolMessage?
  get() = if (hasToolMessage()) getToolMessage() else null

public val unhinged.messaging.Messaging.MessageOrBuilder.workflowMessageOrNull: unhinged.messaging.Messaging.WorkflowMessage?
  get() = if (hasWorkflowMessage()) getWorkflowMessage() else null

public val unhinged.messaging.Messaging.MessageOrBuilder.uiMessageOrNull: unhinged.messaging.Messaging.UIMessage?
  get() = if (hasUiMessage()) getUiMessage() else null

public val unhinged.messaging.Messaging.MessageOrBuilder.systemMessageOrNull: unhinged.messaging.Messaging.SystemMessage?
  get() = if (hasSystemMessage()) getSystemMessage() else null

public val unhinged.messaging.Messaging.MessageOrBuilder.optionsOrNull: unhinged.messaging.Messaging.MessageOptions?
  get() = if (hasOptions()) getOptions() else null

public val unhinged.messaging.Messaging.MessageOrBuilder.metadataOrNull: com.google.protobuf.Struct?
  get() = if (hasMetadata()) getMetadata() else null

