// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messaging.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.messaging;

@kotlin.jvm.JvmName("-initializesendMessageResult")
public inline fun sendMessageResult(block: unhinged.messaging.SendMessageResultKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.SendMessageResult =
  unhinged.messaging.SendMessageResultKt.Dsl._create(unhinged.messaging.Messaging.SendMessageResult.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.messaging.SendMessageResult`
 */
public object SendMessageResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.messaging.Messaging.SendMessageResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.messaging.Messaging.SendMessageResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.messaging.Messaging.SendMessageResult = _builder.build()

    /**
     * `string message_id = 1;`
     */
    public var messageId: kotlin.String
      @JvmName("getMessageId")
      get() = _builder.getMessageId()
      @JvmName("setMessageId")
      set(value) {
        _builder.setMessageId(value)
      }
    /**
     * `string message_id = 1;`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }

    /**
     * `bool success = 2;`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * `bool success = 2;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * `string error_message = 3;`
     */
    public var errorMessage: kotlin.String
      @JvmName("getErrorMessage")
      get() = _builder.getErrorMessage()
      @JvmName("setErrorMessage")
      set(value) {
        _builder.setErrorMessage(value)
      }
    /**
     * `string error_message = 3;`
     */
    public fun clearErrorMessage() {
      _builder.clearErrorMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.messaging.Messaging.SendMessageResult.copy(block: `unhinged.messaging`.SendMessageResultKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.SendMessageResult =
  `unhinged.messaging`.SendMessageResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

