// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messaging.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.messaging;

@kotlin.jvm.JvmName("-initializeshutdownNotice")
public inline fun shutdownNotice(block: unhinged.messaging.ShutdownNoticeKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.ShutdownNotice =
  unhinged.messaging.ShutdownNoticeKt.Dsl._create(unhinged.messaging.Messaging.ShutdownNotice.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.messaging.ShutdownNotice`
 */
public object ShutdownNoticeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.messaging.Messaging.ShutdownNotice.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.messaging.Messaging.ShutdownNotice.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.messaging.Messaging.ShutdownNotice = _builder.build()

    /**
     * `string service_name = 1;`
     */
    public var serviceName: kotlin.String
      @JvmName("getServiceName")
      get() = _builder.getServiceName()
      @JvmName("setServiceName")
      set(value) {
        _builder.setServiceName(value)
      }
    /**
     * `string service_name = 1;`
     */
    public fun clearServiceName() {
      _builder.clearServiceName()
    }

    /**
     * `string shutdown_reason = 2;`
     */
    public var shutdownReason: kotlin.String
      @JvmName("getShutdownReason")
      get() = _builder.getShutdownReason()
      @JvmName("setShutdownReason")
      set(value) {
        _builder.setShutdownReason(value)
      }
    /**
     * `string shutdown_reason = 2;`
     */
    public fun clearShutdownReason() {
      _builder.clearShutdownReason()
    }

    /**
     * `int32 graceful_shutdown_seconds = 3;`
     */
    public var gracefulShutdownSeconds: kotlin.Int
      @JvmName("getGracefulShutdownSeconds")
      get() = _builder.getGracefulShutdownSeconds()
      @JvmName("setGracefulShutdownSeconds")
      set(value) {
        _builder.setGracefulShutdownSeconds(value)
      }
    /**
     * `int32 graceful_shutdown_seconds = 3;`
     */
    public fun clearGracefulShutdownSeconds() {
      _builder.clearGracefulShutdownSeconds()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.messaging.Messaging.ShutdownNotice.copy(block: `unhinged.messaging`.ShutdownNoticeKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.ShutdownNotice =
  `unhinged.messaging`.ShutdownNoticeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

