// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messaging.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.messaging;

@kotlin.jvm.JvmName("-initializetoolCall")
public inline fun toolCall(block: unhinged.messaging.ToolCallKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.ToolCall =
  unhinged.messaging.ToolCallKt.Dsl._create(unhinged.messaging.Messaging.ToolCall.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.messaging.ToolCall`
 */
public object ToolCallKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.messaging.Messaging.ToolCall.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.messaging.Messaging.ToolCall.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.messaging.Messaging.ToolCall = _builder.build()

    /**
     * `string tool_id = 1;`
     */
    public var toolId: kotlin.String
      @JvmName("getToolId")
      get() = _builder.getToolId()
      @JvmName("setToolId")
      set(value) {
        _builder.setToolId(value)
      }
    /**
     * `string tool_id = 1;`
     */
    public fun clearToolId() {
      _builder.clearToolId()
    }

    /**
     * `string tool_name = 2;`
     */
    public var toolName: kotlin.String
      @JvmName("getToolName")
      get() = _builder.getToolName()
      @JvmName("setToolName")
      set(value) {
        _builder.setToolName(value)
      }
    /**
     * `string tool_name = 2;`
     */
    public fun clearToolName() {
      _builder.clearToolName()
    }

    /**
     * `.google.protobuf.Struct tool_arguments = 3;`
     */
    public var toolArguments: com.google.protobuf.Struct
      @JvmName("getToolArguments")
      get() = _builder.getToolArguments()
      @JvmName("setToolArguments")
      set(value) {
        _builder.setToolArguments(value)
      }
    /**
     * `.google.protobuf.Struct tool_arguments = 3;`
     */
    public fun clearToolArguments() {
      _builder.clearToolArguments()
    }
    /**
     * `.google.protobuf.Struct tool_arguments = 3;`
     * @return Whether the toolArguments field is set.
     */
    public fun hasToolArguments(): kotlin.Boolean {
      return _builder.hasToolArguments()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.messaging.Messaging.ToolCall.copy(block: `unhinged.messaging`.ToolCallKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.ToolCall =
  `unhinged.messaging`.ToolCallKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.messaging.Messaging.ToolCallOrBuilder.toolArgumentsOrNull: com.google.protobuf.Struct?
  get() = if (hasToolArguments()) getToolArguments() else null

