// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messaging.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.messaging;

@kotlin.jvm.JvmName("-initializetoolError")
public inline fun toolError(block: unhinged.messaging.ToolErrorKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.ToolError =
  unhinged.messaging.ToolErrorKt.Dsl._create(unhinged.messaging.Messaging.ToolError.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.messaging.ToolError`
 */
public object ToolErrorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.messaging.Messaging.ToolError.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.messaging.Messaging.ToolError.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.messaging.Messaging.ToolError = _builder.build()

    /**
     * `string invocation_id = 1;`
     */
    public var invocationId: kotlin.String
      @JvmName("getInvocationId")
      get() = _builder.getInvocationId()
      @JvmName("setInvocationId")
      set(value) {
        _builder.setInvocationId(value)
      }
    /**
     * `string invocation_id = 1;`
     */
    public fun clearInvocationId() {
      _builder.clearInvocationId()
    }

    /**
     * `string error_code = 2;`
     */
    public var errorCode: kotlin.String
      @JvmName("getErrorCode")
      get() = _builder.getErrorCode()
      @JvmName("setErrorCode")
      set(value) {
        _builder.setErrorCode(value)
      }
    /**
     * `string error_code = 2;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }

    /**
     * `string error_message = 3;`
     */
    public var errorMessage: kotlin.String
      @JvmName("getErrorMessage")
      get() = _builder.getErrorMessage()
      @JvmName("setErrorMessage")
      set(value) {
        _builder.setErrorMessage(value)
      }
    /**
     * `string error_message = 3;`
     */
    public fun clearErrorMessage() {
      _builder.clearErrorMessage()
    }

    /**
     * `bool is_retryable = 4;`
     */
    public var isRetryable: kotlin.Boolean
      @JvmName("getIsRetryable")
      get() = _builder.getIsRetryable()
      @JvmName("setIsRetryable")
      set(value) {
        _builder.setIsRetryable(value)
      }
    /**
     * `bool is_retryable = 4;`
     */
    public fun clearIsRetryable() {
      _builder.clearIsRetryable()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.messaging.Messaging.ToolError.copy(block: `unhinged.messaging`.ToolErrorKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.ToolError =
  `unhinged.messaging`.ToolErrorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

