// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messaging.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.messaging;

@kotlin.jvm.JvmName("-initializetoolMessage")
public inline fun toolMessage(block: unhinged.messaging.ToolMessageKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.ToolMessage =
  unhinged.messaging.ToolMessageKt.Dsl._create(unhinged.messaging.Messaging.ToolMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.messaging.ToolMessage`
 */
public object ToolMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.messaging.Messaging.ToolMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.messaging.Messaging.ToolMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.messaging.Messaging.ToolMessage = _builder.build()

    /**
     * `string tool_id = 1;`
     */
    public var toolId: kotlin.String
      @JvmName("getToolId")
      get() = _builder.getToolId()
      @JvmName("setToolId")
      set(value) {
        _builder.setToolId(value)
      }
    /**
     * `string tool_id = 1;`
     */
    public fun clearToolId() {
      _builder.clearToolId()
    }

    /**
     * `string tool_name = 2;`
     */
    public var toolName: kotlin.String
      @JvmName("getToolName")
      get() = _builder.getToolName()
      @JvmName("setToolName")
      set(value) {
        _builder.setToolName(value)
      }
    /**
     * `string tool_name = 2;`
     */
    public fun clearToolName() {
      _builder.clearToolName()
    }

    /**
     * `string tool_version = 3;`
     */
    public var toolVersion: kotlin.String
      @JvmName("getToolVersion")
      get() = _builder.getToolVersion()
      @JvmName("setToolVersion")
      set(value) {
        _builder.setToolVersion(value)
      }
    /**
     * `string tool_version = 3;`
     */
    public fun clearToolVersion() {
      _builder.clearToolVersion()
    }

    /**
     * `.unhinged.messaging.ToolMessageType message_type = 4;`
     */
    public var messageType: unhinged.messaging.Messaging.ToolMessageType
      @JvmName("getMessageType")
      get() = _builder.getMessageType()
      @JvmName("setMessageType")
      set(value) {
        _builder.setMessageType(value)
      }
    public var messageTypeValue: kotlin.Int
      @JvmName("getMessageTypeValue")
      get() = _builder.getMessageTypeValue()
      @JvmName("setMessageTypeValue")
      set(value) {
        _builder.setMessageTypeValue(value)
      }
    /**
     * `.unhinged.messaging.ToolMessageType message_type = 4;`
     */
    public fun clearMessageType() {
      _builder.clearMessageType()
    }

    /**
     * `.unhinged.messaging.ToolInvocation invocation = 10;`
     */
    public var invocation: unhinged.messaging.Messaging.ToolInvocation
      @JvmName("getInvocation")
      get() = _builder.getInvocation()
      @JvmName("setInvocation")
      set(value) {
        _builder.setInvocation(value)
      }
    /**
     * `.unhinged.messaging.ToolInvocation invocation = 10;`
     */
    public fun clearInvocation() {
      _builder.clearInvocation()
    }
    /**
     * `.unhinged.messaging.ToolInvocation invocation = 10;`
     * @return Whether the invocation field is set.
     */
    public fun hasInvocation(): kotlin.Boolean {
      return _builder.hasInvocation()
    }

    /**
     * `.unhinged.messaging.ToolResult result = 11;`
     */
    public var result: unhinged.messaging.Messaging.ToolResult
      @JvmName("getResult")
      get() = _builder.getResult()
      @JvmName("setResult")
      set(value) {
        _builder.setResult(value)
      }
    /**
     * `.unhinged.messaging.ToolResult result = 11;`
     */
    public fun clearResult() {
      _builder.clearResult()
    }
    /**
     * `.unhinged.messaging.ToolResult result = 11;`
     * @return Whether the result field is set.
     */
    public fun hasResult(): kotlin.Boolean {
      return _builder.hasResult()
    }

    /**
     * `.unhinged.messaging.ToolError tool_error = 12;`
     */
    public var toolError: unhinged.messaging.Messaging.ToolError
      @JvmName("getToolError")
      get() = _builder.getToolError()
      @JvmName("setToolError")
      set(value) {
        _builder.setToolError(value)
      }
    /**
     * `.unhinged.messaging.ToolError tool_error = 12;`
     */
    public fun clearToolError() {
      _builder.clearToolError()
    }
    /**
     * `.unhinged.messaging.ToolError tool_error = 12;`
     * @return Whether the toolError field is set.
     */
    public fun hasToolError(): kotlin.Boolean {
      return _builder.hasToolError()
    }

    /**
     * `.unhinged.messaging.ToolRegistration registration = 13;`
     */
    public var registration: unhinged.messaging.Messaging.ToolRegistration
      @JvmName("getRegistration")
      get() = _builder.getRegistration()
      @JvmName("setRegistration")
      set(value) {
        _builder.setRegistration(value)
      }
    /**
     * `.unhinged.messaging.ToolRegistration registration = 13;`
     */
    public fun clearRegistration() {
      _builder.clearRegistration()
    }
    /**
     * `.unhinged.messaging.ToolRegistration registration = 13;`
     * @return Whether the registration field is set.
     */
    public fun hasRegistration(): kotlin.Boolean {
      return _builder.hasRegistration()
    }
    public val messageDataCase: unhinged.messaging.Messaging.ToolMessage.MessageDataCase
      @JvmName("getMessageDataCase")
      get() = _builder.getMessageDataCase()

    public fun clearMessageData() {
      _builder.clearMessageData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.messaging.Messaging.ToolMessage.copy(block: `unhinged.messaging`.ToolMessageKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.ToolMessage =
  `unhinged.messaging`.ToolMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.messaging.Messaging.ToolMessageOrBuilder.invocationOrNull: unhinged.messaging.Messaging.ToolInvocation?
  get() = if (hasInvocation()) getInvocation() else null

public val unhinged.messaging.Messaging.ToolMessageOrBuilder.resultOrNull: unhinged.messaging.Messaging.ToolResult?
  get() = if (hasResult()) getResult() else null

public val unhinged.messaging.Messaging.ToolMessageOrBuilder.toolErrorOrNull: unhinged.messaging.Messaging.ToolError?
  get() = if (hasToolError()) getToolError() else null

public val unhinged.messaging.Messaging.ToolMessageOrBuilder.registrationOrNull: unhinged.messaging.Messaging.ToolRegistration?
  get() = if (hasRegistration()) getRegistration() else null

