// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messaging.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.messaging;

@kotlin.jvm.JvmName("-initializeuIUpdate")
public inline fun uIUpdate(block: unhinged.messaging.UIUpdateKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.UIUpdate =
  unhinged.messaging.UIUpdateKt.Dsl._create(unhinged.messaging.Messaging.UIUpdate.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.messaging.UIUpdate`
 */
public object UIUpdateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.messaging.Messaging.UIUpdate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.messaging.Messaging.UIUpdate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.messaging.Messaging.UIUpdate = _builder.build()

    /**
     * ```
     * "data", "state", "progress", "error"
     * ```
     *
     * `string update_type = 1;`
     */
    public var updateType: kotlin.String
      @JvmName("getUpdateType")
      get() = _builder.getUpdateType()
      @JvmName("setUpdateType")
      set(value) {
        _builder.setUpdateType(value)
      }
    /**
     * ```
     * "data", "state", "progress", "error"
     * ```
     *
     * `string update_type = 1;`
     */
    public fun clearUpdateType() {
      _builder.clearUpdateType()
    }

    /**
     * `.google.protobuf.Struct update_data = 2;`
     */
    public var updateData: com.google.protobuf.Struct
      @JvmName("getUpdateData")
      get() = _builder.getUpdateData()
      @JvmName("setUpdateData")
      set(value) {
        _builder.setUpdateData(value)
      }
    /**
     * `.google.protobuf.Struct update_data = 2;`
     */
    public fun clearUpdateData() {
      _builder.clearUpdateData()
    }
    /**
     * `.google.protobuf.Struct update_data = 2;`
     * @return Whether the updateData field is set.
     */
    public fun hasUpdateData(): kotlin.Boolean {
      return _builder.hasUpdateData()
    }

    /**
     * `bool force_refresh = 3;`
     */
    public var forceRefresh: kotlin.Boolean
      @JvmName("getForceRefresh")
      get() = _builder.getForceRefresh()
      @JvmName("setForceRefresh")
      set(value) {
        _builder.setForceRefresh(value)
      }
    /**
     * `bool force_refresh = 3;`
     */
    public fun clearForceRefresh() {
      _builder.clearForceRefresh()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.messaging.Messaging.UIUpdate.copy(block: `unhinged.messaging`.UIUpdateKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.UIUpdate =
  `unhinged.messaging`.UIUpdateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.messaging.Messaging.UIUpdateOrBuilder.updateDataOrNull: com.google.protobuf.Struct?
  get() = if (hasUpdateData()) getUpdateData() else null

