// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messaging.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package unhinged.messaging;

@kotlin.jvm.JvmName("-initializeworkflowControl")
public inline fun workflowControl(block: unhinged.messaging.WorkflowControlKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.WorkflowControl =
  unhinged.messaging.WorkflowControlKt.Dsl._create(unhinged.messaging.Messaging.WorkflowControl.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `unhinged.messaging.WorkflowControl`
 */
public object WorkflowControlKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: unhinged.messaging.Messaging.WorkflowControl.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: unhinged.messaging.Messaging.WorkflowControl.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): unhinged.messaging.Messaging.WorkflowControl = _builder.build()

    /**
     * ```
     * "pause", "resume", "cancel", "retry"
     * ```
     *
     * `string control_action = 1;`
     */
    public var controlAction: kotlin.String
      @JvmName("getControlAction")
      get() = _builder.getControlAction()
      @JvmName("setControlAction")
      set(value) {
        _builder.setControlAction(value)
      }
    /**
     * ```
     * "pause", "resume", "cancel", "retry"
     * ```
     *
     * `string control_action = 1;`
     */
    public fun clearControlAction() {
      _builder.clearControlAction()
    }

    /**
     * `string control_reason = 2;`
     */
    public var controlReason: kotlin.String
      @JvmName("getControlReason")
      get() = _builder.getControlReason()
      @JvmName("setControlReason")
      set(value) {
        _builder.setControlReason(value)
      }
    /**
     * `string control_reason = 2;`
     */
    public fun clearControlReason() {
      _builder.clearControlReason()
    }

    /**
     * `.google.protobuf.Struct control_parameters = 3;`
     */
    public var controlParameters: com.google.protobuf.Struct
      @JvmName("getControlParameters")
      get() = _builder.getControlParameters()
      @JvmName("setControlParameters")
      set(value) {
        _builder.setControlParameters(value)
      }
    /**
     * `.google.protobuf.Struct control_parameters = 3;`
     */
    public fun clearControlParameters() {
      _builder.clearControlParameters()
    }
    /**
     * `.google.protobuf.Struct control_parameters = 3;`
     * @return Whether the controlParameters field is set.
     */
    public fun hasControlParameters(): kotlin.Boolean {
      return _builder.hasControlParameters()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun unhinged.messaging.Messaging.WorkflowControl.copy(block: `unhinged.messaging`.WorkflowControlKt.Dsl.() -> kotlin.Unit): unhinged.messaging.Messaging.WorkflowControl =
  `unhinged.messaging`.WorkflowControlKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val unhinged.messaging.Messaging.WorkflowControlOrBuilder.controlParametersOrNull: com.google.protobuf.Struct?
  get() = if (hasControlParameters()) getControlParameters() else null

