# @llm-type config.app
# @llm-does development environment settings for unhinged system deve...
environment: "development"
version: "1.0"
last_updated: "2025-10-20T20:00:00Z"

# Deployment Configuration
deployment:
  compose_file: "control/orchestration/docker-compose.development.yml"
  observability_file: "control/orchestration/docker-compose.observability.yml"
  replicas:
    frontend: 1
    backend: 1
    database: 1
    redis: 1
    kafka: 1

# Resource Limits (Relaxed for development)
resources:
  frontend:
    memory: "256Mi"
    cpu: "0.25"
  backend:
    memory: "512Mi"
    cpu: "0.5"
  database:
    memory: "512Mi"
    cpu: "0.5"
  ai_ml:
    memory: "1Gi"
    cpu: "0.5"

# Security Configuration (Relaxed for development)
security:
  enable_tls: false
  require_authentication: false
  enable_rbac: false
  secret_management: "local"
  network_policies: "permissive"

# Monitoring Configuration
monitoring:
  enable_metrics: true
  enable_logging: true
  enable_tracing: true
  log_level: "DEBUG"
  metrics_retention: "7d"
  traces_retention: "1d"

# Performance Configuration
performance:
  enable_caching: false
  connection_pooling: false
  query_optimization: false
  compression: false

# Development Features
development:
  hot_reload: true
  debug_mode: true
  verbose_logging: true
  enable_profiling: true
  mock_external_services: true

# Networking
networking:
  external_access: true
  load_balancer: false
  cdn: false
  rate_limiting: false
