# Unhinged Production Environment Configuration
# @llm-type control-config
# @llm-legend Production environment settings for Unhinged system deployment
# @llm-key Production-grade configuration with security, performance, and reliability settings
# @llm-map Production environment control configuration for operational deployment
# @llm-axiom Production environment must prioritize security, performance, and reliability
# @llm-token production-config: Production environment configuration for operational control

environment: "production"
version: "1.0"
last_updated: "2025-10-20T20:00:00Z"

# Deployment Configuration
deployment:
  compose_file: "control/orchestration/docker-compose.production.yml"
  observability_file: "control/orchestration/docker-compose.observability.yml"
  replicas:
    frontend: 2
    backend: 3
    database: 1
    redis: 1
    kafka: 1
  
# Resource Limits
resources:
  frontend:
    memory: "512Mi"
    cpu: "0.5"
  backend:
    memory: "1Gi"
    cpu: "1.0"
  database:
    memory: "2Gi"
    cpu: "1.0"
  ai_ml:
    memory: "4Gi"
    cpu: "2.0"

# Security Configuration
security:
  enable_tls: true
  require_authentication: true
  enable_rbac: true
  secret_management: "external"
  network_policies: "strict"

# Monitoring Configuration
monitoring:
  enable_metrics: true
  enable_logging: true
  enable_tracing: true
  log_level: "INFO"
  metrics_retention: "30d"
  traces_retention: "7d"

# Performance Configuration
performance:
  enable_caching: true
  connection_pooling: true
  query_optimization: true
  compression: true

# Backup Configuration
backup:
  enable_automated_backup: true
  backup_schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
  backup_storage: "s3"

# Networking
networking:
  external_access: true
  load_balancer: true
  cdn: true
  rate_limiting: true
